### DISCUSSION TITLE
Self Hosted app response to clicks

### DISCUSSION THREAD

**Discussion by trmendes** [Freika/dawarich#1160] [Q&A]
Hi,
I have the latest version of Dawarich installed on my Synology NAS using Docker. The system has sufficient CPU and memory, but the app is extremely slow — each action takes 10–15 seconds, and I only see a blue bar at the top while it loads.

I'm using the official docker-compose file from the tutorial, with only minor changes (timezone and database password). I suspect this might be a configuration issue, but I'm not sure where to look.

Has anyone experienced similar performance issues? Are there specific settings I should check (e.g., volume mounts, network mode, database optimization)?

Thank you

**Comment by Freika** [comment]
You can give your Dawarich instance more resources by changing limits in the docker compose file and see if it helped

**Comment by trmendes** [comment]
Hi @Freika,

Thank you for your message.

I’ve made some changes to my docker-compose file, but the performance is still very slow—each click takes about 10 seconds to respond.

Below is my current docker-compose file. Note that the dawarich_sidekiq service is missing in this version, but including or excluding it didn’t make any noticeable difference in response speed.

Any ideas?

```
version: '3.8'

services:
  dawarich_redis:
    image: redis:7.0-alpine
    container_name: dawarich_redis
    command: redis-server
    restart: unless-stopped
    networks:
      - dawarich
    volumes:
      - ./redis:/var/shared/redis
    mem_limit: 1g
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

  dawarich_db:
    image: postgis/postgis:17-3.5-alpine
    container_name: dawarich_db
    restart: unless-stopped
    networks:
      - dawarich
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./db_shared:/var/shared
    mem_limit: 4g
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

  dawarich_app:
    image: freikin/dawarich:0.26.1
    container_name: dawarich_app
    depends_on:
      - dawarich_db
      - dawarich_redis
    stdin_open: true
    tty: true
    entrypoint: web-entrypoint.sh
    command: ['bin/dev']
    restart: unless-stopped
    networks:
      - dawarich
    env_file:
      - .env
    volumes:
      - ./public:/var/app/public
      - ./watched:/var/app/tmp/imports/watched
      - ./app_storage:/var/app/storage
    ports:
      - 32568:3000
    mem_limit: 4g
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

networks:
  dawarich:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.48.0/20
```

**Reply by Freika** [reply]
Update to the latest version, starting 0.27.0 performance in the browser was significantly improved

**Comment by dror3go** [comment]
Today I gave Dawarich a go - a fresh install of the latest tag 0.29.1 using Docker without changing the yml file provided in the docs.
The performance is horrible - 120 seconds per endpoint.
I *must* be missing something, but I expected the basic intro to give me an idea of what's going on.

Any pointers?

**Comment by trmendes** [comment]
Same here. I updated the version but it is still very slow!

**Comment by trmendes** [comment]
Hi @Freika 

I'm on the latest version and it is still very slow. Each click takes a very long time. I'm sharing my latest docker-compose.yaml

```
version: '3.8'

services:
  dawarich_redis:
    image: redis:7.4-alpine
    container_name: dawarich_redis
    command: redis-server
    restart: unless-stopped
    networks:
      - dawarich
    volumes:
      - ./redis:/var/shared/redis
    mem_limit: 1g
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  dawarich_db:
    image: postgis/postgis:17-3.5-alpine
    container_name: dawarich_db
    restart: unless-stopped
    networks:
      - dawarich
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./db_shared:/var/shared
    mem_limit: 1g
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d dawarich_development" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    stdin_open: true
    tty: true
    entrypoint: web-entrypoint.sh
    command: ['bin/rails', 'server', '-p', '3000', '-b', '::']
    restart: unless-stopped
    networks:
      - dawarich
      - photon_photonnet
    env_file:
      - .env
    environment:
      RAILS_ENV: ${RAILS_ENV}
      REDIS_URL: ${REDIS_URL}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      MIN_MINUTES_SPENT_IN_CITY: ${MIN_MINUTES_SPENT_IN_CITY}
      APPLICATION_HOSTS: ${APPLICATION_HOSTS}
      TIME_ZONE: ${TIME_ZONE}
      APPLICATION_PROTOCOL: ${APPLICATION_PROTOCOL}
      RAILS_LOG_TO_STDOUT: ${RAILS_LOG_TO_STDOUT}
      STORE_GEODATA: ${STORE_GEODATA}
      PHOTON_API_HOST: photon:2322
    volumes:
      - ./public:/var/app/public
      - ./watched:/var/app/tmp/imports/watched
      - ./app_storage:/var/app/storage
    ports:
      - 32568:3000
    mem_limit: 4g
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO - http://127.0.0.1:3000/api/v1/health | grep -q '\"status\"\\s*:\\s*\"ok\"'" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
      dawarich_redis:
        condition: service_healthy
        restart: true

  dawarich_sidekiq:
    image: freikin/dawarich:latest
    container_name: dawarich_sidekiq
    stdin_open: true
    tty: true
    entrypoint: sidekiq-entrypoint.sh
    command: ['sidekiq']
    restart: unless-stopped
    networks:
      - dawarich
      - photon_photonnet
    env_file:
      - .env
    environment:
      RAILS_ENV: ${RAILS_ENV}
      REDIS_URL: ${REDIS_URL}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      MIN_MINUTES_SPENT_IN_CITY: ${MIN_MINUTES_SPENT_IN_CITY}
      APPLICATION_HOSTS: ${APPLICATION_HOSTS}
      TIME_ZONE: ${TIME_ZONE}
      APPLICATION_PROTOCOL: ${APPLICATION_PROTOCOL}
      RAILS_LOG_TO_STDOUT: ${RAILS_LOG_TO_STDOUT}
      STORE_GEODATA: ${STORE_GEODATA}
      PHOTON_API_HOST: photon:2322
    volumes:
      - ./public:/var/app/public
      - ./watched:/var/app/tmp/imports/watched
      - ./app_storage:/var/app/storage
    mem_limit: 4g
    healthcheck:
      test: [ "CMD-SHELL", "pgrep -f sidekiq" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
      dawarich_redis:
        condition: service_healthy
        restart: true
      dawarich_app:
        condition: service_healthy
        restart: true

networks:
  photon_photonnet:
    external: true
  dawarich:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.10.0/29
```
