### DISCUSSION TITLE
Updating from 0.26.6 to 0.27.2

### DISCUSSION THREAD

**Discussion by Hoempi** [Freika/dawarich#1316] [Q&A] [answered]
Hey everyone,

like mentionend in the title, I'm currently running a fairly old version and would like to tackle the update, before more stuff gets changed.

Regarding the cahnges in the Docker compose file, would you suggest pulling the latest image, waiting for everything to migrate, check for everything running well and then shutting the containers down and afterwards deleting the stuff from the compose? Anything else I would need to do manually?

My current compose looks like this:

```
networks:
  dawarich: null
services:
  dawarich_redis:
    image: redis:7.0-alpine
    container_name: dok008-dawarich_redis
    command: redis-server
    networks:
      - dawarich
    volumes:
      - dawarich_shared:/data
    restart: always
    healthcheck:
      test:
        - CMD
        - redis-cli
        - --raw
        - incr
        - ping
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  dawarich_db:
    image: postgis/postgis:17-3.5-alpine
    shm_size: 1G
    container_name: dok008-dawarich_db
    volumes:
      - ${DOCKER_GLOBAL_DBROOT}/dawarich:/var/lib/postgresql/data
      - dawarich_shared:/var/shared
      - dawarich_storage:/var/app/storage
    networks:
      - dawarich
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: always
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres -d dawarich_development
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dok008-dawarich_app
    volumes:
      - dawarich_public:/var/app/public
      - dawarich_watched:/var/app/tmp/imports/watched
    networks:
      - dawarich
    ports:
      - 10808:3000
      # - 9394:9394 # Prometheus exporter, uncomment if needed
    stdin_open: true
    tty: true
    entrypoint: web-entrypoint.sh
    command:
      - bin/rails
      - server
      - -p
      - "3000"
      - -b
      - "::"
    restart: on-failure
    env_file:
      - .env
    labels:
      - com.centurylinklabs.watchtower.monitor-only=true
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: "5"
    healthcheck:
      test:
        - CMD-SHELL
        - wget -qO - http://127.0.0.1:3000/api/v1/health | grep -q
          '"status"\s*:\s*"ok"'
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
      dawarich_redis:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: "0.50" # Limit CPU usage to 50% of one core
          memory: 4G # Limit memory usage to 4GB
  dawarich_sidekiq:
    image: freikin/dawarich:latest
    container_name: dok008-dawarich_sidekiq
    volumes:
      - dawarich_public:/var/app/public
      - dawarich_watched:/var/app/tmp/imports/watched
      - dawarich_storage:/var/app/storage
    networks:
      - dawarich
    stdin_open: true
    tty: true
    entrypoint: sidekiq-entrypoint.sh
    command:
      - sidekiq
    restart: on-failure
    env_file:
      - .env
    labels:
      - com.centurylinklabs.watchtower.monitor-only=true
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: "5"
    healthcheck:
      test:
        - CMD-SHELL
        - bundle exec sidekiqmon processes | grep $${HOSTNAME}
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
      dawarich_redis:
        condition: service_healthy
        restart: true
      dawarich_app:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: "0.50" # Limit CPU usage to 50% of one core
          memory: 4G # Limit memory usage to 4GB
volumes:
  dawarich_db_data:
    driver: local
    driver_opts:
      type: none
      device: ${DOCKER_GLOBAL_DBROOT}/dawarich
      o: bind
  dawarich_storage:
    driver: local
    driver_opts:
      type: none
      device: ${DOCKER_GLOBAL_DATAROOT}/dawarich/storage
      o: bind
  dawarich_shared:
    driver: local
    driver_opts:
      type: none
      device: ${DOCKER_GLOBAL_DATAROOT}/dawarich/shared
      o: bind
  dawarich_public:
    driver: local
    driver_opts:
      type: none
      device: ${DOCKER_GLOBAL_DATAROOT}/dawarich/public
      o: bind
  dawarich_watched:
    driver: local
    driver_opts:
      type: none
      device: ${DOCKER_GLOBAL_DATAROOT}/dawarich/watched
      o: bind
  photon_data:
    driver: local
    driver_opts:
      type: none
      device: ${DOCKER_GLOBAL_DATAROOT}/dawarich/photon/photon_data
      o: bind
```

.env-file:
```
# Common
DOCKER_GLOBAL_DATAROOT=/mnt/docker-data
DOCKER_GLOBAL_DBROOT=/var/db-data

# Postgres
POSTGRES_USER=postgres
POSTGRES_PASSWORD=myverysecurepasswordisofcourseanotherone
POSTGRES_DB=dawarich_development

# Dawarich Common
RAILS_ENV=development
REDIS_URL=redis://dawarich_redis:6379/0
DATABASE_HOST=dawarich_db
DATABASE_PORT=5432
DATABASE_USERNAME=postgres
DATABASE_PASSWORD=myverysecurepasswordisofcourseanotherone
DATABASE_NAME=dawarich_development
APPLICATION_HOSTS=localhost,::1,127.0.0.1,dawarich.mydomain.com,172.16.0.5
APPLICATION_PROTOCOL=http
DISTANCE_UNIT=km
RAILS_LOG_TO_STDOUT=true
PROMETHEUS_EXPORTER_ENABLED=false
PROMETHEUS_EXPORTER_HOST=dawarich_app
PROMETHEUS_EXPORTER_PORT=9394
ENABLE_TELEMETRY=false # More on telemetry=https://dawarich.app/docs/tutorials/telemetry
SECRET_KEY_BASE=wonttellyouthis
PHOTON_API_HOST=172.16.0.5:10908
PHOTON_API_USE_HTTPS=false
SELF_HOSTED=true

# App
MIN_MINUTES_SPENT_IN_CITY=60
TIME_ZONE=Europe/Berlin

# Sidekiq
BACKGROUND_PROCESSING_CONCURRENCY=10

# Photon
UPDATE_STRATEGY=PARALLEL
UPDATE_INTERVAL=24h
LOG_LEVEL=INFO
FORCE_UPDATE=false # Optional: force index update on startup
#COUNTRY_CODE=zw  # Optional: country-specific index
```
