### DISCUSSION TITLE
Serving IPv6 is not working

### DISCUSSION THREAD

**Discussion by keestux** [Freika/dawarich#1341] [Ideas]
**OS & Hardware**
Ubuntu 24.04
docker.io 26.1.3
docker-compose-v2 2.27.1

**Version**
`latest` docker images as of today (May 25, 2025)

**Describe the bug**
Connecting the app through a hostname that only has an IPv6 address I'm getting:
```txt
Blocked hosts: dawarich.example.com:3000
To allow requests to these hosts, make sure they are valid hostnames (containing only numbers, letters, dashes and dots), then add the following to your environment configuration:

    config.hosts << "dawarich.example.com:3000"
  

For more details view: the Host Authorization guide
```

**To Reproduce**
Using `docker-compose.yml` from the Git repo, with two modifications, enable IPv6 and expose port 3000 on IPv6. Here is a brief snippet from the config.
```yaml
networks:
  dawarich:
    enable_ipv6: true
services:
  dawarich_app:
    ports:
      - "[::]:3000:3000"
```

**Expected behavior**
Normal functioning app through IPv6.
