### DISCUSSION TITLE
0.27.4

### DISCUSSION THREAD

**Discussion by Freika** [Freika/dawarich#1363] [Announcements]
⚠️ This release includes a breaking change. ⚠️

## Changed

- SolidQueue is now using PostgreSQL instead of SQLite. Provide `QUEUE_DATABASE_NAME`, `QUEUE_DATABASE_PASSWORD`, `QUEUE_DATABASE_USERNAME`, `QUEUE_DATABASE_PORT` and `QUEUE_DATABASE_HOST` environment variables to configure it. #1331
- SQLite databases are now being stored in the `dawarich_sqlite_data` volume. #1361 #1357

```diff
...
  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    volumes:
      - dawarich_public:/var/app/public
      - dawarich_watched:/var/app/tmp/imports/watched
      - dawarich_storage:/var/app/storage
      - dawarich_db_data:/dawarich_db_data
+     - dawarich_sqlite_data:/dawarich_sqlite_data
    ...
    restart: on-failure
    environment:
    ...
      DATABASE_NAME: dawarich_development
+     # PostgreSQL database name for solid_queue
+     QUEUE_DATABASE_NAME: dawarich_development_queue
+     QUEUE_DATABASE_PASSWORD: password
+     QUEUE_DATABASE_USERNAME: postgres
+     QUEUE_DATABASE_PORT: 5432
+     QUEUE_DATABASE_HOST: dawarich_db
      # SQLite database paths for cache and cable databases
-     QUEUE_DATABASE_PATH: /dawarich_db_data/dawarich_development_queue.sqlite3
-     CACHE_DATABASE_PATH: /dawarich_db_data/dawarich_development_cache.sqlite3
-     CABLE_DATABASE_PATH: /dawarich_db_data/dawarich_development_cable.sqlite3
+     CACHE_DATABASE_PATH: /dawarich_sqlite_data/dawarich_development_cache.sqlite3
+     CABLE_DATABASE_PATH: /dawarich_sqlite_data/dawarich_development_cable.sqlite3

volumes:
  dawarich_db_data:
+ dawarich_sqlite_data:
  dawarich_shared:
  dawarich_public:
  dawarich_watched:
  dawarich_storage:
...
```

💙 This release is supported by Steven B., James Manolios, chenrik, aldumil, derpderpington, Chippie, dint, jhalpern, Lex Fradski, Schlufo, cyberswan.at, craftyklaus, JMyrng, Andre, hogenf, naraxius, Lemur, Embrace, martin4861, Alex, evetters, GregF, Jon Coffee, Lukas, Robbie G, Kilian, Hans G, Chris, tabaha, Andre, Michael C, Chris, elyob, gesus, Jonah B., Dante, daallex, Tanner A., Matthias B., Milien M., Mathias, Travis S., Stefan, Michael J., Matthew F., Johnathan D., bleibdirtroy, no1etal, Alexander K.,Ashwin C., and BeeHappy on [Patreon](https://www.patreon.com/freika) and [KoFi](https://ko-fi.com/freika) 💙

## What's Changed
* 0.27.4 by @Freika in https://github.com/Freika/dawarich/pull/1362

**Full Changelog**: https://github.com/Freika/dawarich/compare/0.27.3...0.24.7

<hr /><em>This discussion was created from the release <a href='https://github.com/Freika/dawarich/releases/tag/0.27.4'>0.27.4</a>.</em>

**Comment by bytegetter** [comment]
I´ve updated to this version, but it did not work. 

```
networks:
  dawarich:
services:
  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    volumes:
      - dawarich_public:/var/app/public
      - dawarich_watched:/var/app/tmp/imports/watched
      - dawarich_storage:/var/app/storage
      - dawarich_db_data:/dawarich_db_data
      - dawarich_sqlite_data:/dawarich_sqlite_data
    networks:
      - dawarich
    ports:
      - 3000:3000
      # - 9394:9394 # Prometheus exporter, uncomment if needed
    stdin_open: true
    tty: true
    entrypoint: web-entrypoint.sh
    command: ['bin/rails', 'server', '-p', '3000', '-b', '::']
    restart: on-failure
    environment:
      RAILS_ENV: development
      DATABASE_HOST: dawarich_db_pg_17
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      # PostgreSQL database name for solid_queue
      QUEUE_DATABASE_NAME: dawarich_development_queue
      QUEUE_DATABASE_PASSWORD: password
      QUEUE_DATABASE_USERNAME: postgres
      QUEUE_DATABASE_PORT: 5432
      QUEUE_DATABASE_HOST: dawarich_db
      #QUEUE_DATABASE_PATH: /dawarich_db_data/dawarich_development_queue.sqlite3
      #CACHE_DATABASE_PATH: /dawarich_db_data/dawarich_development_cache.sqlite3
      #CABLE_DATABASE_PATH: /dawarich_db_data/dawarich_development_cable.sqlite3
      CACHE_DATABASE_PATH: /dawarich_sqlite_data/dawarich_development_cache.sqlite3
      CABLE_DATABASE_PATH: /dawarich_sqlite_data/dawarich_development_cable.sqlite3
      MIN_MINUTES_SPENT_IN_CITY: 60
      APPLICATION_HOSTS: "dawarich.xxxxx.de,127.0.0.1"
      TIME_ZONE: Europe/Berlin
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: 0.0.0.0
      PROMETHEUS_EXPORTER_PORT: 9394
      SELF_HOSTED: "true"
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO - http://127.0.0.1:3000/api/v1/health | grep -q '\"status\"\\s*:\\s*\"ok\"'" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db_pg_17:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '0.50'    # Limit CPU usage to 50% of one core
          memory: '4G'    # Limit memory usage to 4GB




  dawarich_db_pg_17:
    image: postgis/postgis:17-3.5-alpine
    shm_size: 1G
    container_name: dawarich_db_pg_17
    volumes:
      - dawarich_db_data_pg_17:/var/lib/postgresql/data
      - dawarich_shared:/var/shared
    networks:
      - dawarich
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d dawarich_development" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    
volumes:
  dawarich_db_data:
  dawarich_sqlite_data:
  dawarich_shared:
  dawarich_public:
  dawarich_watched:
  dawarich_storage:
  dawarich_db_data_pg_17:
```


>  root@dawarich-2:~/dawarich# docker compose logs
WARN[0000] The "RAILS_MASTER_KEY" variable is not set. Defaulting to a blank string. 
dawarich_db_pg_17  | 
dawarich_db_pg_17  | PostgreSQL Database directory appears to contain a database; Skipping initialization
dawarich_db_pg_17  | 
dawarich_db_pg_17  | 2025-06-08 13:12:37.622 UTC [1] LOG:  starting PostgreSQL 17.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
dawarich_db_pg_17  | 2025-06-08 13:12:37.622 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
dawarich_db_pg_17  | 2025-06-08 13:12:37.623 UTC [1] LOG:  listening on IPv6 address "::", port 5432
dawarich_db_pg_17  | 2025-06-08 13:12:37.913 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
dawarich_db_pg_17  | 2025-06-08 13:12:38.215 UTC [29] LOG:  database system was shut down at 2025-06-08 13:11:35 UTC
dawarich_db_pg_17  | 2025-06-08 13:12:38.595 UTC [1] LOG:  database system is ready to accept connections
dawarich_db_pg_17  | 2025-06-08 13:12:44.412 UTC [40] ERROR:  database "dawarich_development" already exists
dawarich_db_pg_17  | 2025-06-08 13:12:44.412 UTC [40] STATEMENT:  CREATE DATABASE dawarich_development;
dawarich_db_pg_17  | 2025-06-08 13:17:38.314 UTC [27] LOG:  checkpoint starting: time
dawarich_db_pg_17  | 2025-06-08 13:17:39.174 UTC [27] LOG:  checkpoint complete: wrote 2 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.235 s, sync=0.044 s, total=0.860 s; sync files=3, longest=0.044 s, average=0.015 s; distance=0 kB, estimate=0 kB; lsn=0/EF46958, redo lsn=0/EF46900
dawarich_app       | ⚠️ Starting Rails environment: development ⚠
dawarich_app       | Created SQLite database directory at /dawarich_sqlite_data
dawarich_app       | Setting up all required databases...
dawarich_app       | Attempting to create database dawarich_development if it doesn't exist...
dawarich_app       | Note: Database dawarich_development may already exist or couldn't be created now
dawarich_app       | ⏳ Waiting for database dawarich_development to be ready...
dawarich_app       | ✅ PostgreSQL database dawarich_development is ready!
dawarich_app       | Attempting to create database dawarich_development_queue if it doesn't exist...
dawarich_app       | Note: Database dawarich_development_queue may already exist or couldn't be created now
dawarich_app       | ⏳ Waiting for database dawarich_development_queue to be ready...
dawarich_app       | Postgres database dawarich_development_queue is unavailable - retrying...
dawarich_app       | Postgres database dawarich_development_queue is unavailable - retrying...
dawarich_app       | Postgres database dawarich_development_queue is unavailable - retrying...
dawarich_app       | Postgres database dawarich_development_queue is unavailable - retrying...
dawarich_app       | Postgres database dawarich_development_queue is unavailable - retrying...
dawarich_app       | Postgres database dawarich_development_queue is unavailable - retrying...
dawarich_app       | Postgres database dawarich_development_queue is unavailable - retrying...

Any hint?
