### DISCUSSION TITLE
0.28.0

### DISCUSSION THREAD

**Discussion by Freika** [Freika/dawarich#1390] [Announcements]
⚠️ This release includes a breaking change. ⚠️

_yet another, yay!_

Well, we're moving back to Sidekiq and Redis for background jobs and caching. Unfortunately, SolidQueue and SolidCache brought more problems than they solved. Please update your `docker-compose.yml` to use Redis and Sidekiq.

Before updating, you can remove `dawarich_development_queue` database from your postgres. All *.sqlite3 files in `dawarich_sqlite_data` volume can be removed as well.

```diff
networks:
  dawarich:
services:
+ dawarich_redis:
+   image: redis:7.4-alpine
+   container_name: dawarich_redis
+   command: redis-server
+   networks:
+     - dawarich
+   volumes:
+     - dawarich_shared:/data
+   restart: always
+   healthcheck:
+     test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
+     interval: 10s
+     retries: 5
+     start_period: 30s
+     timeout: 10s
...
  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    volumes:
      - dawarich_public:/var/app/public
      - dawarich_watched:/var/app/tmp/imports/watched
      - dawarich_storage:/var/app/storage
      - dawarich_db_data:/dawarich_db_data
-     - dawarich_sqlite_data:/dawarich_sqlite_data
    ...
    restart: on-failure
    environment:
      RAILS_ENV: development
+     REDIS_URL: redis://dawarich_redis:6379
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
-     # PostgreSQL database name for solid_queue
-     QUEUE_DATABASE_NAME: dawarich_development_queue
-     QUEUE_DATABASE_PASSWORD: password
-     QUEUE_DATABASE_USERNAME: postgres
-     QUEUE_DATABASE_HOST: dawarich_db
-     QUEUE_DATABASE_PORT: 5432
-     # SQLite database paths for cache and cable databases
-     CACHE_DATABASE_PATH: /dawarich_sqlite_data/dawarich_development_cache.sqlite3
-     CABLE_DATABASE_PATH: /dawarich_sqlite_data/dawarich_development_cable.sqlite3
...
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
+     dawarich_redis:
+       condition: service_healthy
+       restart: true
...
+ dawarich_sidekiq:
+   image: freikin/dawarich:latest
+   container_name: dawarich_sidekiq
+   volumes:
+     - dawarich_public:/var/app/public
+     - dawarich_watched:/var/app/tmp/imports/watched
+     - dawarich_storage:/var/app/storage
+   networks:
+     - dawarich
+   stdin_open: true
+   tty: true
+   entrypoint: sidekiq-entrypoint.sh
+   command: ['sidekiq']
+   restart: on-failure
+   environment:
+     RAILS_ENV: development
+     REDIS_URL: redis://dawarich_redis:6379
+     DATABASE_HOST: dawarich_db
+     DATABASE_USERNAME: postgres
+     DATABASE_PASSWORD: password
+     DATABASE_NAME: dawarich_development
+     APPLICATION_HOSTS: localhost
+     BACKGROUND_PROCESSING_CONCURRENCY: 10
+     APPLICATION_PROTOCOL: http
+     PROMETHEUS_EXPORTER_ENABLED: false
+     PROMETHEUS_EXPORTER_HOST: dawarich_app
+     PROMETHEUS_EXPORTER_PORT: 9394
+     SELF_HOSTED: "true"
+     STORE_GEODATA: "true"
+   logging:
+     driver: "json-file"
+     options:
+       max-size: "100m"
+       max-file: "5"
+   healthcheck:
+     test: [ "CMD-SHELL", "pgrep -f sidekiq" ]
+     interval: 10s
+     retries: 30
+     start_period: 30s
+     timeout: 10s
+   depends_on:
+     dawarich_db:
+       condition: service_healthy
+       restart: true
+     dawarich_redis:
+       condition: service_healthy
+       restart: true
+     dawarich_app:
+       condition: service_healthy
+       restart: true
...
volumes:
  dawarich_db_data:
- dawarich_sqlite_data:
  dawarich_shared:
  dawarich_public:
  dawarich_watched:
  dawarich_storage:
```

_I understand the confusion, probably even anger, caused by so many breaking changes in the recent days._

_I'm sorry._

## Fixed

- Fixed a bug where points from Immich and Photoprism did not have lonlat attribute set. #1318
- Added minimum password length to 6 characters. #1373
- Text size of countries being calculated is now smaller. #1371

## Changed

- Geocoder is now being installed from a private fork for debugging purposes.
- Redis is now being used for caching.
- Sidekiq is now being used for background jobs.

## Removed
- SolidQueue, SolidCache and SolidCable are now removed.

💙 This release is supported by Steven B., James Manolios, chenrik, aldumil, derpderpington, Chippie, dint, jhalpern, Lex Fradski, Schlufo, cyberswan.at, craftyklaus, JMyrng, Andre, hogenf, naraxius, Lemur, Embrace, martin4861, Alex, evetters, GregF, Jon Coffee, Lukas, Robbie G, Kilian, Hans G, Chris, tabaha, Andre, Michael C, Chris, elyob, gesus, Jonah B., Dante, daallex, Tanner A., Matthias B., Milien M., Mathias, Travis S., Stefan, Michael J., Matthew F., Johnathan D., bleibdirtroy, no1etal, Alexander K.,Ashwin C., Stefan, dixet, Bailey J. and BeeHappy on [Patreon](https://www.patreon.com/freika) and [KoFi](https://ko-fi.com/freika) 💙

## What's Changed
* fix map container height to fit viewport by @rtuszik in https://github.com/Freika/dawarich/pull/1350
* Revert "fix map container height to fit viewport" by @Freika in https://github.com/Freika/dawarich/pull/1380
* Fix ISO3166-Alpha2 for Taiwan by @Sea-n in https://github.com/Freika/dawarich/pull/1300
* Fixed a bug where hovering over a route when another route is clicked… by @Freika in https://github.com/Freika/dawarich/pull/1374
* Bump turbo-rails from 2.0.13 to 2.0.16 by @dependabot in https://github.com/Freika/dawarich/pull/1386
* Bump gpx from 1.2.0 to 1.2.1 by @dependabot in https://github.com/Freika/dawarich/pull/1387
* Bump groupdate from 6.6.0 to 6.7.0 by @dependabot in https://github.com/Freika/dawarich/pull/1388
* Revert/sidekiq and redis by @Freika in https://github.com/Freika/dawarich/pull/1384
* 0.28.0 by @Freika in https://github.com/Freika/dawarich/pull/1389

## New Contributors
* @rtuszik made their first contribution in https://github.com/Freika/dawarich/pull/1350
* @Sea-n made their first contribution in https://github.com/Freika/dawarich/pull/1300

**Full Changelog**: https://github.com/Freika/dawarich/compare/0.27.4...0.28.0

<hr /><em>This discussion was created from the release <a href='https://github.com/Freika/dawarich/releases/tag/0.28.0'>0.28.0</a>.</em>

**Comment by dc911x** [comment]
FYI (I'm not mad), it's been a bit confusing that's for sure. But we're still in "development" and not "stable".
Updates are coming out fast and kinda stable (minus the SolidQueue and SolidCache woops!)
But as unraid user I hope @nwithan8 updates the template because I've been editing manually and lost track on what I've removed and what I've added lol, but that's just the unraid CA limitations, once you've installed them the repo updates come through but not the compose stuff.

**Reply by Freika** [reply]
> FYI (I'm not mad), it's been a bit confusing that's for sure. But we're still in "development" and not "stable".
> 
> Updates are coming out fast and kinda stable (minus the SolidQueue and SolidCache woops!)
> 
> But as unraid user I hope @nwithan8 updates the template because I've been editing manually and lost track on what I've removed and what I've added lol, but that's just the unraid CA limitations, once you've installed them the repo updates come through but not the compose stuff. 

I actually opened a pr with 0.28.0 changes to @nwithan8 repo so as soon as it's merged, you're good. I'd take it over, but I can't even test it as I don't have unraid license nor time to do it

**Reply by nwithan8** [reply]
Is this just a complete reversion to pre-0.27.0, or are there new env cars or paths here? If it's just a revert, I can simply un-deprecate to Sidekiq template and revert the main template.

**Reply by nwithan8** [reply]
@Freika awaiting your feedback on your PR

**Reply by Freika** [reply]
replied

**Comment by gpietrog** [comment]
Can we skip the 0.27.4 version?

**Comment by Billos** [comment]
Hello, I'm currently trying to fix my REDIS configuration.
From what I can see, you can't set the db index in the REDIS_URL anymore.
Which is a problem when you are using one common Redis server and DB indexes 1 or 0 might already be taken by other services.

Are you planning on adding a new env var to support this ?

**Comment by Millio345** [comment]
Getting a little bit confusing to be honest but oh well, this happens with software in active development, thanks for the hard work. Glad I was a bit too lazy to remove my redis & sidekiq volumes :-)

So is the "dawarich_db_data" volume which was added in 0.27.0 still being used?

**Reply by Freika** [reply]
dawarich_db_data volume is still being used to persist your postgres database, so yes

**Comment by tedstriker** [comment]
How should a migration from 0.26.7 to 0.28.0 take place?
Swapping version numbers for the containers won't do the trick, as the server throws errors with the following stack trace:
```
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in 'Kernel#require'
server-1  | Tasks: TOP => db:migrate => db:load_config => environment
server-1  | (See full trace by running task with --trace)
server-1  | ⚠️ Starting Rails environment: development ⚠️
server-1  | Setting up all required databases...
server-1  | Attempting to create database dawarich if it doesn't exist...
server-1  | Note: Database dawarich may already exist or couldn't be created now
server-1  | ⏳ Waiting for database dawarich to be ready...
server-1  | ✅ PostgreSQL database dawarich is ready!
server-1  | Running migrations for all databases...
server-1  | Running primary database migrations...
server-1  | [dotenv] Loaded .env.development
server-1  | bin/rails aborted!
server-1  | ArgumentError: invalid value for Integer(): "0/0" (ArgumentError)
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/redis-client-0.24.0/lib/redis_client/url_config.rb:33:in 'RedisClient::URLConfig#db'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/redis-client-0.24.0/lib/redis_client/config.rb:200:in 'RedisClient::Config#initialize'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/redis-client-0.24.0/lib/redis_client.rb:174:in 'Class#new'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/redis-client-0.24.0/lib/redis_client.rb:174:in 'RedisClient.config'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/redis-5.4.0/lib/redis/client.rb:23:in 'Redis::Client.config'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/redis-5.4.0/lib/redis.rb:142:in 'Redis#initialize_client'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/redis-5.4.0/lib/redis.rb:73:in 'Redis#initialize'
server-1  | /var/app/config/initializers/geocoder.rb:7:in 'Class#new'
server-1  | /var/app/config/initializers/geocoder.rb:7:in '
'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/engine.rb:693:in 'Kernel#load'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/engine.rb:693:in 'block in Rails::Engine#load_config_initializer'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/activesupport-8.0.2/lib/active_support/notifications.rb:212:in 'ActiveSupport::Notifications.instrument'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/engine.rb:692:in 'Rails::Engine#load_config_initializer'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/engine.rb:646:in 'block (2 levels) in '
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/engine.rb:645:in 'Array#each'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/engine.rb:645:in 'block in '
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/initializable.rb:32:in 'BasicObject#instance_exec'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/initializable.rb:32:in 'Rails::Initializable::Initializer#run'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/initializable.rb:61:in 'block in Rails::Initializable#run_initializers'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/initializable.rb:50:in 'Array#each'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/initializable.rb:50:in 'Rails::Initializable::Collection#tsort_each_child'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/initializable.rb:60:in 'Rails::Initializable#run_initializers'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/application.rb:440:in 'Rails::Application#initialize!'
server-1  | /var/app/config/environment.rb:7:in '
'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in 'Kernel#require'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/zeitwerk-2.7.3/lib/zeitwerk/core_ext/kernel.rb:34:in 'Kernel#require'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/application.rb:416:in 'Rails::Application#require_environment!'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/application.rb:567:in 'block in Rails::Application#run_tasks_blocks'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:281:in 'block in Rake::Task#execute'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:281:in 'Array#each'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:281:in 'Rake::Task#execute'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:219:in 'block in Rake::Task#invoke_with_call_chain'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:199:in 'Monitor#synchronize'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:199:in 'Rake::Task#invoke_with_call_chain'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:243:in 'block in Rake::Task#invoke_prerequisites'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:241:in 'Array#each'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:241:in 'Rake::Task#invoke_prerequisites'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:218:in 'block in Rake::Task#invoke_with_call_chain'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:199:in 'Monitor#synchronize'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:199:in 'Rake::Task#invoke_with_call_chain'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:243:in 'block in Rake::Task#invoke_prerequisites'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:241:in 'Array#each'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:241:in 'Rake::Task#invoke_prerequisites'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:218:in 'block in Rake::Task#invoke_with_call_chain'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:199:in 'Monitor#synchronize'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:199:in 'Rake::Task#invoke_with_call_chain'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:188:in 'Rake::Task#invoke'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/application.rb:188:in 'Rake::Application#invoke_task'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/application.rb:138:in 'block (2 levels) in Rake::Application#top_level'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/application.rb:138:in 'Array#each'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/application.rb:138:in 'block in Rake::Application#top_level'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/application.rb:147:in 'Rake::Application#run_with_threads'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/application.rb:132:in 'Rake::Application#top_level'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/commands/rake/rake_command.rb:27:in 'block (2 levels) in Rails::Command::RakeCommand.perform'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/application.rb:214:in 'Rake::Application#standard_exception_handling'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/commands/rake/rake_command.rb:27:in 'block in Rails::Command::RakeCommand.perform'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/commands/rake/rake_command.rb:44:in 'block in Rails::Command::RakeCommand.with_rake'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/rake_module.rb:59:in 'Rake.with_application'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/commands/rake/rake_command.rb:41:in 'Rails::Command::RakeCommand.with_rake'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/commands/rake/rake_command.rb:20:in 'Rails::Command::RakeCommand.perform'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/command.rb:150:in 'Rails::Command.invoke_rake'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/command.rb:67:in 'block in Rails::Command.invoke'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/command.rb:143:in 'Rails::Command.with_argv'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/command.rb:63:in 'Rails::Command.invoke'
server-1  | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/commands.rb:18:in '
'
```

**Reply by Billos** [reply]
Try removing the "/0" at the end of your REDIS_URL

**Reply by tedstriker** [reply]
That resolved it. Thank you!

**Reply by wburgers** [reply]
Any other steps needed?

**Comment by clartek** [comment]
Is there any easier way to update my docker compose than copying and pasting and manually removing the +'s? I'm using Portainer.

**Reply by nwithan8** [reply]
You can reference the full Docker Compose here: https://github.com/Freika/dawarich/blob/master/docker/docker-compose.yml

**Reply by clartek** [reply]
Thanks, copy and pasted the full compose (adding my custom domain and timezone), redeployed, and all is well.

**Comment by mstuslar** [comment]
I haven't used Dawarich before and just downloaded the docker_compose.yml file from this release to try a new installation. Running on a Pi4 I needed to replace image: postgis with imresamu for the darwarich_db image. all the rest I left unchanged.

However the darwarich_app seems to hand in the loop (see below) all the other containers seem to start just fine. Since this is not an upgrade from a older version I didn't expect any issues here, and the only other thing  I noticed is this message about memory limit.
⠏ Container dawarich_app                                                                                                  Waiting 231.2s 
 ! dawarich_app Your kernel does not support memory limit capabilities or the cgroup is not mounted. Limitation discarded.         

Docker is also freshly installed and the only other app running is Portainer.

⚠️ Starting Rails environment: development ⚠️
Setting up all required databases...
Attempting to create database dawarich_development if it doesn't exist...
Note: Database dawarich_development may already exist or couldn't be created now
⏳ Waiting for database dawarich_development to be ready...
Postgres database dawarich_development is unavailable - retrying...
Postgres database dawarich_development is unavailable - retrying...
Postgres database dawarich_development is unavailable - retrying...
Postgres database dawarich_development is unavailable - retrying...
Postgres database dawarich_development is unavailable - retrying...
Postgres database dawarich_development is unavailable - retrying...
Postgres database dawarich_development is unavailable - retrying...
Postgres database dawarich_development is unavailable - retrying...
Postgres database dawarich_development is unavailable - retrying...
Postgres database dawarich_development is unavailable - retrying...
Postgres database dawarich_development is unavailable - retrying...


Any suggestion how this can be fixed, or how log it's expected to take for a new installation?

I added the output of inspect as a file
[inspect.txt](https://github.com/user-attachments/files/20678559/inspect.txt)

**Reply by mstuslar** [reply]
I guess I stumbled across the solution: 

It looks like the postgres user didn't have the password set to "password" (don't know why, as I did not change anything to that regard in the compose file)

Getting into the dawwarich_db container, starting psql and than using the following command to set the password to "password" like it's set in the compose file, did the trick for me:

`ALTER USER postgres WITH PASSWORD 'password';`

**Comment by kronn** [comment]
Not mad. Only mad respect for the courage to admit wrong decisions and provide proper instruction how to move forward. This is not easy and you do a great job here.

**Reply by Freika** [reply]
Thank you!

**Comment by Bestivus** [comment]
Just chiming in with support, this is one of those self hosted apps that provides so much value.  I was many versions behind, but just this morning went one by one upgrading to the next specific version.  Finally got to 0.28.0 and so far no issues.

Appreciate all the work!

**Comment by c0delama** [comment]
Am i correct that i can update from 0.27.1 to 0.28.1 without any changes to my `docker-compose.yaml` or am i missing something?

**Reply by Freika** [reply]
No, you need to update your compose file. Check release notes

**Comment by chriscom2020** [comment]
I updated from version 0.27.4 directly to 0.28.1 - the update went smoothly. However, the map is no longer displayed under "Trips."
It probably wasn’t working in version 0.27.4 either, but I didn’t notice it. Do you have any advice on how to fix this? Thank you!

**Reply by Freika** [reply]
Check logs and open a new issue please, provide all necessary details

**Comment by iAmRenzo** [comment]
I am (still) on 26.5, so not sure what the best strategy is for me. I missed the previous braking change. I did some modification, I believe, for Synology Container Manager Projects. I recall that Synology doesn't support all things. But now I am not sure how to proceed.

This is my working config:
```
networks:
  dawarich:
services:
  dawarich_redis:
    image: redis:7.0-alpine
    container_name: dawarich_redis
    command: redis-server
    networks:
      - dawarich
    volumes:
      - dawarich_shared:/data
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  dawarich_db:
    image: postgis/postgis:17-3.5-alpine
    shm_size: 1G
    container_name: dawarich_db
    volumes:
      - dawarich_db_data:/var/lib/postgresql/data
      - dawarich_shared:/var/shared
      # - ./postgresql.conf:/etc/postgresql/postgresql.conf # Optional, uncomment if you want to use a custom config
    networks:
      - dawarich
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dawarich_development
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d dawarich_development" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    # command: postgres -c config_file=/etc/postgresql/postgresql.conf # Use custom config, uncomment if you want to use a custom config
  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    volumes:
      - dawarich_public:/var/app/public
      - dawarich_watched:/var/app/tmp/imports/watched
      - dawarich_storage:/var/app/storage
    networks:
      - dawarich
    ports:
      - 3639:3000
      # - 9394:9394 # Prometheus exporter, uncomment if needed
    stdin_open: true
    tty: true
    entrypoint: web-entrypoint.sh
    command: ['bin/rails', 'server', '-p', '3000', '-b', '::']
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      MIN_MINUTES_SPENT_IN_CITY: 60
      TIME_ZONE: Europe/Amsterdam
      APPLICATION_PROTOCOL: http
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: 0.0.0.0
      PROMETHEUS_EXPORTER_PORT: 9394
      SELF_HOSTED: "true"
      STORE_GEODATA: "true"
      APPLICATION_HOSTS: "dawarich.renzo.ovh,localhost,127.0.0.1"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO - http://127.0.0.1:3000/api/v1/health | grep -q '\"status\"\\s*:\\s*\"ok\"'" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
  dawarich_sidekiq:
    image: freikin/dawarich:latest
    container_name: dawarich_sidekiq
    volumes:
      - dawarich_public:/var/app/public
      - dawarich_watched:/var/app/tmp/imports/watched
      - dawarich_storage:/var/app/storage
    networks:
      - dawarich
    stdin_open: true
    tty: true
    entrypoint: sidekiq-entrypoint.sh
    command: ['sidekiq']
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      APPLICATION_HOSTS: localhost
      BACKGROUND_PROCESSING_CONCURRENCY: 10
      APPLICATION_PROTOCOL: http
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: dawarich_app
      PROMETHEUS_EXPORTER_PORT: 9394
      SELF_HOSTED: "true"
      STORE_GEODATA: "true"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "bundle exec sidekiqmon processes | grep $${HOSTNAME}" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s

volumes:
  dawarich_db_data:
  dawarich_shared:
  dawarich_public:
  dawarich_watched:
  dawarich_storage:
```
I've managed to come to this, but I am a bit in the dark here.
```
networks:
  dawarich:
services:
  dawarich_redis:
    image: redis:7.4-alpine
    container_name: dawarich_redis
    command: redis-server
    networks:
      - dawarich
    volumes:
      - dawarich_shared:/data
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    volumes:
      - dawarich_public:/var/app/public
      - dawarich_watched:/var/app/tmp/imports/watched
      - dawarich_storage:/var/app/storage
      - dawarich_db_data:/dawarich_db_data
    ports:
      - 3639:3000
      # - 9394:9394 # Prometheus exporter, uncomment if needed
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      MIN_MINUTES_SPENT_IN_CITY: 60
      TIME_ZONE: Europe/Amsterdam
      APPLICATION_PROTOCOL: http
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: 0.0.0.0
      PROMETHEUS_EXPORTER_PORT: 9394
      SELF_HOSTED: "true"
      STORE_GEODATA: "true"
      APPLICATION_HOSTS: "dawarich.renzo.ovh,localhost,127.0.0.1"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO - http://127.0.0.1:3000/api/v1/health | grep -q '\"status\"\\s*:\\s*\"ok\"'" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
  dawarich_sidekiq:
    image: freikin/dawarich:latest
    container_name: dawarich_sidekiq
    volumes:
      - dawarich_public:/var/app/public
      - dawarich_watched:/var/app/tmp/imports/watched
      - dawarich_storage:/var/app/storage
    networks:
      - dawarich
    stdin_open: true
    tty: true
    entrypoint: sidekiq-entrypoint.sh
    command: ['sidekiq']
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      APPLICATION_HOSTS: localhost
      BACKGROUND_PROCESSING_CONCURRENCY: 10
      APPLICATION_PROTOCOL: http
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: dawarich_app
      PROMETHEUS_EXPORTER_PORT: 9394
      SELF_HOSTED: "true"
      STORE_GEODATA: "true"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "pgrep -f sidekiq" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
      dawarich_redis:
        condition: service_healthy
        restart: true
      dawarich_app:
        condition: service_healthy
        restart: true

volumes:
  dawarich_db_data:
  dawarich_shared:
  dawarich_public:
  dawarich_watched:
  dawarich_storage:
```
