### DISCUSSION TITLE
Difficulty deploying external postgres

### DISCUSSION THREAD

**Discussion by chrismilson** [Freika/dawarich#1441] [General]
I'm hosting postgres outside of the docker-compose, and figured that I would be able to set the DATABASE_HOSTNAME etc. environment variables accordingly and have a good time. On start, I got several errors from the sidekiq container that mostly included "local user with ID 1000 does not exist".

~On closer inspection, it appears as though the sidekiq container is using a bundled psql and actually expects the db to be hosted in the same pod(!) which was surprising.~ It uses a bundled psql, that will attempt to connect to postgres over the network if you actually set the DATABASE_USERNAME and DATABASE_PASSWORD env vars. ouch.

I don't expect this to be a supported use case, but I spent enough time troubleshooting. Hopefully someone else will see this and it can save them time.

**Comment by chrismilson** [comment]
If you're creating a pod in kubernetes, ensure you set the command with the entrypoint for each container, and not just set args. The containers will come up healthy without setting explicit commands in the container specs, but they won't run the data migrations etc. so the site won't work.

```yaml
container: <value of entrypoint from docker-compose>
args: <value of command list from docker-compose>

# e.g. as of today - will probably change so be careful
command: ["web-entrypoint.sh"]
args: ["bin/rails", "-p", "3000", "-b", "::"]
# and
command: ["sidekiq-entrypoint.sh"]
args: ["sidekiq"]
```
