### DISCUSSION TITLE
Unraid Community App Template

### DISCUSSION THREAD

**Discussion by Dalarialus** [Freika/dawarich#150] [Ideas]
Would it be possible to get a community app template for Unraid?

**Comment by HStep20** [comment]
Since its really 3 containers required to make it, I highly recommend using the docker-compose plugin to get this up and running. Here is my compose file I use for my unraid server (since it doesn't seem to support Volumes or Network keys within docker-compose:

I like to nest my appdata folders within a parent `compose` folder for each stack. If you don't like this, you can change the Volume paths under each container. Also make note of the UI ports, since I have changed mine from the defaults here. 

```yml
services:
  dawarich_redis:
    image: redis:7.0-alpine
    command: redis-server
    volumes:
      - /mnt/user/appdata/compose-dawarich/shared:/var/shared/redis
  dawarich_db:
    image: postgres:14.2-alpine
    container_name: dawarich_db
    volumes:
      - /mnt/user/appdata/compose-dawarich/db:/var/lib/postgresql/data
      - /mnt/user/appdata/compose-dawarich/shared:/var/shared
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YOURPASSWORD
  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    volumes:
      - /mnt/user/appdata/compose-dawarich/gems:/usr/local/bundle/gems
      - /mnt/user/appdata/compose-dawarich/public:/var/app/public
    ports:
      - 3731:3000
    stdin_open: true
    tty: true
    entrypoint: dev-entrypoint.sh
    command: ['bin/dev']
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: YOURPASSWORD
      DATABASE_NAME: dawarich_development
      MIN_MINUTES_SPENT_IN_CITY: 60
      APPLICATION_HOST: localhost
      APPLICATION_HOSTS: localhost
      TIME_ZONE: America/Denver
      APPLICATION_PROTOCOL: http
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    depends_on:
      - dawarich_db
      - dawarich_redis
  dawarich_sidekiq:
    image: freikin/dawarich:latest
    container_name: dawarich_sidekiq
    volumes:
      - /mnt/user/appdata/compose-dawarich/gems:/usr/local/bundle/gems
      - /mnt/user/appdata/compose-dawarich/public:/var/app/public
    stdin_open: true
    tty: true
    entrypoint: dev-entrypoint.sh
    command: ['sidekiq']
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: YOURPASSWORD
      DATABASE_NAME: dawarich_development
      APPLICATION_HOST: localhost
      APPLICATION_HOSTS: localhost
      BACKGROUND_PROCESSING_CONCURRENCY: 10
      APPLICATION_PROTOCOL: http
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    depends_on:
      - dawarich_db
      - dawarich_redis
      - dawarich_app
 ```

**Reply by Dalarialus** [reply]
How have you handled the breaking change introduced in 0.19.6?

Did you just change

```
  dawarich_redis:
    image: redis:7.0-alpine
    command: redis-server
    volumes:
      - /mnt/user/appdata/compose-dawarich/shared:/var/shared/redis
  ```

to;

```
  dawarich-redis:
    image: redis:7.0-alpine
    container_name: dawarich-redis
    command: redis-server
    volumes:
      - /mnt/user/appdata/compose-dawarich/shared:/data
```
