### DISCUSSION TITLE
Reverse geocoding stops after Stopping / Starting dawarich containers

### DISCUSSION THREAD

**Discussion by solderdot72** [Freika/dawarich#563] [Q&A]
Hi!
This is really cool! Thank you for putting so much effort into this project.
I run an instance of dawarich on a Raspi 5 with Docker/Portainer. I do frequent automated backups of the Raspi's SD-Card. For that purpose I stop all Docker containers (`docker stop <container>`), create the image and then start the Docker containers again ( `docker start <container>`).
As a starter I imported ~40'000 geopoints via the watched folder (in the end it will be ~4 million geopoints), and reverse geocoding started. The reverse geocoding takes quite some time and is interrupted by the backup job. At this point in time for ~30'000 geopoints the reverse geocoding was accomplished. For the remaining ~10'000 geopoints dawarich tells me that the geocoding was peformed but had no data. Looking into the background jobs I see that the respective queue is empty. Restarting the geocoding populates the queue, but it does not get shorter, and in the stats page I do not see an increase in the number of geocoded points.
Any ideas why this should happen?
Any suggestions on how to shut down dawarich properly for a backup?
Thanks in advance and best regards

**Comment by Freika** [comment]
Can't say much without your version of Dawarich and docker-compose.yml

**Comment by solderdot72** [comment]
Hi Freika,
thank you for taking the time for looking into my question.
I am using DaWarIch 0.19.6. Please find the YML below:
```
networks:
  dawarich:
services:
  dawarich_redis:
    image: redis:7.0-alpine
    container_name: dawarich_redis
    command: redis-server
    networks:
      - dawarich
    volumes:
      - shared_data:/var/shared/redis
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  dawarich_db:
    image: postgres:14.2-alpine
    container_name: dawarich_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - shared_data:/var/shared
    networks:
      - dawarich
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: b59qppd0qh6e-5ikkv2o5dc8
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d dawarich_development" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    volumes:
      - gem_cache:/usr/local/bundle/gems_app
      - public:/var/app/public
      - watched:/var/app/tmp/imports/watched
    networks:
      - dawarich
    ports:
      - 3000:3000
      # - 9394:9394 # Prometheus exporter, uncomment if needed
    stdin_open: true
    tty: true
    entrypoint: dev-entrypoint.sh
    command: ['bin/dev']
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: b59qppd0qh6e-5ikkv2o5dc8
      DATABASE_NAME: dawarich_development
      MIN_MINUTES_SPENT_IN_CITY: 60
      APPLICATION_HOST: localhost
      APPLICATION_HOSTS: localhost
      TIME_ZONE: Europe/Berlin
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
      PHOTON_API_HOST: photon.komoot.io
      PHOTON_API_USE_HTTPS: true
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: 0.0.0.0
      PROMETHEUS_EXPORTER_PORT: 9394
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO - http://127.0.0.1:3000/api/v1/health | grep -q '\"status\"\\s*:\\s*\"ok\"'" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
      dawarich_redis:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '0.50'    # Limit CPU usage to 50% of one core
          memory: '2G'    # Limit memory usage to 2GB
  dawarich_sidekiq:
    image: freikin/dawarich:latest
    container_name: dawarich_sidekiq
    volumes:
      - gem_cache:/usr/local/bundle/gems_sidekiq
      - public:/var/app/public
      - watched:/var/app/tmp/imports/watched
    networks:
      - dawarich
    stdin_open: true
    tty: true
    entrypoint: dev-entrypoint.sh
    command: ['sidekiq']
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: b59qppd0qh6e-5ikkv2o5dc8
      DATABASE_NAME: dawarich_development
      APPLICATION_HOST: localhost
      APPLICATION_HOSTS: localhost
      BACKGROUND_PROCESSING_CONCURRENCY: 10
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
      PHOTON_API_HOST: photon.komoot.io
      PHOTON_API_USE_HTTPS: true
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: dawarich_app
      PROMETHEUS_EXPORTER_PORT: 9394
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "bundle exec sidekiqmon processes | grep $${HOSTNAME}" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
      dawarich_redis:
        condition: service_healthy
        restart: true
      dawarich_app:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '0.50'    # Limit CPU usage to 50% of one core
          memory: '2G'    # Limit memory usage to 2GB

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/DockerVolumes/DaWarIch/db_data
  gem_cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/DockerVolumes/DaWarIch/gem_cache
  shared_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/DockerVolumes/DaWarIch/shared_data
  public:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/DockerVolumes/DaWarIch/public
  watched:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/DockerVolumes/DaWarIch/watched
```
I'd be happy for any  suggestions.
Best regards
-- Solderdot72

**Reply by Freika** [reply]
In one of the most recent releases an error with redis data persistency was fixed. To apply the fix, you need to change your config a bit:

```diff
    volumes:
-      - shared_data:/var/shared/redis
+      - shared_data:/data
```

Change it in both contrainers and it should prevent you from losing background jobs upon restart. Also hit "Restart reverse geocoding" in Background jobs section to make sure your data will be fully reverse geocoded.

Don't forget to follow release notes, it's important :)

**Comment by solderdot72** [comment]
Hi Freika,

Thanks for the suggestion! From now on I will check the YML for changes before updating DaWarIch - promised!

I took the latest YML from GitHub, integrated my changes and started from scratch. Now reverse geocoding continues after a Container stop/start cycle. So looks like my finding was already solved. Thank you!

During testing I found, that import jobs that are currently processed when the container is stopped, apparently are aborted and not resumed. What I see is that every geopoint that was already imported from a GPX file when the container was stopped is displayed on the map, all subsequent geopoints in the same GPX file are not shown. 

My best guess is that the GPX file is tagged as "imported" or removed from the "to be processed"-List before the laste geopoint is processed and moved into the database, so when the container is started again, the GPX file is skipped.

Could you please check if this might be the case? If you prefer, I can open a new thread for this topic since it is new and probably not closely related to the initial one.

Thanks an best regards
-- Solderdot

P.S.: Here comes my current YML:
```
networks:
  dawarich:
services:
  dawarich_redis:
    image: redis:7.0-alpine
    container_name: dawarich_redis
    command: redis-server
    networks:
      - dawarich
    volumes:
      - dawarich_shared:/data
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  dawarich_db:
    image: postgres:14.2-alpine
    container_name: dawarich_db
    volumes:
      - dawarich_db_data:/var/lib/postgresql/data
      - dawarich_shared:/var/shared
    networks:
      - dawarich
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xxxx
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d dawarich_development" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    volumes:
      - dawarich_gem_cache_app:/usr/local/bundle/gems
      - dawarich_public:/var/app/public
      - dawarich_watched:/var/app/tmp/imports/watched
    networks:
      - dawarich
    ports:
      - 3000:3000
      # - 9394:9394 # Prometheus exporter, uncomment if needed
    stdin_open: true
    tty: true
    entrypoint: dev-entrypoint.sh
    command: ['bin/dev']
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: xxxx
      DATABASE_NAME: dawarich_development
      MIN_MINUTES_SPENT_IN_CITY: 60
      APPLICATION_HOST: localhost
      APPLICATION_HOSTS: localhost
      TIME_ZONE: Europe/Berlin
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
      PHOTON_API_HOST: photon.komoot.io
      PHOTON_API_USE_HTTPS: true
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: 0.0.0.0
      PROMETHEUS_EXPORTER_PORT: 9394
      ENABLE_TELEMETRY: false # More on telemetry: https://dawarich.app/docs/tutorials/telemetry
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO - http://127.0.0.1:3000/api/v1/health | grep -q '\"status\"\\s*:\\s*\"ok\"'" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
      dawarich_redis:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '0.50'    # Limit CPU usage to 50% of one core
          memory: '2G'    # Limit memory usage to 2GB
  dawarich_sidekiq:
    image: freikin/dawarich:latest
    container_name: dawarich_sidekiq
    volumes:
      - dawarich_gem_cache_sidekiq:/usr/local/bundle/gems
      - dawarich_public:/var/app/public
      - dawarich_watched:/var/app/tmp/imports/watched
    networks:
      - dawarich
    stdin_open: true
    tty: true
    entrypoint: dev-entrypoint.sh
    command: ['sidekiq']
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: b59qppd0qh6e-5ikkv2o5dc8
      DATABASE_NAME: dawarich_development
      APPLICATION_HOST: localhost
      APPLICATION_HOSTS: localhost
      BACKGROUND_PROCESSING_CONCURRENCY: 10
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
      PHOTON_API_HOST: photon.komoot.io
      PHOTON_API_USE_HTTPS: true
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: dawarich_app
      PROMETHEUS_EXPORTER_PORT: 9394
      ENABLE_TELEMETRY: false # More on telemetry: https://dawarich.app/docs/tutorials/telemetry
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "bundle exec sidekiqmon processes | grep $${HOSTNAME}" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
      dawarich_redis:
        condition: service_healthy
        restart: true
      dawarich_app:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '0.50'    # Limit CPU usage to 50% of one core
          memory: '2G'    # Limit memory usage to 2GB

volumes:
  dawarich_db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/DockerVolumes/DaWarIch/db_data
  dawarich_gem_cache_app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/DockerVolumes/DaWarIch/gem_cache
  dawarich_gem_cache_sidekiq:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/DockerVolumes/DaWarIch/gem_cache
  dawarich_shared:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/DockerVolumes/DaWarIch/shared_data
  dawarich_public:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/DockerVolumes/DaWarIch/public
  dawarich_watched:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/DockerVolumes/DaWarIch/watched
```
