### DISCUSSION TITLE
problem with container dawarich_db

### DISCUSSION THREAD

**Discussion by xep22** [Freika/dawarich#590] [General]
Just tried to install Dawarich following [this](https://dawarich.app/docs/intro#setup-your-dawarich-instance) and always get error with the dawarich_db container. Tried on windows and Debian, and on both it happens, so have to be a general bug.

`[+] Running 5/5
 ✔ Network dawarich_dawarich   Created                                                                             0.1s
 ✔ Container dawarich_redis    Healthy                                                                             6.9s
 ✘ Container dawarich_db       Error                                                                              16.9s
 ✔ Container dawarich_app      Created                                                                             0.1s
 ✔ Container dawarich_sidekiq  Created                                                                             0.1s
dependency failed to start: container dawarich_db is unhealthy`

Log says:

```
2024-12-23 19:48:09.029 GMT [1] LOG:  input in flex scanner failed at file "/etc/postgresql/postgresql.conf" line 1
2024-12-23 19:48:09.030 GMT [1] FATAL:  configuration file "/etc/postgresql/postgresql.conf" contains errors
```

**Comment by Freika** [comment]
@xep22 update to a new version and make sure your custom postgres config is commented out

**Reply by xep22** [reply]
I never installed Dawarich, I just tried to install first time...

**Reply by xep22** [reply]
ok works now with new config

**Reply by solderdot72** [reply]
Would you please be so kind and share details on what exactly you did to overcome the issue?

**Comment by solderdot72** [comment]
Hi and merry, merry christmas, everyone!

Same here: Unable to deploy the stack. I removed the old stack completely and started deployment from scratch. I receive the following error in Portainer:
```
Failed to deploy a stack: Network dawarich_dawarich 
Creating Network dawarich_dawarich 
Created Container dawarich_redis 
Creating Container dawarich_db 
Creating Container dawarich_redis 
Created Container dawarich_db 
Created Container dawarich_app 
Creating dawarich_app 
Your kernel does not support memory limit capabilities or the cgroup is not mounted. Limitation discarded. 
Container dawarich_app 
Created Container dawarich_sidekiq 
Creating dawarich_sidekiq 
Your kernel does not support memory limit capabilities or the cgroup is not mounted. Limitation discarded. 
Container dawarich_sidekiq 
Created Container dawarich_db 
Starting Container dawarich_redis 
Starting Container dawarich_db 
Started Container dawarich_redis 
Started Container dawarich_db 
Waiting Container dawarich_redis 
Waiting Container dawarich_db 
Error Container dawarich_redis Healthy dependency failed to start: container dawarich_db is unhealthy 
```
I receive this very same error no matter if I include the new statements for the cusstomer config or not. I copied the sample config into the directory `dawarich_db_data`, in my case `/data/DockerVolumes/DaWarIch/db_data`. Not sure if this is the correct folder, though.

Here's my YML file:
```
networks:
  dawarich:
services:
  dawarich_redis:
    image: redis:7.0-alpine
    container_name: dawarich_redis
    command: redis-server
    networks:
      - dawarich
    volumes:
      - dawarich_shared:/data
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  dawarich_db:
    image: postgres:14.2-alpine
    shm_size: 1G
    container_name: dawarich_db
    volumes:
      - dawarich_db_data:/var/lib/postgresql/data
      - dawarich_shared:/var/shared
#      - ./postgresql.conf:/etc/postgresql/postgresql.conf # Provide path to your custom config
    networks:
      - dawarich
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d dawarich_development" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
#    command: postgres -c config_file=/etc/postgresql/postgresql.conf # Use custom config
  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    volumes:
      - dawarich_gem_cache_app:/usr/local/bundle/gems
      - dawarich_public:/var/app/public
      - dawarich_watched:/var/app/tmp/imports/watched
    networks:
      - dawarich
    ports:
      - 3000:3000
      # - 9394:9394 # Prometheus exporter, uncomment if needed
    stdin_open: true
    tty: true
    entrypoint: dev-entrypoint.sh
    command: ['bin/dev']
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      MIN_MINUTES_SPENT_IN_CITY: 60
      APPLICATION_HOST: localhost
      APPLICATION_HOSTS: localhost
      TIME_ZONE: Europe/Berlin
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
      PHOTON_API_HOST: photon.komoot.io
      PHOTON_API_USE_HTTPS: true
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: 0.0.0.0
      PROMETHEUS_EXPORTER_PORT: 9394
      ENABLE_TELEMETRY: false # More on telemetry: https://dawarich.app/docs/tutorials/telemetry
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO - http://127.0.0.1:3000/api/v1/health | grep -q '\"status\"\\s*:\\s*\"ok\"'" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
      dawarich_redis:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '0.50'    # Limit CPU usage to 50% of one core
          memory: '2G'    # Limit memory usage to 2GB
  dawarich_sidekiq:
    image: freikin/dawarich:latest
    container_name: dawarich_sidekiq
    volumes:
      - dawarich_gem_cache_sidekiq:/usr/local/bundle/gems
      - dawarich_public:/var/app/public
      - dawarich_watched:/var/app/tmp/imports/watched
    networks:
      - dawarich
    stdin_open: true
    tty: true
    entrypoint: dev-entrypoint.sh
    command: ['sidekiq']
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      APPLICATION_HOST: localhost
      APPLICATION_HOSTS: localhost
      BACKGROUND_PROCESSING_CONCURRENCY: 10
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
      PHOTON_API_HOST: photon.komoot.io
      PHOTON_API_USE_HTTPS: true
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: dawarich_app
      PROMETHEUS_EXPORTER_PORT: 9394
      ENABLE_TELEMETRY: false # More on telemetry: https://dawarich.app/docs/tutorials/telemetry
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "bundle exec sidekiqmon processes | grep $${HOSTNAME}" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
      dawarich_redis:
        condition: service_healthy
        restart: true
      dawarich_app:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '0.50'    # Limit CPU usage to 50% of one core
          memory: '2G'    # Limit memory usage to 2GB

volumes:
  dawarich_db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/DockerVolumes/DaWarIch/db_data
  dawarich_gem_cache_app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/DockerVolumes/DaWarIch/gem_cache
  dawarich_gem_cache_sidekiq:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/DockerVolumes/DaWarIch/gem_cache
  dawarich_shared:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/DockerVolumes/DaWarIch/shared_data
  dawarich_public:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/DockerVolumes/DaWarIch/public
  dawarich_watched:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/DockerVolumes/DaWarIch/watched
```

Any ideas what might be wrong?
