### DISCUSSION TITLE
List of public Photon instances for reverse geocoding

### DISCUSSION THREAD

**Discussion by Freika** [Freika/dawarich#693] [General]
If you have a Photon instance up and running, and willing to provide it for Dawarich users to utilize, please post it in this thread and I'll add it to the main message.

Two important things:

1. It would be good if you could provide SSL-protected connection and use rate-limiting of some kind, so your servers would not be flooded with hundreds of thousands of requests
2. To all who wants to use Photon instances from this list: ⚠️**USE THEM AT YOUR OWN RISK.**⚠️ This is YOUR private data you're sending to be reverse geocoded, keep that in mind. You have full responsibility for using 3rd party services and sending your data there to be processed.

Thank you!

## Community public instances

- https://photon.koalasec.org/ by @rtuszik 
- https://photon.donsomhong.net/ by @dhj65 ([10 requests per source IP and second](https://github.com/Freika/dawarich/discussions/693#discussioncomment-12032318))
- https://photon.marsmathis.com/ by @marsmathis 
- https://photon.vanoosterhout.cloud/ by @rvoosterhout (Ratelimits with 10 request per second, per source IP)
- https://photon.kllswitch.com/ by @blownco

**Comment by rtuszik** [comment]
Feel free to use:

https://photon.koalasec.org

No limits. Should be able to take a beating.

**Comment by dhj65** [comment]
I'm offering my photon for free use as well:

https://photon.donsomhong.net

please note: request rate is currently limited to 10 requests per source IP and second. This might be increased or decreased, depending on the server load.

**Reply by dhj65** [reply]
I haven't noted any excess usage during the last 3 monthes... The limits have been disabled for now.

There was a problem, that nginx did not reload properly after update of the ssl cert. User requests probably failed during the last days. This is fixed now and a valid cert is used.

**Reply by TheRealNox** [reply]
Thanks a lot for that!
I had my own container, but got [ressource limited (or what looks like it)](https://github.com/rtuszik/photon-docker/issues/59) with the recent update, so in the meantime, I went and use yours, Again, thanks for that!!

Please let me know is usage goes to high (I had 3000ish point to reverse geocode)

**Reply by TheRealNox** [reply]
Seems to be down at the minute @dhj65 ?

**Comment by marsmathis** [comment]
https://photon.marsmathis.com

No rate limit for now.
Location is Central Europe, four cores and 16 GB RAM. No idea whether this is too much or not enough, we’ll see.

~~Edit: Welp, I just had to limit the instance. Funnily enough, the reason was not hardware (CPU is at 0.3 % utilization), but rather the network as I only have around 2 MB/s down and the Photon requests were saturating my line.~~

Edit 2: Limit taken back out, I thought the requests saturated the line but it's the background update. All good.

**Comment by robert-nash** [comment]
I was initially hesitant to use a service from this list as I was concerned about the possibility of one of the (kindly provided) servers going down in time.

I ended up setting a local "load balancer" using caddy which distributes requests between the three services currently available. I am unsure whether this is the best way of dealing with it but it seems like a reasonable solution for providing resilience as well as reducing the load on any of the individual servers.

Here is an excerpt from my Caddyfile in case it is helpful for anyone:

```
http://localhost:8888 {
    # Reverse proxy requests to the list of public Photon servers.
    reverse_proxy https://photon.koalasec.org https://photon.donsomhong.net https://photon.marsmathis.com {

        # Sets the load balancing policy. round_robin cycles through them in order.
        lb_policy round_robin

        # Configure passive health checks to automatically use healthy servers.
        # After 2 consecutive failed requests, mark the server as down.
        max_fails 2
        # Consider it down for 60 seconds before trying it again.
        fail_duration 60s

        # Rewrite the Host header to match the expected Host for the upstream server
        header_up Host {upstream_hostport}
    }
}
```

**Reply by TheRealNox** [reply]
That's a very good idea!
I've ended adding caddy to my compose stack as such:
```
  dawarich_caddy:
    image: caddy:2.8.4-alpine
    container_name: dawarich_caddy
    networks:
      - dawarich-net
    volumes:
      - /volume1/docker/configs/dawarich/caddy:/etc/caddy
      - /volume1/docker/configs/dawarich/caddy_data:/data
      - /volume1/docker/configs/dawarich/caddy_config:/config
    restart: unless-stopped
    environment:
      GOMAXPROCS: 0 //Needed as this is not set in Synology Docker implementation
[...]
  dawarich_app:
  [...]
    environment:
      PHOTON_API_HOST: dawarich_caddy:8888
      PHOTON_API_USE_HTTPS: false 
```
Working like a charm!
