### DISCUSSION TITLE
Reverse Geocode Question

### DISCUSSION THREAD

**Discussion by timcrice** [Freika/dawarich#701] [Q&A] [answered]
I started my own reverse geocode server last night following the Dawarich and Ton Snoei guides. I have the server running, and as the Ton Snoei guide states the API is reachable in the browser at http://"my server name":2322/api?q=amsterdam. However when I put that address into the docker-compose.yml file under dawarich_app and dawarich_sidekiq and restart Dawarich every point since has been a "point without data"  

Is there a different format for putting this into the yml? Or is there something else that I am missing?

P.S-  This is the most exciting project I've found in quite a while, thank you Freika!

**Comment by Freika** [comment]
@timcrice did you try to check your specific coordinates, if photon returns a valid response for them?

**Reply by timcrice** [reply]
I haven't, how would I do that?

**Reply by Freika** [reply]
@timcrice replace with real values both url and coordinates: https://your.photon.url/reverse?lon=13.352233&lat=52.51491

**Reply by timcrice** [reply]
This doesn't seem like a valid response:
![Screenshot from 2025-01-21 20-01-34](https://github.com/user-attachments/assets/417f4b1f-3915-4ca4-8f29-0fd9b28f61e3)

**Reply by Freika** [reply]
It's a valid response, just an empty one. This indicates either there is no data on these coordinates at all, or your Photon instance doesn't have it (which is kinda normal). That's why you're having "points without data".

One suggestion might be is to check if you have downloaded photon data archive that includes data on the country you're trying to get reverse geocoding data for

**Reply by timcrice** [reply]
I finally got some time to work on this.  I do get a proper response when manually sending coordinates to the API, as you suggested.  It was a rookie mistake, I didn't realize that it was formatted Lon before lat.  I was reversing the numbers and it was looking for a location outside of my downloaded dataset.

I however am still unable to get reverse geocoded data in Dawarich.  This is a reoccurring  warning I am getting in the logs, does it mean anything to you?

dawarich_sidekiq  | D, [2025-01-27T14:29:02.096126 #8] DEBUG -- :   Point Load (1.2ms)  SELECT "points".* FROM "points" WHERE "points"."id" = $1 LIMIT $2  [["id", 31599], ["LIMIT", 1]]
dawarich_sidekiq  | D, [2025-01-27T14:29:02.096738 #8] DEBUG -- :   ↳ app/services/reverse_geocoding/points/fetch_data.rb:7:in `initialize'
dawarich_sidekiq  | E, [2025-01-27T14:29:02.099910 #8] ERROR -- : Error performing ReverseGeocodingJob (Job ID: 77b2e755-1c40-420e-b02f-e56a7e3857ed) from Sidekiq(reverse_geocoding) in 6.29ms: Socket::ResolutionError (Socket::ResolutionError):

I appreciate the help!

**Comment by WorldTeacher** [comment]
I set up the photon-docker within the dawarich docker-compose.yml and set the  PHOTON_API_HOST to '192.168.178.20:2322' (the server IP:Port I assigned to photon. Sidekiq now reports this: `OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 peeraddr=192.168.178.20:2322 state=error: record layer failure` for ~16k points.

This is a part of the config:
```
dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    volumes:
      - dawarich_public:/var/app/public
      - dawarich_watched:/var/app/tmp/imports/watched
    networks:
      - dawarich
    ports:
      - 3009:3000
      # - 9394:9394 # Prometheus exporter, uncomment if needed
    stdin_open: true
    tty: true
    entrypoint: web-entrypoint.sh
    command: ['bin/rails', 'server', '-p', '3000', '-b', '::']
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: db_username
      DATABASE_PASSWORD: db_password
      DATABASE_NAME: dawarich_development
      MIN_MINUTES_SPENT_IN_CITY: 60
      APPLICATION_HOST: localhost
      APPLICATION_HOSTS: localhost, 192.168.178.20,https://dawarich.theprivateserver.de,dawarich.theprivateserver.de
      TIME_ZONE: Europe/Berlin
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: 0.0.0.0
      PROMETHEUS_EXPORTER_PORT: 9394
      PHOTON_API_HOST: '192.168.178.20:2322'
      ENABLE_TELEMETRY: false # More on telemetry: https://dawarich.app/docs/tutorials/telemetry
``` 

did I make any errors setting this up?

Opening the server IP:Port in the browser for both q=amsterdam and lat/lon gives me valid responses
