### DISCUSSION TITLE
Which docker-compose to use ?

### DISCUSSION THREAD

**Discussion by r4nchy** [Freika/dawarich#767] [Q&A] [answered]
https://github.com/Freika/dawarich/tree/master/docker

There are two docker compose files called `docker-compose.production.yml` and `docker-compose.yml` both having different image versions.

Which one should I use as a user ?

**Comment by Freika** [comment]
Please use the one that is `docker/docker-compose.yml`

**Reply by r4nchy** [reply]
I get following error while `docker compose up` on the `docker-compose.yml`

and just the dawarich-db and dawarich-redis container are active

```
[+] Running 6/7warich-app
 ✔ Network dawarich_dawarich                                                                                                   Created0.2s r kernel does not support memory limit capabilities or the cgroup is not mounted. Limitation discarde
 ✔ Container dawarich-redis                                                                                                    Healthy7.0s ch-sidekiq
 ✔ Container dawarich-db                                                                                                       Healthy6.5s  Your kernel does not support memory limit capabilities or the cgroup is not mounted. Limitation disc
[+] Running 6/7warich-app
 ✔ Network dawarich_dawarich                                                                                                   Created0.2s r kernel does not support memory limit capabilities or the cgroup is not mounted. Limitation discarde
 ✔ Container dawarich-redis                                                                                                    Healthy7.0s ch-sidekiq
 ✔ Container dawarich-db                                                                                                       Healthy6.5s  Your kernel does not support memory limit capabilities or the cgroup is not mounted. Limitation disc
[+] Running 6/7warich-app
 ✔ Network dawarich_dawarich                                                                                                   Created0.2s r kernel does not support memory limit capabilities or the cgroup is not mounted. Limitation discarde
 ✔ Container dawarich-redis                                                                                                    Healthy7.0s ch-sidekiq
 ✔ Container dawarich-db                                                                                                       Healthy6.5s  Your kernel does not support memory limit capabilities or the cgroup is not mounted. Limitation disc
[+] Running 6/7warich-app
 ✔ Network dawarich_dawarich                                                                                                   Created0.2s r kernel does not support memory limit capabilities or the cgroup is not mounted. Limitation discarde
 ✔ Container dawarich-redis                                                                                                    Healthy7.0s ch-sidekiq
 ✔ Container dawarich-db                                                                                                       Healthy6.5s  Your kernel does not support memory limit capabilities or the cgroup is not mounted. Limitation disc
 ⠴ Container dawarich-app                                                                                                      Starting7.7s
 ! dawarich_app Your kernel does not support memory limit capabilities or the cgroup is not mounted. Limitation discarded.     0.0s
 ✔ Container dawarich-sidekiq
       Created0.2s
 ! dawarich_sidekiq Your kernel does not support memory limit capabilities or the cgroup is not mounted. Limitation discarded. 0.0s
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: exec: "dev-entrypoint.sh": executable file not found in $PATH: unknown
```

**Reply by Freika** [reply, marked as answer]
Well, I see you're not using the most recent docker compose file judging by this line in your log:

> Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: exec: "dev-entrypoint.sh": executable file not found in $PATH: unknown

**Reply by r4nchy** [reply]
this is the one I use

```
services:
  dawarich_redis:
    image: redis:7.0-alpine
    container_name: dawarich-redis
    command: redis-server
    networks:
      - dawarich
    volumes:
      - /home/pi/data/dawarich/dawarich_shared:/data
    # restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    labels:
      - sablier.enable=true
      - sablier.group=dawarich


  dawarich_db:
    image: postgres:14.2-alpine
    shm_size: 1G
    container_name: dawarich-db
    volumes:
      - /home/pi/data/dawarich/dawarich_db_data:/var/lib/postgresql/data
      - /home/pi/data/dawarich/dawarich_shared:/var/shared
    networks:
      - dawarich
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    # restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d dawarich_development" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    labels:
      - sablier.enable=true
      - sablier.group=dawarich


  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich-app
    volumes:
      - /home/pi/data/dawarich/dawarich_public:/var/app/public
      - /home/pi/data/dawarich/dawarich_watched:/var/app/tmp/imports/watched
    networks:
      - dawarich
    ports:
      - 3121:3000
      # - 9394:9394 # Prometheus exporter, uncomment if needed
    stdin_open: true
    tty: true
    entrypoint: dev-entrypoint.sh
    command: ['bin/rails', 'server', '-p', '3000', '-b', '::']
    # restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      MIN_MINUTES_SPENT_IN_CITY: 60
      APPLICATION_HOST: localhost
      APPLICATION_HOSTS: localhost,dawarich.example.org
      TIME_ZONE: Europe/London
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: 0.0.0.0
      PROMETHEUS_EXPORTER_PORT: 9394
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO - http://127.0.0.1:3000/api/v1/health | grep -q '\"status\"\\s*:\\s*\"ok\"'" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
      dawarich_redis:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '0.50'    # Limit CPU usage to 50% of one core
          memory: '4G'    # Limit memory usage to 2GB
    labels:
      - sablier.enable=true
      - sablier.group=dawarich

  dawarich_sidekiq:
    image: freikin/dawarich:latest
    container_name: dawarich-sidekiq
    volumes:
      - /home/pi/data/dawarich/dawarich_public:/var/app/public
      - /home/pi/data/dawarich/dawarich_watched:/var/app/tmp/imports/watched
    networks:
      - dawarich
    stdin_open: true
    tty: true
    entrypoint: sidekiq-entrypoint.sh
    command: ['sidekiq']
    # restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      APPLICATION_HOST: localhost
      APPLICATION_HOSTS: localhost,dawarich.example.org
      BACKGROUND_PROCESSING_CONCURRENCY: 10
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: dawarich_app
      PROMETHEUS_EXPORTER_PORT: 9394
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "bundle exec sidekiqmon processes | grep $${HOSTNAME}" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
      dawarich_redis:
        condition: service_healthy
        restart: true
      dawarich_app:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '0.50'    # Limit CPU usage to 50% of one core
          memory: '4G'    # Limit memory usage to 2GB
    labels:
      - sablier.enable=true
      - sablier.group=dawarich


networks:
  dawarich:

volumes:
  dawarich_db_data:
  dawarich_shared:
  dawarich_public:
  dawarich_watched:
  ```
