### DISCUSSION TITLE
Home assistant as tracking app

### DISCUSSION THREAD

**Discussion by geekscrapy** [Freika/dawarich#77] [Q&A] [answered]
Lots of the self hosted community already run Home assistant which has the ability to track location. Is there a way to tap into this rather than run an additional app?

**Comment by Freika** [comment]
I think at some point I'll research the possibility for HomeAssistant to send data to Dawarich. I'm not aware if there are any plugins allowing sending geodata to 3rd party URL, but if there are any, send me a link and example of payload, and I'll experiment with it.

Meanwhile I asked Chatgpt are there ways to send this data to 3rd party urls, and it suggested using something like NodeRED or other webhooks-based solutions :)

**Comment by drlobo** [comment, marked as answer]
hey, I was able to push Home assistant device location to Darawich with the RESTful Command integration. It could probably be improved, but it's a first working step.

Here is how I configured it: 
``` yaml
# configuration.yaml
rest_command:
    push_position_to_dawarich:
      url: http://dawarich_dns:3000/api/v1/overland/batches?api_key={{ api_key }}
      method: POST
      content_type: 'application/json'
      payload: >
        {
          "locations": [
          {
           "type": "Feature",
           "geometry":{
             "type": "Point",
             "coordinates":[
               {{ longitude }},
               {{ latitude }}
              ]
           },
           "properties":{
              "api_key": "xxxxxxxxxxxxx",
              "timestamp": "{{ now().isoformat() }}",
              "altitude": {{ altitude }},
              "speed": {{ speed }},
              "horizontal_accuracy": 0,
              "vertical_accuracy": {{ vertical_accuracy }},
              "motion": [],
              "pauses": false,
              "activity": "{{ activity }}",
              "desired_accuracy": 0,
              "deferred": 0,
              "significant_change": "unknown",
              "locations_in_payload": 1,
              "device_id": "{{device_id}}",
              "wifi": "unknown",
              "battery_state": "unknown",
              "battery_level": {{ battery_level }}
           }
          }
          ]
        }
```
_**Note:** you have to restart homeassistant (and not reload the yaml files) the first time you add a rest_command, later you can use the `rest_command.reload` service to refresh any changes in the rest command definition._

and this the automation to call the rest command when the latitude or longitude of a device tracker changes.  

```yaml
alias: Push pixel7 position to dawarich
description: ""
trigger:
  - platform: state
    entity_id:
      - device_tracker.pixel_7
    attribute: longitude
  - platform: state
    entity_id:
      - device_tracker.pixel_7
    attribute: latitude
condition: []
action:
  - service: rest_command.push_position_to_dawarich
    data:
      latitude: "{{ state_attr('device_tracker.pixel_7','latitude') }}"
      longitude: "{{ state_attr('device_tracker.pixel_7','longitude') }}"
      speed: "{{ state_attr('device_tracker.pixel_7','speed') }}"
      altitude: "{{ state_attr('device_tracker.pixel_7','altitude') }}"
      vertical_accuracy: "{{ state_attr('device_tracker.pixel_7','vertical_accuracy') }}"
      activity: "{{ states('sensor.pixel_7_detected_activity') }}"
      device_id: pixel7
      battery_level: "{{ states('sensor.pixel_7_battery_level') }}"
mode: single
```

I used the overland format because it was the only one documented in the swagger api-docs. I would be nice to expose as well the owntrack api endpoint, and even nicer to add a generic api endpoint with a simple/flat json format with only the minimal required fields for darwarich.

Edit: adding the api_key as template variable, to be able to resused the rest command with multiple device/users (each user in dawarich has its own api key)

**Reply by Freika** [reply]
That is just awesome! I can't check it out myself as I'm not a HA user, but I'll be referencing to this post anyone interested in similar integration, thank you!

**Reply by lukyjay** [reply]
Thanks so much for this! It would be great to have it added to the Readme and Wiki

**Reply by woernsn** [reply]
Nice, I didn't know there was a API documentation for overland.
But there is also a documentation for OwnTracks.
See https://github.com/Freika/dawarich/discussions/118 (I wrote that using my wrong account. meh)

**Reply by TheDoor** [reply]
With the introduction of popups in version 0.9.4, you can now see your devices' battery levels as a percentage. In this automation, the battery percentage is represented as a value from 0-100. However, Dawarich uses a value between 0-1 and displays it as a percentage. Therefore, I recommend replacing the `battery_level` line with the following suggestion for more correct display on the Dawarich popup:

```yaml
"{{ (states('sensor.device_battery_level')) | int / 100 }}"
```

**Reply by estevez-dev** [reply]
Some more suggested improvements. I found that some points were missing when comparing my location history in Dawarich and Home Assistant.
Unlike `latitude` and `longitude`, `speed`, `altitude`, and `vertical_accuracy` could be absent among `device_tracker` attributes. In that case, `None` will be sent in the request, resulting in an HTTP 400 response from Dawarich. To prevent that from happening, we need to check the attributes before sending:
```
speed: >-
    {{ iif(state_attr('device_tracker.calling_device', 'speed') is none, '0', state_attr('device_tracker.calling_device', 'speed')) }}
altitude: >-
    {{ iif(state_attr('device_tracker.calling_device', 'altitude') is none, '300', state_attr('device_tracker.calling_device', 'altitude')) }}
vertical_accuracy: >-
    {{ iif(state_attr('device_tracker.calling_device', 'vertical_accuracy') is none, '0', state_attr('device_tracker.calling_device', 'vertical_accuracy')) }}
```

I chose "300" as a fallback altitude because this is an average altitude for my place, but I'm unsure if it is a good idea. Not sure about "0" as well.

**Reply by bklaesener** [reply]
Probably a stupid question since nobody else asked: what do I put as "device_id" data?

Apparently not the device tracker entity in HA, which would be "device_tracker.pixel_7" instead of "pixel7" in the above example automation.

Any variation I have tried in my setup triggers a "device unknown to Home Assistant" error reported by Spook.

**Reply by hockey6611** [reply]
> Probably a stupid question since nobody else asked: what do I put as "device_id" data?
> 
> Apparently not the device tracker entity in HA, which would be "device_tracker.pixel_7" instead of "pixel7" in the above example automation.
> 
> Any variation I have tried in my setup triggers a "device unknown to Home Assistant" error reported by Spook.

I interpreted it as arbitrary, and comes from the [Overland app API](https://github.com/aaronpk/Overland-iOS#api) that dawarich is being made compatible with. It is not associated with a home assistant entity, and you can add anything you like as the device id.

**Reply by bklaesener** [reply]
> I interpreted it as arbitrary

Thanks a lot, that's what I thought initially but was then irritated by the error reported by Spook, which is probably irrelevant here. I am now using the actual hexadecimal device ID that HA assigns and am getting no more complaints by Spook.

I am still not getting any locations showing up in Dawarich although the automation appears to be pushing, but at least I can reasonably assume it is not due to a wrong device ID.

**Comment by Tazmanian79** [comment]
Hello,

do you have more information about the position of Home Assistant.  I mean how freakantly is it updated?
I now use the owntracks app and it's running fine.  But I don't want several apps and as I'm a user of HA it would be great to be able to use HA for the locations updates.

Another question.  I have 2 users, how should this be configured?
Just change this?
    push_position_to_dawarich_user1:
and
    push_position_to_dawarich_user2:

and than of course use the Dawarich API for each user.


Is there a way to see which app pushed the locations update to Dawarich?
I mean as a test to see the difference between Owntracks and HA I would like to let it run simultaneously

**Reply by drlobo** [reply]
I would say homeassistant app location updates are less frequent than a dedicated app like owntracks, here is the [documentation](https://companion.home-assistant.io/docs/core/location/) from  homeassisant explaining when a location update is triggered.

I 've edited my code sample to allow the rest command to be resused with multiple users, the api key in the url  is now a variable that you can pass in the automation data.

To compare home assistant and owncloud, I would simply create a new user (one user for HA, one for Owntrack) and each app will push location with it's own api key. If you do so, I would as well be interested in the results, but I guess that owntrack will be more accurate

**Comment by geekscrapy** [comment]
It would be nice to have the option even with less accuracy 👍

**Comment by pmatis** [comment]
Thank you @drlobo for the head start! I would not have gotten there without your guide.
I think I've streamlined the connection and configuration. As I understand it, not all variables are available to HA and not all data is stored in DaWarich.... or maybe I just don't see it. Either way, the following suits me adequately:

My /opt/homeassistant/config/rest_command.yaml file:

```
push_position_to_dawarich:
  url: http://10.1.2.3:3000/api/v1/overland/batches?api_key={{ api_key }}
  method: POST
  content_type: 'application/json'
  payload: >
    {
      "locations": [
      {
       "type": "Feature",
       "geometry":{
         "type": "Point",
         "coordinates":[
           {{ longitude }},
           {{ latitude }}
          ]
       },
       "properties":{
          "api_key": "{{ api_key }}",
          "timestamp": "{{ now().isoformat() }}",
          "altitude": {{ altitude }},
          "speed": {{ speed }},
          "horizontal_accuracy": 0,
          "vertical_accuracy": {{ vertical_accuracy }},
          "significant_change": "unknown",
          "locations_in_payload": 1
       }
      }
      ]
    }
```


My Automation yaml:

```
alias: Push My position to DaWarich
description: ""
trigger:
  - platform: state
    entity_id:
      - device_tracker.sm_s918u
    attribute: longitude
  - platform: state
    entity_id:
      - device_tracker.sm_s918u
    attribute: latitude
condition: []
action:
  - service: rest_command.push_position_to_dawarich
    data:
      api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      vertical_accuracy: "{{ state_attr(state_attr('person.myuser','source'),'vertical_accuracy') }}"
      latitude: "{{ state_attr('person.myuser','latitude') }}"
      longitude: "{{ state_attr('person.myuser','longitude') }}"
      speed: "{{ state_attr(state_attr('person.myuser','source'),'speed') }}"
      altitude: "{{ state_attr(state_attr('person.myuser','source'),'altitude') }}"
mode: single
```


Notice, I'm using person.myuser so that whatever device the user has is what's being tracked - except one important thing... the trigger is based on a device. I know that I could use a variable to further streamline this, but this is a WIP, too. Maybe I'll update this again later, but I wanted to get this out for others.

Does anyone know how to trigger on a PERSON changing location?

**Reply by drlobo** [reply]
in the trigger section, simply use person.myuser instead of device_tracker.sm_s918u

**Reply by Carunga** [reply]
Hello,
great concept, love the idea. When I try your code I get a 400 error when prasing the content (find the output of dawarich below). Any ideas what I might be doint worng?

```
dawarich_app        | 06:29:36 web.1  | F, [2024-08-08T06:29:36.285393 #62] FATAL -- :
dawarich_app        | 06:29:36 web.1  | ActionDispatch::Http::Parameters::ParseError (Error occurred while parsing request parameters):
dawarich_app        | 06:29:36 web.1  |
dawarich_app        | 06:29:36 web.1  | app/controllers/application_controller.rb:29:in `current_api_user'
dawarich_app        | 06:29:36 web.1  | app/controllers/application_controller.rb:23:in `authenticate_api_key'
dawarich_app        | 06:29:36 web.1  | D, [2024-08-08T06:29:36.575943 #62] DEBUG -- :   Rendering layout vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.3.4/lib/action_dispatch/middleware/templates/rescues/layout.erb
dawarich_app        | 06:29:36 web.1  | D, [2024-08-08T06:29:36.576032 #62] DEBUG -- :   Rendering vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.3.4/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout
dawarich_app        | 06:29:36 web.1  | D, [2024-08-08T06:29:36.577000 #62] DEBUG -- : Error occurred while parsing request parameters.
dawarich_app        | 06:29:36 web.1  | Contents:
dawarich_app        | 06:29:36 web.1  |
dawarich_app        | 06:29:36 web.1  | {
dawarich_app        | 06:29:36 web.1  |   "locations": [
dawarich_app        | 06:29:36 web.1  |   {
dawarich_app        | 06:29:36 web.1  |    "type": "Feature",
dawarich_app        | 06:29:36 web.1  |    "geometry":{
dawarich_app        | 06:29:36 web.1  |      "type": "Point",
dawarich_app        | 06:29:36 web.1  |      "coordinates":[
dawarich_app        | 06:29:36 web.1  |        57.701115750324459,
dawarich_app        | 06:29:36 web.1  |        4.9075001495357
dawarich_app        | 06:29:36 web.1  |       ]
dawarich_app        | 06:29:36 web.1  |    },
dawarich_app        | 06:29:36 web.1  |    "properties":{
dawarich_app        | 06:29:36 web.1  |       "api_key": "fc2a96ccb75e6c38abb97c31ba822c68",
dawarich_app        | 06:29:36 web.1  |       "timestamp": "2024-08-08T08:29:36.268005+02:00",
dawarich_app        | 06:29:36 web.1  |       "altitude": 380.66634149165316,
dawarich_app        | 06:29:36 web.1  |       "speed": 0.0,
dawarich_app        | 06:29:36 web.1  |       "horizontal_accuracy": 0,
dawarich_app        | 06:29:36 web.1  |       "vertical_accuracy": None,
dawarich_app        | 06:29:36 web.1  |       "significant_change": "unknown",
dawarich_app        | 06:29:36 web.1  |       "locations_in_payload": 1
dawarich_app        | 06:29:36 web.1  |    }
dawarich_app        | 06:29:36 web.1  |   }
```

**Reply by pmatis** [reply]
@Carunga, I'm not sure how the JSON was created but it's missing 2 closing brackets and the value of vertical_accuracy should be quoted if it's not numeric. I changed it to 0:

```
{
  "locations": [
  {
   "type": "Feature",
   "geometry":{
     "type": "Point",
     "coordinates":[
       57.701115750324459,
       4.9075001495357
      ]
   },
   "properties":{
      "api_key": "fc2a96ccb75e6c38abb97c31ba822c68",
      "timestamp": "2024-08-08T08:29:36.268005+02:00",
      "altitude": 380.66634149165316,
      "speed": 0.0,
      "horizontal_accuracy": 0,
      "vertical_accuracy": 0,
      "significant_change": "unknown",
      "locations_in_payload": 1
   }
  }
]
}
```

The above parsed properly.

**Reply by Carunga** [reply]
Wow thanks @pmatis ! It was the vertical accuracy without the quote. The closing brackets were just a copy paste error. It is working now very smoothley for days. I like it!

**Comment by Tazmanian79** [comment]
I didn't had time before but I just setup this link between HA and Dawarach and it's working fine.

I have only one thing.
In the log I have these entries: Push locatie Yves naar Dawarich: Already running

It's because sometimes the location is changed very often even when I hardly move.
Would it be possible to trigger the automation when the location change is bigger than for example 100 metres ?

**Reply by lspeltie** [reply]
You'd have write an automation to save previous location coordinates in a variable and compare euclidean distance to the current location, and push the location depending on that. Or you'd have to query the home assistant history database and compare it, [like this ](https://community.home-assistant.io/t/device-tracker-history/684963/3).  I'd recommend the previous location variable. but the speed it starts to register location would completely depend on your companion app update frequency if you do that.

**Comment by Carunga** [comment]
Working great for me as well. But one drawback I realized is that if you have no connection to your server (let's say your are hiking in a area without cell coverage or you are traveling without a mobil data plan for the country you are in) the locations data will be lost. This is sad as this might be some of the most interesting data. Any ideas for a workaround? I am aware this might be the intended behavior of  home assistant but maybe someone here has an idea for a workaround.

**Reply by lspeltie** [reply]
The Home assistant companion app doesn't seem to cache location history for devices that are offline to send to the server at a later time. My advice would be to use Overland, which says it does that exact thing.

**Comment by hockey6611** [comment]
Thank you to all here for helping integrate Home Assistant with Dawarich! I am testing this as a self-hosted replacement for Google Timeline. (it was nice of google to push me to another self-hosted alternative with their depreciation of Timeline 😀)

Building off of these comments (https://github.com/Freika/dawarich/discussions/77#discussioncomment-9904099 https://github.com/Freika/dawarich/discussions/77#discussioncomment-10065835), I iterated on these to be able use a single automation (utilizing `trigger_id` templates) and support multiple dawarich/home assistant users or devices. I wanted to share my configuration for others to use or improve!

configuration.yaml
```yaml
rest_command:
  dawarich_push_position_rest_command:
    url: https://sub.domain.tld/api/v1/overland/batches?api_key={{ api_key }}
    method: POST
    content_type: 'application/json'
    payload: >
      {
        "locations": [
        {
          "type": "Feature",
          "geometry":{
            "type": "Point",
            "coordinates":[
              {{ longitude }},
              {{ latitude }}
            ]
          },
          "properties":{
            "api_key": "{{ api_key }}",
            "timestamp": "{{ now().isoformat() }}",
            "altitude": {{ altitude }},
            "horizontal_accuracy": {{ horizontal_accuracy }},
            "vertical_accuracy": {{ vertical_accuracy }},
            "motion": [],
            "pauses": false,
            "locations_in_payload": 1,
            "device_id": "{{device_id}}"
          }
        }
        ]
      }
```

I created the automation in the HA GUI editor, but here is the yaml from the generated automations
````yaml
alias: dawarich location push
description: rest command diy integration
triggers:
  - entity_id:
      - device_tracker.user1_composite_device_tracker
    attribute: longitude
    trigger: state
    id: user1_location
  - entity_id:
      - device_tracker.user1_composite_device_tracker
    attribute: latitude
    trigger: state
    id: user1_location
  - entity_id:
      - device_tracker.user2_composite_device_tracker
    attribute: longitude
    trigger: state
    id: user2_location
  - entity_id:
      - device_tracker.user2_composite_device_tracker
    attribute: latitude
    trigger: state
    id: user2_location
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - user1_location
        sequence:
          - data:
              api_key: xxx
              latitude: "{{ state_attr(trigger.entity_id,'latitude') }}"
              longitude: "{{ state_attr(trigger.entity_id,'longitude') }}"
              altitude: >-
                {{
                state_attr(state_attr(trigger.entity_id,'last_entity_id'),'altitude')
                }}
              vertical_accuracy: >-
                {{
                state_attr(state_attr(trigger.entity_id,'last_entity_id'),'vertical_accuracy')
                }}
              horizontal_accuracy: >-
                {{
                state_attr(state_attr(trigger.entity_id,'last_entity_id'),'gps_accuracy')
                }}
              device_id: ha_user1_composite
            action: rest_command.dawarich_push_position_rest_command
      - conditions:
          - condition: trigger
            id:
              - user2_location
        sequence:
          - data:
              api_key: yyy
              latitude: "{{ state_attr(trigger.entity_id,'latitude') }}"
              longitude: "{{ state_attr(trigger.entity_id,'longitude') }}"
              altitude: >-
                {{
                state_attr(state_attr(trigger.entity_id,'last_entity_id'),'altitude')
                }}
              vertical_accuracy: >-
                {{
                state_attr(state_attr(trigger.entity_id,'last_entity_id'),'vertical_accuracy')
                }}
              horizontal_accuracy: >-
                {{
                state_attr(state_attr(trigger.entity_id,'last_entity_id'),'gps_accuracy')
                }}
              device_id: ha_user2_composite
            action: rest_command.dawarich_push_position_rest_command
mode: single

````

caveats:

- I use [ha-composite](https://github.com/pnbruckner/ha-composite-tracker) custom component to accommodate multiple devices for a single user. Not all attributes are the same between underlying devices (iOS vs android). This is why you see some nested `state_attr` templates. So modify as needed if you don't use ha-composite.
- dawarach is hosted on a separate host served via caddy https
- I removed some properties not applicable for me, which were included originally in the comments in this thread
- I wanted to store the `api_key` in the `!secrets` file for the automation, but it seems there are Home Assistant limitations preventing this, and I wasn't able to manage this. So the api key is just entered into the action.
- This could be further improved by implementing the automation `action` as a script with input fields. This would make the "integration" more extensible. I might take a stab at that down the road

**Reply by redge76** [reply]
`(it was nice of google to push me to another self-hosted alternative with their depreciation of Timeline 😀) `
Just had to switch to device storage based Timeline. Off course I hate it and now I'm here too :-D

**Comment by AlbinLind** [comment]
Thanks to all of the above suggestions I threw together a (very simple) custom Home Assistant integration. It can take a device tracker in HA, such as if you have installed the app, and then send the requests to your Dawarich server. It also displays your stats as sensors. 

It is still in the very early stages, and I don't have too much time to develop it, but if you want to try it it is available [here](https://github.com/AlbinLind/dawarich-home-assistant).

**Reply by bklaesener** [reply]
Thanks a lot for this, and I can confirm that 0.31 is working perfectly for me.

**Reply by BeastleeUK** [reply]
Big thanks from me too, this works really well for me.

**Comment by phobiac** [comment]
Note for version 0.21.0: Updated the files below to use the new Authorization header method of sending the api key. I've also done testing with both iOS and Android devices and refined the data collection script to work with both.

I wanted to set this up for myself and implemented it a bit differently, primarily because I have a multi-person household who will potentially use dawarich all getting data from Home Assistant so I wanted a more generically repeatable setup process. This was all done with the previous comments in mind so thank you everyone who made suggestions.

First off, for the REST command I ended up going with the owntracks endpoint as the docs listed it as being for individual data points vs batch points. It also looked a bit easier to set up. I included every bit of information that seemed potentially relevant though I'm not sure how much of this beyond the GPS location is actually used.

```
rest_command:
  push_position_to_dawarich:
    url: "http://YOURDAWARICHHOST/api/v1/owntracks/points"
    headers:
      authorization: "Bearer {{ api_key }}"
    method: POST
    content_type: "application/json"
    payload: '{"tst": {{ as_timestamp(now()) }},"_type": "location","lat": {{ latitude }},"lon": {{ longitude }},"acc": {{ gps_accuracy }},"alt": {{ altitude }},"vac": {{ vertical_accuracy }},"vel": {{ velocity }},"cog": {{ course }},"batt": {{ battery_level }},"bs": {{ battery_status }},"inregions": ["{{ zone }}"],"t": "u","SSID": "{{ wifi_ssid }}"}'
```
Instead of a single automation I went with a script. This script is set up with fields to make it easier to interact with. Notably, I have it configured to execute in queued mode with a limit of 100. I haven't had the opportunity to tune that but I set that mode and limit on the assumption that multiple automations could end up calling the script and we want them executed one at a time and in order.

For the entities to pick for your devices I went with what is given by the companion apps. If any of these don't work double check you have the sensor in question enabled in your companion app.

```
alias: Collect data for dawarich
fields:
  api_key:
    selector:
      text: null
    name: API Key
    description: API key from dawarich
    required: true
    default: keyhere
  device_name:
    name: Device Name
    description: Device to use for tracking
    required: true
    example: device_tracker.phone
    selector:
      entity:
        filter:
          domain: device_tracker
  device_battery_level:
    example: sensor.phone_battery_level
    selector:
      entity:
        filter:
          domain: sensor
    name: Device battery level
  device_battery_state:
    example: sensor.phone_battery_state
    selector:
      entity:
        filter:
          domain: sensor
    name: Device battery state
  device_wifi:
    example: sensor.phone_wifi_connection
    selector:
      entity:
        filter:
          domain: sensor
    name: Device Wifi
sequence:
  - action: rest_command.push_position_to_dawarich
    response_variable: dawarich_response
    metadata: {}
    data:
      api_key: "{{ api_key }}"
      latitude: "{{ state_attr(device_name,'latitude') }}"
      longitude: "{{ state_attr(device_name,'longitude') }}"
      gps_accuracy: "{{ state_attr(device_name,'gps_accuracy') }}"
      altitude: >-
        {{ iif(state_attr(device_name, 'altitude') is none, '0',
        state_attr(device_name, 'altitude')) }}
      vertical_accuracy: >-
        {{ iif(state_attr(device_name, 'vertical_accuracy') is none, '0',
        state_attr(device_name, 'vertical_accuracy')) }}
      device_id: "{{ device_name }}"
      battery_level: "{{ int(states(device_battery_level),1) / 100 }}"
      battery_status: >-
        {{ (states(device_battery_state)) | regex_replace(find='unknown',
        replace='0', ignorecase=true) | regex_replace(find='not_charging',
        replace='0', ignorecase=true) | regex_replace(find='not charging',
        replace='0', ignorecase=true) | regex_replace(find='discharging',
        replace='1', ignorecase=true) | regex_replace(find='charging',
        replace='2', ignorecase=true) | regex_replace(find='full', replace='3',
        ignorecase=true) }}
      zone: "{{ states(device_name) }}"
      velocity:   >-
        {{ iif(state_attr(device_name, 'speed') is none, '0',
        state_attr(device_name, 'speed')) }}
      course:  >-
        {{ iif(state_attr(device_name, 'course') is none, '0',
        state_attr(device_name, 'course')) }}
      wifi_ssid: "{{ iif(states(device_wifi) is none, 'NOWIFI', states(device_wifi)) }}"
description: ""
icon: mdi:crosshairs-question
mode: queued
max: 100
```
The automation is now very simple. Here's an example of an anonymized one using my phone.

```
alias: Send PERSON location data to dawarich
description: ""
triggers:
  - trigger: state
    entity_id:
      - device_tracker.personphone
    attribute: latitude
  - trigger: state
    entity_id:
      - device_tracker.personphone
    attribute: longitude
conditions: []
actions:
  - action: script.collect_data_for_dawarich
    metadata: {}
    data:
      api_key: "KEYHERE"
      device_name: device_tracker.personphone
      device_battery_level: sensor.personphone_battery_level
      device_battery_state: sensor.personphone_battery_state
      device_wifi: sensor.personphone_wifi_connection
mode: queued
max: 10
```
