### ISSUE TITLE
Container unhealthy reported during installation in 0.25.4

### ISSUE THREAD

**Issue by lonelypandaa** [Freika/dawarich#1015]
Hello. I have an issue during the installation of Dawarich. My machine is an Orange Pi 3b, running on Orange Pi 1.0.6 Jammy with Linux 5.10.160-rockchip-rk356, with a docker portal software called CasaOS

After running this command, it was initially able to download and extract some containers. 
After some time, it pops up an error message pops up, and the installation is terminated. 

It seems that the dawarich_redis and dawarich_db are fine. But not for the dawarich_app and dawarich_sidekiq. Both containers b8d5ecb16957 and 548c742a8e62, were reported unhealthy in separate installations. 

I tired to edit the docker-compose.yml according to the releases update of 0.25.4, but it does not help. 

```
orangepi@orangepi3b:~$ **docker-compose up**
dawarich_db is up-to-date
dawarich_redis is up-to-date

**ERROR**: for dawarich_app  Container "b8d5ecb16957" is unhealthy.
**ERROR**: Encountered errors while bringing up the project.
``` 

```
root@orangepi3b:/home/orangepi# docker-compose up
dawarich_redis is up-to-date
dawarich_db is up-to-date

ERROR: for dawarich_sidekiq  Container "548c742a8e62" is unhealthy.

ERROR: for dawarich_app  Container "548c742a8e62" is unhealthy.
ERROR: Encountered errors while bringing up the project.
``` 

Would you mind helping me to solve this issue. Thank you so much for your kind help.

**Comment by lonelypandaa** [comment]
For easier reading, I attached my docker-compose.yml file below. 

_I used the docker-compose.yml file that was directly copied from your github, originally. 
it poped up the following error. 
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.dawarich_sidekiq.environment.PROMETHEUS_EXPORTER_ENABLED contains false, which is an invalid type, it should be a string, number, or a null
services.dawarich_app.environment.PROMETHEUS_EXPORTER_ENABLED contains false, which is an invalid type, it should be a string, number, or a null
services.dawarich_sidekiq.depends_on contains unsupported option: 'restart'
services.dawarich_app.depends_on contains unsupported option: 'restart'_

As such, I edited the file with the aid of AI in the following 2 aspects. So it was a bit different from your file 

1. Boolean values in environment: Docker Compose requires environment variables to be strings, even if they represent boolean values. The values false and true need to be enclosed in quotes ("false" or "true").
2. Unsupported restart option in depends_on: The depends_on key does not support the restart option. The restart directive belongs to the service level, not within depends_on.



[docker-compose.yml.txt](https://github.com/user-attachments/files/19622033/docker-compose.yml.txt)

**Comment by lonelypandaa** [comment]
I tried to delete the latest version, or pull the version 0.25.3 by changing the docker-compose.yml. 
dawarich_db and dawarich_redis are fine and look running. 
However, the same issue is still reported, even when I delete and install 0.25.3 from scratch. 

```
orangepi@orangepi3b:~$ docker image ls
REPOSITORY                TAG             IMAGE ID       CREATED         SIZE
postgis/postgis           14-3.5-alpine   3cc8894c35cd   8 days ago      643MB
freikin/dawarich          0.25.3          fc247d2088dd   2 weeks ago     1.09GB
fallenbagel/jellyseerr    2.3.0           78fcdc57bdee   2 months ago    1.37GB
syncthing/syncthing       1.29            2e1356f25152   2 months ago    39.4MB
mauricenino/dashdot       5.9.0           a20a11ca3b63   6 months ago    212MB
redis                     7.0-alpine      755105238729   10 months ago   34.1MB
germannewsmaker/myspeed   1.0.9           819b05b33da5   10 months ago   186MB


orangepi@orangepi3b:~$ docker-compose down --volumes
docker-compose up --build
Stopping dawarich_db    ... done
Stopping dawarich_redis ... done
Removing dawarich_db    ... done
Removing dawarich_redis ... done
Removing network orangepi_dawarich
Removing volume orangepi_dawarich_db_data
Removing volume orangepi_dawarich_shared
Removing volume orangepi_dawarich_public
Removing volume orangepi_dawarich_watched
Removing volume orangepi_dawarich_storage
Creating network "orangepi_dawarich" with the default driver
Creating volume "orangepi_dawarich_db_data" with default driver
Creating volume "orangepi_dawarich_shared" with default driver
Creating volume "orangepi_dawarich_public" with default driver
Creating volume "orangepi_dawarich_watched" with default driver
Creating volume "orangepi_dawarich_storage" with default driver
Creating dawarich_db    ... done
Creating dawarich_redis ... done

ERROR: **for dawarich_app  Container "be8b7ec19706" is unhealthy**.
ERROR: Encountered errors while bringing up the project.

```

**Comment by Freika** [comment]
@lonelypandaa you can completely remove prometheus related env vars from your compose file and try again, it should probably fix it, based on logs you provided

@janexner can't say much without proper logs

**Comment by lonelypandaa** [comment]
@Freika , thank you for your help. 

I converted all the Prometheus-related env vars into comments and tried again. 

The same issue still exists. dawarich_sidekiq and dawarich_app cannot be installed due to an unhealthy container. Notably, different containers were reported as unhealthy in various attempts. 

I attached my docker-compose.yml file below. Different from your file on github, I modified it a bit, as it shouted "**ENABLE_TELEMETRY contains false, which is an invalid type, it should be a string, number, or a null**" and "**contains unsupported option: 'restart**'". I am not sure if this matters. 





```
orangepi@orangepi3b:~$ docker-compose down --volumes
Stopping dawarich_redis ... done
Stopping dawarich_db    ... done
Removing dawarich_redis ... done
Removing dawarich_db    ... done
Removing network orangepi_dawarich
Removing volume orangepi_dawarich_db_data
Removing volume orangepi_dawarich_shared
Removing volume orangepi_dawarich_public
Removing volume orangepi_dawarich_watched
Removing volume orangepi_dawarich_storage
orangepi@orangepi3b:~$ docker-compose up --build
Creating network "orangepi_dawarich" with the default driver
Creating volume "orangepi_dawarich_db_data" with default driver
Creating volume "orangepi_dawarich_shared" with default driver
Creating volume "orangepi_dawarich_public" with default driver
Creating volume "orangepi_dawarich_watched" with default driver
Creating volume "orangepi_dawarich_storage" with default driver
Creating dawarich_redis ... done
Creating dawarich_db    ... done

ERROR: for dawarich_sidekiq  Container "c7d1537ce286" is unhealthy.

ERROR: for dawarich_app  Container "c7d1537ce286" is unhealthy.
ERROR: Encountered errors while bringing up the project
``` 


The following is my compose-docker.yml file. 

```
networks:
  dawarich:
services:

dawarich_redis:
    image: redis:7.0-alpine
    container_name: dawarich_redis
    command: redis-server
    networks:
      - dawarich
    volumes:
      - dawarich_shared:/data
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  dawarich_db:
    # Changed the image here from postgres:14.2-alpine to postgis/postgis:14-3.5-alpine
    image: postgis/postgis:14-3.5-alpine
    shm_size: 1G
    container_name: dawarich_db
    volumes:
      - dawarich_db_data:/var/lib/postgresql/data
      - dawarich_shared:/var/shared
    networks:
      - dawarich
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d dawarich_development" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s  

  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    volumes:
      - dawarich_public:/var/app/public
      - dawarich_watched:/var/app/tmp/imports/watched
      - dawarich_storage:/var/app/storage
    networks:
      - dawarich
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    entrypoint: web-entrypoint.sh
    command: ['bin/rails', 'server', '-p', '3000', '-b', '::']
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      MIN_MINUTES_SPENT_IN_CITY: 60
      APPLICATION_HOSTS: localhost
      TIME_ZONE: Europe/London
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
   #   PROMETHEUS_EXPORTER_ENABLED: "false"
   #   PROMETHEUS_EXPORTER_HOST: 0.0.0.0
   #   PROMETHEUS_EXPORTER_PORT: 9394
      ENABLE_TELEMETRY: "false"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      #test: [ "CMD-SHELL", "wget -qO - http://127.0.0.1:3000/api/v1/health | grep -q '\"status\"\\s*:\\s*\"ok\"'" ]#
      test: [ "CMD-SHELL", "wget -qO - http://127.0.0.1:3000/api/v1/health | grep -q '\"status\"\\s*:\\s*\"ok\"'" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
      dawarich_redis:
        condition: service_healthy

  dawarich_sidekiq:
    image: freikin/dawarich:latest
    container_name: dawarich_sidekiq
    volumes:
      - dawarich_public:/var/app/public
      - dawarich_watched:/var/app/tmp/imports/watched
      - dawarich_storage:/var/app/storage
    networks:
      - dawarich
    stdin_open: true
    tty: true
    entrypoint: sidekiq-entrypoint.sh
    command: ['sidekiq']
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      APPLICATION_HOSTS: localhost
      BACKGROUND_PROCESSING_CONCURRENCY: 10
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
      #PROMETHEUS_EXPORTER_ENABLED: "false"
      #PROMETHEUS_EXPORTER_HOST: dawarich_app
     # PROMETHEUS_EXPORTER_PORT: 9394
      ENABLE_TELEMETRY: "false"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "bundle exec sidekiqmon processes | grep $${HOSTNAME}" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
      dawarich_redis:
        condition: service_healthy
      dawarich_app:
        condition: service_healthy

volumes:
  dawarich_db_data:
  dawarich_shared:
  dawarich_public:
  dawarich_watched:
  dawarich_storage:
```
