### ISSUE TITLE
Cannot login if I'm using HTTPS

### ISSUE THREAD

**Issue by ldellisola** [Freika/dawarich#106]
I am running the current version of Dawarich in my home server behind a Traefik reverse proxy.

I can access the login page without any problem but I cannot login if I'm using an HTTPS connection. If I use HTTP under the same reverse proxy, I can log in without any issues.

Here's the error:
<img width="1106" alt="Screenshot 2024-07-07 at 18 41 11" src="https://github.com/Freika/dawarich/assets/26941679/d7d22005-72b8-47ad-90c3-0e44f635f1ca">
(The hosts under the black boxes are identical)

This is my `docker-compose.yaml`:
```
networks:
  dawarich:
  web:
    name: "web"
    external: true

services:
  redis:
    image: redis:7.0-alpine
    command: redis-server
    restart: unless-stopped
    volumes:
      - ./redis:/var/shared/redis
    networks:
      - dawarich
  postgres:
    image: postgres:14.2-alpine
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ...
      POSTGRES_PASSWORD: ...
    networks:
      - dawarich
  app:
    image: freikin/dawarich:latest
    volumes:
      - ./app/gems:/usr/local/bundle/gems
      - ./app/public:/var/app/public
    stdin_open: true
    tty: true
    entrypoint: dev-entrypoint.sh
    command: ['bin/dev']
    restart: unless-stopped
    networks:
      - web
      - dawarich
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
      DATABASE_HOST: postgres
      DATABASE_USERNAME:...
      DATABASE_PASSWORD: ...
      DATABASE_NAME: dawarich
      MIN_MINUTES_SPENT_IN_CITY: 60
      APPLICATION_HOST: <MY-HOST>
      TIMEZONE: Europe/Oslo
    depends_on:
      - postgres
      - redis
    labels:
      traefik.enable: "true"
      traefik.http.routers.dawarich.rule: "Host(`<MY-HOST>`)"
      traefik.http.services.dawarich.loadbalancer.server.port: "3000"

  sidekiq:
    image: freikin/dawarich:latest
    volumes:
      - ./app/gems:/usr/local/bundle/gems
      - ./app/public:/var/app/public
    stdin_open: true
    tty: true
    entrypoint: dev-entrypoint.sh
    command: ['sidekiq']
    restart: unless-stopped
    networks:
      - dawarich
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
      DATABASE_HOST: postgres
      DATABASE_USERNAME: ...
      DATABASE_PASSWORD: ...
      DATABASE_NAME: dawarich
      APPLICATION_HOST: <MY-HOST>
      BACKGROUND_PROCESSING_CONCURRENCY: 10
    depends_on:
      - app
      - redis
      - postgres
```

**Comment by Freika** [comment]
Hi @ldellisola  You can try setting it in `APPLICATION_PROTOCOL` env var, it was implemented in 0.8.4 release: https://github.com/Freika/dawarich/releases/tag/0.8.4

**Comment by ldellisola** [comment]
Hey, When I set APPLICATION_PROTOCOL to https the site goes into an infinite redirect when I try to access the site:

![Screenshot 2024-07-09 at 07-11-39 Problem loading page](https://github.com/Freika/dawarich/assets/26941679/f48cd1ed-3daa-418b-ac8e-0e93e9a06059)

This happens not matter if I have https redirection enabled or disabled in my reverse proxy.

**Comment by Freika** [comment]
Unfortunately, I can't provide support with Traefik as I don't use it.

For Caddy, though, my configuration looks like this:

```
dawarich.myhost.com {
	reverse_proxy 192.168.0.1:3000
	tls {
		dns cloudflare CLOUDFLARE_API_KEY
	}
}
```

I'm accessing it using Tailscale + Cloudflare SSL certificates, I described my setup in details here: https://frey.today/homelab-with-tailscale-docker-caddy-ssl-cloudflare/

**Comment by ldellisola** [comment]
Weird. I'll look on my end then. Thanks anyway!

**Comment by larsrh** [comment]
@ldellisola Did you figure out what the problem was? I have the exact same issue here with Apache.

**Comment by larsrh** [comment]
After fiddling a little bit, I think I convinced the Rails container to believe it's being spoken to in HTTP, without causing the mismatch error above.

This is my `compose.override.yml`:

```yml
services:
  dawarich_app:
    ports: !override
      - 127.0.0.1:8001:3000
    environment:
      APPLICATION_HOST: example.org
      APPLICATION_HOSTS: localhost,example.org
  dawarich_sidekiq:
    environment:
      APPLICATION_HOST: example.org
      APPLICATION_HOSTS: localhost,example.org
```

This is my Apache config:

```
<IfModule mod_ssl.c>
<VirtualHost *:443>
    ServerAdmin test@example.org
    ServerName example.org

    # this causes Apache to strip out the Origin header which I believe confuses Rails
    ProxyRequests Off
    ProxyAddHeaders Off
    RequestHeader unset Origin
    # this is necessary because otherwise all the links I get are `http://localhost:8001/...`
    RequestHeader set X-Forwarded-Host example.org

    # config as suggested by the Wiki
    SetOutputFilter BROTLI
    AddOutputFilterByType BROTLI_COMPRESS text/css text/plain text/xml text/javascript application/javascript application/json application/manifest+json application/vnd.api+json application/xml application/xhtml+xml application/rss+xml application/atom+xml application/vnd.ms-fontobject application/x-font-ttf application/x-font-opentype application/x-font-truetype image/svg+xml image/x-icon image/vnd.microsoft.icon font/ttf font/eot font/otf font/opentype
    BrotliCompressionQuality 6
        
    ProxyPass / http://127.0.0.1:8001/
    ProxyPassReverse / http://127.0.0.1:8001/

    # more SSL config ...
</VirtualHost>
</IfModule>
```
