### ISSUE TITLE
installation fails - "RAILS_MASTER_KEY" variable is not set

### ISSUE THREAD

**Issue by Pr3mut05** [Freika/dawarich#1076]
**OS & Hardware**
Linux Debian Docker

**Version**
0.25.5

Hallo,

after the command _docker compose up -d_ the message

```
WARN[0000] The "RAILS_MASTER_KEY" variable is not set. Defaulting to a blank string. 
WARN[0000] The "RAILS_MASTER_KEY" variable is not set. Defaulting to a blank string.
```
_Container dawarich_app_ fails with 

`dependency failed to start: container dawarich_app is unhealthy`

**Comment by mcbrineellis** [comment]
I am also getting this issue.  I tried adding the var using a .env file and it seems to make no difference, all I see in the logs is:

```
~/docker-compose$ docker logs d196151a0498 -f
⚠️ Starting Rails environment: development ⚠️
⏳ Waiting for database to be ready...
psql: error: connection to server at "dawarich_db" (172.25.0.3), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
Postgres is unavailable - retrying...
psql: error: connection to server at "dawarich_db" (172.25.0.3), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
Postgres is unavailable - retrying...
psql: error: connection to server at "dawarich_db" (172.25.0.3), port 5432 failed: FATAL:  database "dawarich_development" does not exist
Postgres is unavailable - retrying...
psql: error: connection to server at "dawarich_db" (172.25.0.3), port 5432 failed: FATAL:  database "dawarich_development" does not exist
Postgres is unavailable - retrying...
psql: error: connection to server at "dawarich_db" (172.25.0.3), port 5432 failed: FATAL:  database "dawarich_development" does not exist
Postgres is unavailable - retrying...
psql: error: connection to server at "dawarich_db" (172.25.0.3), port 5432 failed: FATAL:  database "dawarich_development" does not exist
Postgres is unavailable - retrying...
psql: error: connection to server at "dawarich_db" (172.25.0.3), port 5432 failed: FATAL:  database "dawarich_development" does not exist
```

**Comment by sampotato-dev** [comment]
I am getting the same. It seems that the database "dawarich_development" does not exist on the DB container. 

```
rver to start....2025-04-20 04:38:42.337 UTC [78] LOG:  starting PostgreSQL 14.17 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
dawarich_db     | 2025-04-20 04:38:42.479 UTC [78] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
dawarich_db     | 2025-04-20 04:38:42.684 UTC [79] LOG:  database system was shut down at 2025-04-20 04:38:11 UTC
dawarich_db     | 2025-04-20 04:38:42.776 UTC [78] LOG:  database system is ready to accept connections
dawarich_db     |  done
dawarich_db     | server started
dawarich_db     | 
dawarich_db     | /usr/local/bin/docker-entrypoint.sh: sourcing /docker-entrypoint-initdb.d/10_postgis.sh
dawarich_db     | 2025-04-20 04:38:43.653 UTC [97] FATAL:  database "dawarich_development" does not exist
dawarich_db     | 2025-04-20 04:38:53.698 UTC [104] FATAL:  database "dawarich_development" does not exist
dawarich_db     | 2025-04-20 04:39:03.738 UTC [111] FATAL:  database "dawarich_development" does not exist
dawarich_db     | CREATE DATABASE
dawarich_db     | Loading PostGIS extensions into template_postgis
dawarich_db     | CREATE EXTENSION
dawarich_db     | CREATE EXTENSION
dawarich_db     | You are now connected to database "template_postgis" as user "postgres".
dawarich_db     | CREATE EXTENSION
dawarich_db     | 2025-04-20 04:39:13.777 UTC [122] FATAL:  database "dawarich_development" does not exist
dawarich_db     | CREATE EXTENSION
dawarich_db     | Loading PostGIS extensions into postgres
dawarich_db     | CREATE EXTENSION
dawarich_db     | 2025-04-20 04:39:23.818 UTC [131] FATAL:  database "dawarich_development" does not exist
dawarich_db     | CREATE EXTENSION
dawarich_db     | You are now connected to database "postgres" as user "postgres".
dawarich_db     | CREATE EXTENSION
dawarich_db     | CREATE EXTENSION
dawarich_db     | 
dawarich_db     | waiting for server to shut down...2025-04-20 04:39:30.248 UTC [78] LOG:  received fast shutdown request
dawarich_db     | .2025-04-20 04:39:30.382 UTC [78] LOG:  aborting any active transactions
dawarich_db     | 2025-04-20 04:39:30.386 UTC [78] LOG:  background worker "logical replication launcher" (PID 85) exited with exit code 1
dawarich_db     | 2025-04-20 04:39:30.387 UTC [80] LOG:  shutting down
dawarich_db     | ...2025-04-20 04:39:33.889 UTC [140] FATAL:  the database system is shutting down
dawarich_db     | 2025-04-20 04:39:33.985 UTC [78] LOG:  database system is shut down
dawarich_db     |  done
dawarich_db     | server stopped
dawarich_db     | 
dawarich_db     | PostgreSQL init process complete; ready for start up.
dawarich_db     | 
dawarich_db     | 2025-04-20 04:39:34.047 UTC [1] LOG:  starting PostgreSQL 14.17 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
dawarich_db     | 2025-04-20 04:39:34.047 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
dawarich_db     | 2025-04-20 04:39:34.047 UTC [1] LOG:  listening on IPv6 address "::", port 5432
dawarich_db     | 2025-04-20 04:39:34.190 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
dawarich_db     | 2025-04-20 04:39:34.218 UTC [142] LOG:  database system was shut down at 2025-04-20 04:39:33 UTC
dawarich_db     | 2025-04-20 04:39:34.233 UTC [1] LOG:  database system is ready to accept connections
dawarich_db     | 2025-04-20 04:39:34.511 UTC [149] FATAL:  database "dawarich_development" does not exist
dawarich_db     | 2025-04-20 04:39:36.525 UTC [150] FATAL:  database "dawarich_development" does not exist
dawarich_db     | 2025-04-20 04:39:38.540 UTC [151] FATAL:  database "dawarich_development" does not exist
dawarich_db     | 2025-04-20 04:39:40.555 UTC [152] FATAL:  database "dawarich_development" does not exist
dawarich_db     | 2025-04-20 04:39:42.571 UTC [153] FATAL:  database "dawarich_development" does not exist
dawarich_db     | 2025-04-20 04:39:43.926 UTC [160] FATAL:  database "dawarich_development" does not exist
dawarich_db     | 2025-04-20 04:39:44.585 UTC [161] FATAL:  database "dawarich_development" does not exist
dawarich_db     | 2025-04-20 04:39:46.600 UTC [162] FATAL:  database "dawarich_development" does not exist
dawarich_db     | 2025-04-20 04:39:48.615 UTC [163] FATAL:  database "dawarich_development" does not exist
dawarich_db     | 2025-04-20 04:39:50.630 UTC [164] FATAL:  database "dawarich_development" does not exist
dawarich_db     | 2025-04-20 04:39:52.645 UTC [165] FATAL:  database "dawarich_development" does not exist
dawarich_db     | 2025-04-20 04:39:53.960 UTC [172] FATAL:  database "dawarich_development" does not exist
dawarich_db     | 2025-04-20 04:39:54.660 UTC [173] FATAL:  database "dawarich_development" does not exist
dawarich_db     | 2025-04-20 04:39:56.691 UTC [174] FATAL:  database "dawarich_development" does not exist
dawarich_db     | 2025-04-20 04:39:58.733 UTC [175] FATAL:  database "dawarich_development" does not exist
dawarich_db     | 2025-04-20 04:40:00.751 UTC [176] FATAL:  database "dawarich_development" does not exist
dawarich_app    | psql: error: connection to server at "dawarich_db" (172.18.0.3), port 5432 failed: FATAL:  database "dawarich_development" does not exist
dawarich_app    | Postgres is unavailable - retrying...
dawarich_db     | 2025-04-20 04:40:02.772 UTC [177] FATAL:  database "dawarich_development" does not exist
```

**Comment by sampotato-dev** [comment]
Attempting to work around issue; 
changed database name to "postgres" (default postgres database name). 
application able to start, can visit web interface. 
dawarich_sidekiq container still not running, has never run after being created, no logs. any ideas? 
can start container manually after other containers have started, no issues. 

![Image](https://github.com/user-attachments/assets/e72dba22-7726-4adb-b00a-6e26095a9dc1)

Log
```
WARN[0000] The "RAILS_MASTER_KEY" variable is not set. Defaulting to a blank string. 
WARN[0000] The "RAILS_MASTER_KEY" variable is not set. Defaulting to a blank string. 
dawarich_app    | ⚠️ Starting Rails environment: development ⚠️
dawarich_app    | ⏳ Waiting for database to be ready...
dawarich_app    | ✅ PostgreSQL is ready!
dawarich_app    | PostgreSQL is ready. Running database migrations...
dawarich_app    | [dotenv] Set DATABASE_PORT
dawarich_app    | [dotenv] Loaded .env.development
dawarich_app    | D, [2025-04-20T07:35:57.463159 #10] DEBUG -- :    (0.4ms)  SELECT pg_try_advisory_lock(737815420147457505)
dawarich_app    | D, [2025-04-20T07:35:57.474295 #10] DEBUG -- :   ActiveRecord::SchemaMigration Load (2.9ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
dawarich_app    | D, [2025-04-20T07:35:57.555347 #10] DEBUG -- :   ActiveRecord::InternalMetadata Load (2.4ms)  SELECT * FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 ORDER BY "ar_internal_metadata"."key" ASC LIMIT 1  [[nil, "environment"]]
dawarich_app    | D, [2025-04-20T07:35:57.556885 #10] DEBUG -- :    (0.3ms)  SELECT pg_advisory_unlock(737815420147457505)
dawarich_app    | D, [2025-04-20T07:35:57.559646 #10] DEBUG -- :   ActiveRecord::SchemaMigration Load (0.2ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
dawarich_app    | D, [2025-04-20T07:35:57.795871 #10] DEBUG -- :    (25.6ms)  SELECT f_geometry_column,coord_dimension,srid,type FROM geometry_columns WHERE f_table_name='addrfeat'
dawarich_app    | D, [2025-04-20T07:35:57.895394 #10] DEBUG -- :    (7.9ms)  SELECT f_geometry_column,coord_dimension,srid,type FROM geometry_columns WHERE f_table_name='bg'
dawarich_app    | D, [2025-04-20T07:35:57.914267 #10] DEBUG -- :    (3.6ms)  SELECT f_geometry_column,coord_dimension,srid,type FROM geometry_columns WHERE f_table_name='county'
dawarich_app    | D, [2025-04-20T07:35:58.048795 #10] DEBUG -- :    (3.5ms)  SELECT f_geometry_column,coord_dimension,srid,type FROM geometry_columns WHERE f_table_name='cousub'
dawarich_app    | D, [2025-04-20T07:35:58.207802 #10] DEBUG -- :    (3.4ms)  SELECT f_geometry_column,coord_dimension,srid,type FROM geometry_columns WHERE f_table_name='edges'
dawarich_app    | D, [2025-04-20T07:35:58.268482 #10] DEBUG -- :    (3.4ms)  SELECT f_geometry_column,coord_dimension,srid,type FROM geometry_columns WHERE f_table_name='faces'
dawarich_app    | D, [2025-04-20T07:35:58.435382 #10] DEBUG -- :    (3.7ms)  SELECT f_geometry_column,coord_dimension,srid,type FROM geometry_columns WHERE f_table_name='place'
dawarich_app    | D, [2025-04-20T07:35:58.584756 #10] DEBUG -- :    (3.4ms)  SELECT f_geometry_column,coord_dimension,srid,type FROM geometry_columns WHERE f_table_name='state'
dawarich_app    | D, [2025-04-20T07:35:58.641615 #10] DEBUG -- :    (3.9ms)  SELECT f_geometry_column,coord_dimension,srid,type FROM geometry_columns WHERE f_table_name='tabblock'
dawarich_app    | D, [2025-04-20T07:35:58.674228 #10] DEBUG -- :    (2.6ms)  SELECT f_geometry_column,coord_dimension,srid,type FROM geometry_columns WHERE f_table_name='tract'
dawarich_app    | D, [2025-04-20T07:35:58.726080 #10] DEBUG -- :    (3.2ms)  SELECT f_geometry_column,coord_dimension,srid,type FROM geometry_columns WHERE f_table_name='zcta5'
dawarich_app    | Running DATA migrations...
dawarich_app    | [dotenv] Set DATABASE_PORT
dawarich_app    | [dotenv] Loaded .env.development
dawarich_app    | D, [2025-04-20T07:36:02.345770 #42] DEBUG -- :    (0.9ms)  SELECT pg_try_advisory_lock(737815420147457505)
dawarich_app    | D, [2025-04-20T07:36:02.355772 #42] DEBUG -- :   DataMigrate::DataSchemaMigration Load (2.6ms)  SELECT "data_migrations"."version" FROM "data_migrations" ORDER BY "data_migrations"."version" ASC
dawarich_app    | D, [2025-04-20T07:36:02.374951 #42] DEBUG -- :   ActiveRecord::InternalMetadata Load (2.7ms)  SELECT * FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 ORDER BY "ar_internal_metadata"."key" ASC LIMIT 1  [[nil, "environment"]]
dawarich_redis  | 1:C 20 Apr 2025 07:26:07.836 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
dawarich_redis  | 1:C 20 Apr 2025 07:26:07.836 # Redis version=7.0.15, bits=64, commit=00000000, modified=0, pid=1, just started
dawarich_redis  | 1:C 20 Apr 2025 07:26:07.836 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
dawarich_redis  | 1:M 20 Apr 2025 07:26:07.836 * monotonic clock: POSIX clock_gettime
dawarich_redis  | 1:M 20 Apr 2025 07:26:07.837 * Running mode=standalone, port=6379.
dawarich_redis  | 1:M 20 Apr 2025 07:26:07.837 # Server initialized
dawarich_redis  | 1:M 20 Apr 2025 07:26:07.837 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
dawarich_app    | D, [2025-04-20T07:36:02.376459 #42] DEBUG -- :    (0.3ms)  SELECT pg_advisory_unlock(737815420147457505)
dawarich_app    | D, [2025-04-20T07:36:02.377717 #42] DEBUG -- :   DataMigrate::DataSchemaMigration Load (0.3ms)  SELECT "data_migrations"."version" FROM "data_migrations" ORDER BY "data_migrations"."version" ASC
dawarich_app    | Running seeds...
dawarich_app    | [dotenv] Set DATABASE_PORT
dawarich_app    | [dotenv] Loaded .env.development
dawarich_app    | D, [2025-04-20T07:36:06.745156 #57] DEBUG -- :   ActiveRecord::SchemaMigration Load (26.9ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
dawarich_app    | D, [2025-04-20T07:36:06.956224 #57] DEBUG -- :   User Exists? (2.4ms)  SELECT 1 AS one FROM "users" LIMIT $1  [["LIMIT", 1]]
dawarich_redis  | 1:M 20 Apr 2025 07:26:07.837 * Loading RDB produced by version 7.0.15
dawarich_redis  | 1:M 20 Apr 2025 07:26:07.837 * RDB age 79 seconds
dawarich_redis  | 1:M 20 Apr 2025 07:26:07.837 * RDB memory usage when created 0.85 Mb
dawarich_redis  | 1:M 20 Apr 2025 07:26:07.837 * Done loading RDB, keys loaded: 1, keys expired: 0.
dawarich_redis  | 1:M 20 Apr 2025 07:26:07.837 * DB loaded from disk: 0.000 seconds
dawarich_redis  | 1:M 20 Apr 2025 07:26:07.837 * Ready to accept connections
dawarich_db     | 
dawarich_db     | PostgreSQL Database directory appears to contain a database; Skipping initialization
dawarich_db     | 
dawarich_db     | 2025-04-20 07:35:39.127 UTC [1] LOG:  starting PostgreSQL 14.17 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
dawarich_db     | 2025-04-20 07:35:39.127 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
dawarich_db     | 2025-04-20 07:35:39.127 UTC [1] LOG:  listening on IPv6 address "::", port 5432
dawarich_db     | 2025-04-20 07:35:39.213 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
dawarich_db     | 2025-04-20 07:35:39.222 UTC [27] LOG:  database system was shut down at 2025-04-20 07:35:20 UTC
dawarich_db     | 2025-04-20 07:35:39.231 UTC [1] LOG:  database system is ready to accept connections
dawarich_app    | => Booting Puma
dawarich_app    | => Rails 8.0.1 application starting in development 
dawarich_app    | => Run `bin/rails server --help` for more startup options
dawarich_app    | [dotenv] Set DATABASE_PORT
dawarich_app    | [dotenv] Loaded .env.development
dawarich_app    | [81] Puma starting in cluster mode...
dawarich_app    | [81] * Puma version: 6.6.0 ("Return to Forever")
dawarich_app    | [81] * Ruby version: ruby 3.4.1 (2024-12-25 revision 48d4efcb85) +YJIT +PRISM [x86_64-linux-musl]
dawarich_app    | [81] *  Min threads: 5
dawarich_app    | [81] *  Max threads: 5
dawarich_app    | [81] *  Environment: development
dawarich_app    | [81] *   Master PID: 81
dawarich_app    | [81] *      Workers: 2
dawarich_app    | [81] *     Restarts: (✔) hot (✖) phased
dawarich_app    | [81] * Preloading application
dawarich_app    | [81] * Listening on http://[::]:3000
dawarich_app    | [81] Use Ctrl-C to stop
dawarich_app    | [81] - Worker 0 (PID: 103) booted in 0.0s, phase: 0
dawarich_app    | [81] - Worker 1 (PID: 113) booted in 0.0s, phase: 0
dawarich_app    | D, [2025-04-20T07:36:13.570462 #103] DEBUG -- :   ActiveRecord::SchemaMigration Load (23.1ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
dawarich_app    | D, [2025-04-20T07:36:14.806835 #103] DEBUG -- :   User Load (2.6ms)  SELECT "users".* FROM "users" WHERE "users"."api_key" IS NULL LIMIT $1  [["LIMIT", 1]]
dawarich_app    | D, [2025-04-20T07:36:14.851276 #103] DEBUG -- :   ↳ app/controllers/api_controller.rb:22:in 'ApiController#current_api_user'
dawarich_app    | I, [2025-04-20T07:36:14.859657 #103]  INFO -- : {"method":"GET","path":"/api/v1/health","format":"*/*","controller":"Api::V1::HealthController","action":"index","status":200,"allocations":10053,"duration":192.78,"view":0.26,"db":23.99}
dawarich_app    | D, [2025-04-20T07:36:25.561135 #113] DEBUG -- :   ActiveRecord::SchemaMigration Load (58.7ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
dawarich_app    | D, [2025-04-20T07:36:26.802782 #113] DEBUG -- :   User Load (2.0ms)  SELECT "users".* FROM "users" WHERE "users"."api_key" IS NULL LIMIT $1  [["LIMIT", 1]]
dawarich_app    | D, [2025-04-20T07:36:26.811937 #113] DEBUG -- :   ↳ app/controllers/api_controller.rb:22:in 'ApiController#current_api_user'
dawarich_app    | I, [2025-04-20T07:36:26.845206 #113]  INFO -- : {"method":"GET","path":"/api/v1/health","format":"*/*","controller":"Api::V1::HealthController","action":"index","status":200,"allocations":9105,"duration":154.67,"view":0.32,"db":17.75}
``` 


docker-compose file, modified lines in bold

```
networks:
  dawarich:
services:
  dawarich_redis:
    image: redis:7.0-alpine
    container_name: dawarich_redis
    command: redis-server
    networks:
      - dawarich
    volumes:
      - /mnt/user/appdata/visited_locations/dawarich_shared:/data
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  dawarich_db:
    image: postgis/postgis:14-3.5-alpine
    shm_size: 1G
    container_name: dawarich_db
    volumes:
      - /mnt/user/appdata/visited_locations/dawarich_db_data:/var/lib/postgresql/data
      - /mnt/user/appdata/visited_locations/dawarich_shared:/var/shared
      # - ./postgresql.conf:/etc/postgresql/postgresql.conf # Optional, uncomment if you want to use a custom config
    networks:
      - dawarich
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      **POSTGRES_DB: postgres**
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    # command: postgres -c config_file=/etc/postgresql/postgresql.conf # Use custom config, uncomment if you want to use a custom config
  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    volumes:
      - /mnt/user/appdata/visited_locations/dawarich_public:/var/app/public
      - /mnt/user/appdata/visited_locations/dawarich_watched:/var/app/tmp/imports/watched
      - /mnt/user/appdata/visited_locations/dawarich_storage:/var/app/storage
    networks:
      - dawarich
    ports:
      - 3000:3000
      # - 9394:9394 # Prometheus exporter, uncomment if needed
    stdin_open: true
    tty: true
    entrypoint: web-entrypoint.sh
    command: ['bin/rails', 'server', '-p', '3000', '-b', '::']
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      #DATABASE_NAME: dawarich_development
      **DATABASE_NAME: postgres**
      MIN_MINUTES_SPENT_IN_CITY: 60
      APPLICATION_HOSTS: localhost,192.168.200.49
      TIME_ZONE: Australia/Melbourne
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: 0.0.0.0
      PROMETHEUS_EXPORTER_PORT: 9394
      SELF_HOSTED: "true"
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO - http://127.0.0.1:3000/api/v1/health | grep -q '\"status\"\\s*:\\s*\"ok\"'" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
      dawarich_redis:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '0.50'    # Limit CPU usage to 50% of one core
          memory: '4G'    # Limit memory usage to 4GB
  dawarich_sidekiq:
    image: freikin/dawarich:latest
    container_name: dawarich_sidekiq
    volumes:
      - /mnt/user/appdata/visited_locations/dawarich_public:/var/app/public
      - /mnt/user/appdata/visited_locations/dawarich_watched:/var/app/tmp/imports/watched
      - /mnt/user/appdata/visited_locations/dawarich_storage:/var/app/storage
    networks:
      - dawarich
    stdin_open: true
    tty: true
    entrypoint: sidekiq-entrypoint.sh
    command: ['sidekiq']
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      #DATABASE_NAME: dawarich_development
      **DATABASE_NAME: postgres**
      APPLICATION_HOSTS: localhost
      BACKGROUND_PROCESSING_CONCURRENCY: 10
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: dawarich_app
      PROMETHEUS_EXPORTER_PORT: 9394
      SELF_HOSTED: "true"
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "bundle exec sidekiqmon processes | grep $${HOSTNAME}" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
      dawarich_redis:
        condition: service_healthy
        restart: true
      dawarich_app:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '0.50'    # Limit CPU usage to 50% of one core
          memory: '4G'    # Limit memory usage to 4GB

volumes:
  dawarich_db_data:
  dawarich_shared:
  dawarich_public:
  dawarich_watched:
  dawarich_storage:
```
