### ISSUE TITLE
Server error 500 in App

### ISSUE THREAD

**Issue by runzl0r** [Freika/dawarich#1170]
**OS & Hardware**
ios 18, latest app,

**Version**
Dawarich 0.26, updated DB to 17

**Describe the bug**
I get error message 500 in the app when I want to upload data points. Currently there are 6000 in Backlog.

**Logs**
Error in dawarich app, sidekiq looks fine:

```
{"device_id":"E909E2F3-99DB-4337-A30A-D71151CCDDD4","track_id":"C8223696-E337-4DC7-B2CA-1098BC9EB60B","speed":24.03582692754816,"course":309.518310546875,"vertical_accuracy":3,"horizontal_accuracy":1.9999999939882136,"course_accuracy":12.731480016974817,"speed_accuracy":0.4002491301420852,"timestamp":"2025-05-06T06:09:20Z","altitude":317.58213164657354}}', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT ("lonlat","timestamp","user_id") DO UPDATE SET updated_at=(CASE WHEN ("points"."battery_status" IS NOT DISTINCT FROM excluded."battery_status" AND "points"."battery" IS NOT DISTINCT FROM excluded."battery" AND "points"."altitude" IS NOT DISTINCT FROM excluded."altitude" AND "points"."tracker_id" IS NOT DISTINCT FROM excluded."tracker_id" AND "points"."velocity" IS NOT DISTINCT FROM excluded."velocity" AND "points"."ssid" IS NOT DISTINCT FROM excluded."ssid" AND "points"."accuracy" IS NOT DISTINCT FROM excluded."accuracy" AND "points"."vertical_accuracy" IS NOT DISTINCT FROM excluded."vertical_accuracy" AND "points"."course_accuracy" IS NOT DISTINCT FROM excluded."course_accuracy" AND "points"."course" IS NOT DISTINCT FROM excluded."course" AND "points"."raw_data" IS NOT DISTINCT FROM excluded."raw_data") THEN "points".updated_at ELSE CURRENT_TIMESTAMP END),"battery_status"=excluded."battery_status","battery"=excluded."battery","altitude"=excluded."altitude","tracker_id"=excluded."tracker_id","velocity"=excluded."velocity","ssid"=excluded."ssid","accuracy"=excluded."accuracy","vertical_accuracy"=excluded."vertical_accuracy","course_accuracy"=excluded."course_accuracy","course"=excluded."course","raw_data"=excluded."raw_data" RETURNING id, timestamp, ST_X(lonlat::geometry) AS longitude, ST_Y(lonlat::geometry) AS latitude
D, [2025-05-12T09:37:55.679195 #121] DEBUG -- :   ↳ app/services/points/create.rb:18:in 'block in Points::Create#call'
I, [2025-05-12T09:37:55.679417 #121]  INFO -- : {"method":"POST","path":"/api/v1/points","format":"*/*","controller":"Api::V1::PointsController","action":"create","status":500,"allocations":1535491,"duration":2128.28,"view":0.0,"db":31.07,"unpermitted_params":["point"]}
E, [2025-05-12T09:37:55.680846 #121] ERROR -- :   
ActiveRecord::StatementInvalid (PG::CardinalityViolation: ERROR:  ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
)
Caused by: PG::CardinalityViolation (ERROR:  ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
)

Information for: ActiveRecord::StatementInvalid (PG::CardinalityViolation: ERROR:  ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
):
  

Information for cause: PG::CardinalityViolation (ERROR:  ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
):
  
app/services/points/create.rb:18:in 'block in Points::Create#call'
app/services/points/create.rb:16:in 'Array#each'
app/services/points/create.rb:16:in 'Enumerable#each_slice'
app/services/points/create.rb:16:in 'Points::Create#call'
app/controllers/api/v1/points_controller.rb:27:in 'Api::V1::PointsController#create'
```

**Additional context**
Looks like there are two datapoints at the same time?

**Comment by jikee-h** [comment]
I have the same issue (see my traces below) 
```
dawarich_app      | D, [2025-05-14T13:54:56.522684 #126] DEBUG -- :   ↳ app/services/points/create.rb:18:in 'block in Points::Create#call'
dawarich_app      | I, [2025-05-14T13:54:56.522915 #126]  INFO -- : {"method":"POST","path":"/api/v1/points","format":"*/*","controller":"Api::V1::PointsController","action":"create","status":500,"allocations":134996,"duration":143.63,"view":0.0,"db":13.78,"unpermitted_params":["point"]}
dawarich_app      | E, [2025-05-14T13:54:56.525689 #126] ERROR -- :
dawarich_app      | ActiveRecord::StatementInvalid (PG::CardinalityViolation: ERROR:  ON CONFLICT DO UPDATE command cannot affect row a second time
dawarich_app      | HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
dawarich_app      | )
dawarich_app      | Caused by: PG::CardinalityViolation (ERROR:  ON CONFLICT DO UPDATE command cannot affect row a second time
dawarich_app      | HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
dawarich_app      | )
dawarich_app      |
dawarich_app      | Information for: ActiveRecord::StatementInvalid (PG::CardinalityViolation: ERROR:  ON CONFLICT DO UPDATE command cannot affect row a second time
dawarich_app      | HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
dawarich_app      | ):
dawarich_app      |
dawarich_app      |
dawarich_app      | Information for cause: PG::CardinalityViolation (ERROR:  ON CONFLICT DO UPDATE command cannot affect row a second time
dawarich_app      | HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
dawarich_app      | ):
dawarich_app      |
dawarich_app      | app/services/points/create.rb:18:in 'block in Points::Create#call'
dawarich_app      | app/services/points/create.rb:16:in 'Array#each'
dawarich_app      | app/services/points/create.rb:16:in 'Enumerable#each_slice'
dawarich_app      | app/services/points/create.rb:16:in 'Points::Create#call'
dawarich_app      | app/controllers/api/v1/points_controller.rb:27:in 'Api::V1::PointsController#create'
```

**Comment by jikee-h** [comment]
Hello, 
Wanted to say that with upgrade to 0.26.1-rc, the problem disappeared. 

So great to see it is already fixed, and looking forward to an official release when it is ready :)

**Comment by Freika** [comment]
The fix will be released in stable version of 0.26.1 and already available in 0.26.1-rc, as @jikee-h mentioned

**Comment by joerghohn** [comment]
As you can see in screenshot i can not see the error 500 in the app, just Error.
Nevernetheless thank you for your quick response. 
I will try to update later

**Comment by Freika** [comment]
@joerghohn no worries, as you said, there is no way you could know it's a duplicate :) Just closed it for my own convenience

**Comment by Freika** [comment]
Done in 0.26.1

**Comment by runzl0r** [comment]
Happened again today after the new app release.

**Comment by Freika** [comment]
@runzl0r can you provide error log?

**Comment by runzl0r** [comment]
This is my docker-compose, I think the error is somewhere here, since the database does not start.
```
networks:
  dawarich:
services:
  dawarich_db:
    image: postgis/postgis:17-3.5-alpine
    shm_size: 1G
    container_name: dawarich_db
    volumes:
      - dawarich_db_data_pg_17:/var/lib/postgresql/data
      - dawarich_shared:/var/shared
      # - ./postgresql.conf:/etc/postgresql/postgresql.conf # Optional, uncomment if you want to use a custom config
    networks:
      - dawarich
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dawarich_development
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d dawarich_development" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    # command: postgres -c config_file=/etc/postgresql/postgresql.conf # Use custom config, uncomment if you want to use a custom config
  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    volumes:
      - dawarich_public:/var/app/public
      - dawarich_watched:/var/app/tmp/imports/watched
      - dawarich_storage:/var/app/storage
#      - dawarich_db_data:/dawarich_db_data
      - dawarich_db_data_pg_17:/var/lib/postgresql/data
      - dawarich_shared:/var/shared
    networks:
      - dawarich
    ports:
      - 3001:3000
      # - 9394:9394 # Prometheus exporter, uncomment if needed
    stdin_open: true
    tty: true
    entrypoint: web-entrypoint.sh
    command: ['bin/rails', 'server', '-p', '3000', '-b', '::']
   restart: on-failure
    environment:
      RAILS_ENV: development
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      # SQLite database paths for secondary databases
      QUEUE_DATABASE_PATH: /dawarich_db_data/dawarich_development_queue.sqlite3
      CACHE_DATABASE_PATH: /dawarich_db_data/dawarich_development_cache.sqlite3
      CABLE_DATABASE_PATH: /dawarich_db_data/dawarich_development_cable.sqlite3
      MIN_MINUTES_SPENT_IN_CITY: 60
      APPLICATION_HOSTS: localhost
      TIME_ZONE: Europe/London
      APPLICATION_PROTOCOL: http
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: 0.0.0.0
      PROMETHEUS_EXPORTER_PORT: 9394
      SELF_HOSTED: "true"
      STORE_GEODATA: "true"
      PHOTON_API_HOST: photon.donsomhong.net
      PHOTON_API_USE_HTTPS: true

    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO - http://127.0.0.1:3000/api/v1/health | grep -q '\"status\"\\s*:\\s*\"ok\"'" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '1'    # Limit CPU usage to 50% of one core
          memory: '4G'    # Limit memory usage to 4GB
volumes:
  dawarich_db_data:
  dawarich_shared:
  dawarich_public:
  dawarich_watched:
  dawarich_storage:
  dawarich_db_data_pg_17:
```

Output of database container:
```
PostgreSQL Database directory appears to contain a database; Skipping initialization
2025-06-08 09:32:26.888 UTC [1] LOG:  starting PostgreSQL 17.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
2025-06-08 09:32:26.888 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2025-06-08 09:32:26.888 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2025-06-08 09:32:26.891 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2025-06-08 09:32:26.895 UTC [29] LOG:  database system was shut down at 2025-06-06 08:25:19 UTC
2025-06-08 09:32:26.895 UTC [29] LOG:  invalid checkpoint record
2025-06-08 09:32:26.895 UTC [29] PANIC:  could not locate a valid checkpoint record at 0/16C56DC0
2025-06-08 09:32:27.020 UTC [1] LOG:  startup process (PID 29) was terminated by signal 6: Aborted
2025-06-08 09:32:27.020 UTC [1] LOG:  aborting startup due to startup process failure
2025-06-08 09:32:27.020 UTC [1] LOG:  database system is shut down
```

Output of dawarich app:

```
⚠️ Starting Rails environment: development ⚠️
Created SQLite database directory at /dawarich_db_data
Setting up all required databases...
Attempting to create database dawarich_development if it doesn't exist...
Note: Database dawarich_development may already exist or couldn't be created now
⏳ Waiting for database dawarich_development to be ready...
Postgres database dawarich_development is unavailable - retrying...
Postgres database dawarich_development is unavailable - retrying..
```

I didnt change anything in the last update, just did a compose pull and compose up -d and it wouldn't start anymore...
