### ISSUE TITLE
Cannot connect via cloudflare tunnel

### ISSUE THREAD

**Issue by johnsturgeon** [Freika/dawarich#1248]
First I tried connecting through my existing tunnel, but that did not work, so I've created a new tunnel just for dawarich (and added the tunnel to the compose file).

Here are the relevant changes (let's say my domain is `dawarich.somedomain.tld`)
```yaml
dawarich_app:
  environment:
      RAILS_APPLICATION_CONFIG_HOSTS: ""
      APPLICATION_HOSTS: "dawarich.somedomain.tld,''"
dawarich_sidekiq:
  environment:
      RAILS_APPLICATION_CONFIG_HOSTS: ""
      APPLICATION_HOSTS: "dawarich.somedomain.tld,''"
tunnel:
  image: cloudflare/cloudflared:latest
  command: tunnel --no-autoupdate run
  networks:
    - dawarich
  env_file: tunnel.env
  restart: always
  container_name: tunnel
  depends_on:
    - dawarich_app
```

I'm getting the error: 

<img width="775" alt="Image" src="https://github.com/user-attachments/assets/1ad235cd-2368-4ec2-afa6-6ac6ac5cfa61" />

**Comment by faultoverload** [comment]
I'm just using a local reverse proxy instead of cloudflare but this is what my APPLICATION_HOSTS setting looks like. 10.0.1.6 is the IP of my nginx proxy.

`APPLICATION_HOSTS: localhost,::1,127.0.0.1,10.0.1.6,dawarich.domain.com`

**Comment by johnsturgeon** [comment]
Thank you my friend!  That did it.  I thought that because I was using a cloudflare tunnel that I had to use the cloudflare instructions, but alas, simply setting it up as a reverse proxy worked great.  For me, the trick was that I used the ip of the dawarich host instead of the nginx proxy

**Comment by fj-solutions** [comment]
Same Problem with Cloudflare Zero Trust Tunnel, following [this](https://dawarich.app/docs/tutorials/expose-instance-via-cloudflare-tunnel) tutorial.

Here are my changes (assuming my domain is: `dawarich.somedomain.tld`):

```
dawarich_app:
  environment:
      RAILS_APPLICATION_CONFIG_HOSTS: ""
      APPLICATION_HOSTS: dawarich.somedomain.tld,''
dawarich_sidekiq:
  environment:
      RAILS_APPLICATION_CONFIG_HOSTS: ""
      APPLICATION_HOSTS: dawarich.somedomain.tld,''
tunnel:
  image: cloudflare/cloudflared:latest
  command: tunnel --no-autoupdate run
  networks:
    - dawarich
  env_file: tunnel.env
  restart: always
  container_name: tunnel
  depends_on:
    - dawarich_app
```

Same Error aswell:

![Image](https://github.com/user-attachments/assets/cb4ab35d-23c8-4c0e-81ea-a062759cb7da)

Output in Console:
```
dawarich_app      | E, [2025-05-23T06:37:52.518152 #103] ERROR -- : [ActionDispatch::HostAuthorization::DefaultResponseApp] Blocked hosts: 
dawarich_app      | D, [2025-05-23T06:37:52.548143 #103] DEBUG -- :   Rendering layout vendor/bundle/ruby/3.4.0/gems/actionpack-8.0.2/lib/action_dispatch/middleware/templates/rescues/layout.erb
dawarich_app      | D, [2025-05-23T06:37:52.548560 #103] DEBUG -- :   Rendering vendor/bundle/ruby/3.4.0/gems/actionpack-8.0.2/lib/action_dispatch/middleware/templates/rescues/blocked_host.html.erb within rescues/layout
```


If somebody (maybe @johnsturgeon) could enlighten me, it would be much appreciated.
