### ISSUE TITLE
No automatic/scheduled searching for places/visits

### ISSUE THREAD

**Issue by solderer-de** [Freika/dawarich#1253]
**OS & Hardware**
Linux Docker

**Version**
0.26.5

**Describe the bug**
There is no scheduled searching for places or visits active in my instance. Manual searching via console is possible.

**Expected behavior**
As described in wiki there should be a scheduled task every night for searching and - as result - a notification for suggested visits. My last notification was 11 days ago for a manual search...

**Additional context**
What are the steps needed to debug this?

**Comment by solderer-de** [comment]
No scheduled tasks in sidekick:

<img width="1455" height="485" alt="Image" src="https://github.com/user-attachments/assets/30e30061-8393-4020-9fdd-0eb7a380af36" />

Nothing changed here with the last pdates :-/

**Comment by Freika** [comment]
Do you have reverse geocoding configured?

**Comment by solderer-de** [comment]
Yes - with my own photon instance. But - after inspecting compose file i found missing photon environment variables for sidekiq instance (maybe since changing scheduling to the other component and then back to sidekiq... - added now again and restart sidekiq instance). Is this relevant for scheduling visit searches?

**Comment by Freika** [comment]
@schoebelh yes it's relevant, refer to the default compose file to see what env vars are set in both containers

**Comment by solderer-de** [comment]
@Freika : I've checked my compose file against the default - can't see any qualifying differences... Can you check and show me the needed adaptations?

```
services:
  dawarich_redis:
    image: redis:7.4-alpine
    container_name: dawarich_redis
    command: redis-server
    networks:
      - dawarich
    volumes:
      - ./shared_data:/data
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  dawarich_app:
    image: freikin/dawarich:latest
    #image: freikin/dawarich:rc
    container_name: dawarich_app
    volumes:
      - ./public:/var/app/public
      - ./watched:/var/app/tmp/imports/watched
      - ./storage:/var/app/storage
      - ./db_data:/dawarich_db_data
    networks:
      - dawarich
      - proxy
      - db-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dawarich.entrypoints=websecure"
      - "traefik.http.routers.dawarich.rule=(Host(`xxx`))"
      - "traefik.http.routers.dawarich.tls=true"
      #- "traefik.http.routers.dawarich.tls.certresolver=http_resolver"
      - "traefik.http.routers.dawarich.service=dawarich"
      - "traefik.http.services.dawarich.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.dawarich.middlewares=default@file"
    stdin_open: true
    tty: true
    entrypoint: web-entrypoint.sh
    command: ['bin/rails', 'server', '-p', '3000', '-b', '::']
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379
      DATABASE_HOST: db-postgresql
      DATABASE_USERNAME: postgres
      #DATABASE_PASSWORD: xxx
      DATABASE_PASSWORD: xxx
      DATABASE_NAME: dawarich_development
      MIN_MINUTES_SPENT_IN_CITY: 60
      APPLICATION_HOSTS: xxx
      TIME_ZONE: Europe/Berlin
      APPLICATION_PROTOCOL: http
      REVERSE_GEOCODING_ENABLED: true
      DISTANCE_UNIT: km
      #PHOTON_API_HOST: photon.komoot.io
      PHOTON_API_HOST: photon:2322
      PHOTON_API_USE_HTTPS: false
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: 0.0.0.0
      PROMETHEUS_EXPORTER_PORT: 9394
      SIDEKIQ_USERNAME: xxx
      SIDEKIQ_PASSWORD: xxx
      SELF_HOSTED: true
      STORE_GEODATA: "true"
      SMTP_SERVER: xxx
      SMTP_PORT: 587
      SMTP_DOMAIN: xxx
      SMTP_USERNAME: xxx
      SMTP_PASSWORD: xxx
      SMTP_FROM: xxx
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO - http://127.0.0.1:3000/api/v1/health | grep -q '\"status\"\\s*:\\s*\"ok\"'" ]
      #test: [ "CMD-SHELL", "exit 0" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_redis:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '0.50'    # Limit CPU usage to 50% of one core
          memory: '4G'    # Limit memory usage to 2GB

  dawarich_sidekiq:
    image: freikin/dawarich:latest
    container_name: dawarich_sidekiq
    volumes:
      - ./public:/var/app/public
      - ./watched:/var/app/tmp/imports/watched
      - ./storage:/var/app/storage
    networks:
      - dawarich
      - db-net
    stdin_open: true
    tty: true
    entrypoint: sidekiq-entrypoint.sh
    command: ['sidekiq']
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379
      DATABASE_HOST: db-postgresql
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: xxx
      DATABASE_NAME: dawarich_development
      APPLICATION_HOSTS: localhost
      BACKGROUND_PROCESSING_CONCURRENCY: 10
      APPLICATION_PROTOCOL: http
      REVERSE_GEOCODING_ENABLED: true
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: dawarich_app
      PROMETHEUS_EXPORTER_PORT: 9394
      PHOTON_API_HOST: photon:2322
      PHOTON_API_USE_HTTPS: false
      SELF_HOSTED: "true"
      STORE_GEODATA: "true"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "pgrep -f sidekiq" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_redis:
        condition: service_healthy
        restart: true
      dawarich_app:
        condition: service_healthy
        restart: true

volumes:
  public:
  watched:
  storage:
  db_data:
  shared_data:

networks:
  proxy:
    external: true
  dawarich:
    driver: bridge
  db-net:
    external: true
    name: datenbanken_db-net
```
