### ISSUE TITLE
redis Errors and RAM Usage

### ISSUE THREAD

**Issue by sugarfunk** [Freika/dawarich#1287]
I am not sure what I have wrong here. redis is using 10-20gb ram and sidekiq is throwing these redis error. 

Config below.

```
W, [2025-05-30T22:08:01.893773 #8]  WARN -- : RedisClient::CommandError: LOADING Redis is loading the dataset in memory (redis://dawarich_redis:6379)
W, [2025-05-30T22:08:01.893906 #8]  WARN -- : 
E, [2025-05-30T22:08:09.233140 #8] ERROR -- : heartbeat: LOADING Redis is loading the dataset in memory
E, [2025-05-30T22:08:09.272123 #8] ERROR -- : LOADING Redis is loading the dataset in memory (redis://dawarich_redis:6379)
E, [2025-05-30T22:08:09.272313 #8] ERROR -- : /var/app/vendor/bundle/ruby/3.4.0/gems/redis-client-0.24.0/lib/redis_client/connection_mixin.rb:36:in 'RedisClient::ConnectionMixin#call'
W, [2025-05-30T22:08:09.272375 #8]  WARN -- : RedisClient::CommandError: LOADING Redis is loading the dataset in memory (redis://dawarich_redis:6379)
W, [2025-05-30T22:08:09.272680 #8]  WARN -- : 
E, [2025-05-30T22:08:09.277735 #8] ERROR -- : LOADING Redis is loading the dataset in memory (redis://dawarich_redis:6379)
W, [2025-05-30T22:08:09.278093 #8]  WARN -- : RedisClient::CommandError: LOADING Redis is loading the dataset in memory (redis://dawarich_redis:6379)
W, [2025-05-30T22:08:09.278309 #8]  WARN -- : 
E, [2025-05-30T22:08:09.277903 #8] ERROR -- : LOADING Redis is loading the dataset in memory (redis://dawarich_redis:6379)
W, [2025-05-30T22:08:09.278372 #8]  WARN -- : RedisClient::CommandError: LOADING Redis is loading the dataset in memory (redis://dawarich_redis:6379)
W, [2025-05-30T22:08:09.278524 #8]  WARN -- : 
E, [2025-05-30T22:08:09.288435 #8] ERROR -- : LOADING Redis is loading the dataset in memory (redis://dawarich_redis:6379)
W, [2025-05-30T22:08:09.288549 #8]  WARN -- : RedisClient::CommandError: LOADING Redis is loading the dataset in memory (redis://dawarich_redis:6379)
W, [2025-05-30T22:08:09.288703 #8]  WARN -- : 
```

Compose
```
networks:
  dawarich: null
services:
  dawarich_redis:
    image: redis:7.0-alpine
    container_name: dawarich_redis
    command: redis-server
    networks:
      - dawarich
    volumes:
      - ./dawarich_shared:/data
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - redis-cli
        - --raw
        - incr
        - ping
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  dawarich_db:
    image: postgis/postgis:17-3.5-alpine
    shm_size: 1G
    container_name: dawarich_db
    volumes:
      - ./dawarich_db_data:/var/lib/postgresql/data
      - ./dawarich_shared:/var/shared
      # - ./postgresql.conf:/etc/postgresql/postgresql.conf # Optional, uncomment if you want to use a custom config
    networks:
      - dawarich
    environment:
      POSTGRES_USER: postgres42
      POSTGRES_PASSWORD: XXXXXXXXXXXXXX
      POSTGRES_DB: dawarich_development
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres42 -d dawarich_development
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    # command: postgres -c config_file=/etc/postgresql/postgresql.conf # Use custom config, uncomment if you want to use a custom config
  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    volumes:
      - ./dawarich_public:/var/app/public
      - ./dawarich_watched:/var/app/tmp/imports/watched
      - ./dawarich_storage:/var/app/storage
    networks:
      - dawarich
    ports:
      - 3001:3000
      # - 9394:9394 # Prometheus exporter, uncomment if needed
    stdin_open: true
    tty: true
    entrypoint: web-entrypoint.sh
    command:
      - bin/rails
      - server
      - -p
      - "3000"
      - -b
      - "::"
    restart: unless-stopped
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres42
      DATABASE_PASSWORD: XXXXXXXXXXXXXXXX
      DATABASE_NAME: dawarich_development
      MIN_MINUTES_SPENT_IN_CITY: 60
      APPLICATION_HOSTS: HIDDENHOSTS
      TIME_ZONE: America/New_York
      APPLICATION_PROTOCOL: http
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: 0.0.0.0
      PROMETHEUS_EXPORTER_PORT: 9394
      SELF_HOSTED: "true"
      STORE_GEODATA: "true"
      DISABLE_TELEMETRY: "true"
      DISTANCE_UNIT: mi
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: "5"
    healthcheck:
      test:
        - CMD-SHELL
        - wget -qO - http://127.0.0.1:3000/api/v1/health | grep -q
          '"status"\s*:\s*"ok"'
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
      dawarich_redis:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: "0.50" # Limit CPU usage to 50% of one core
          memory: 4G # Limit memory usage to 4GB
  dawarich_sidekiq:
    image: freikin/dawarich:latest
    container_name: dawarich_sidekiq
    volumes:
      - ./dawarich_public:/var/app/public
      - ./dawarich_watched:/var/app/tmp/imports/watched
      - ./dawarich_storage:/var/app/storage
    networks:
      - dawarich
    stdin_open: true
    tty: true
    entrypoint: sidekiq-entrypoint.sh
    command:
      - sidekiq
    restart: unless-stopped
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres42
      DATABASE_PASSWORD: XXXXXXXXXXXXXX
      DATABASE_NAME: dawarich_development
      APPLICATION_HOSTS: HIDDENHOSTS
      BACKGROUND_PROCESSING_CONCURRENCY: 10
      APPLICATION_PROTOCOL: http
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: dawarich_app
      PROMETHEUS_EXPORTER_PORT: 9394
      SELF_HOSTED: "true"
      STORE_GEODATA: "true"
      DISTANCE_UNIT: mi
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: "5"
    healthcheck:
      test:
        - CMD-SHELL
        - bundle exec sidekiqmon processes | grep $${HOSTNAME}
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
      dawarich_redis:
        condition: service_healthy
        restart: true
      dawarich_app:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: "0.50" # Limit CPU usage to 50% of one core
          memory: 4G # Limit memory usage to 4GB
```
