### ISSUE TITLE
upgrading to 0.25.0 fails during migration from 0.23.6

### ISSUE THREAD

**Issue by miknuc** [Freika/dawarich#1349]
Hi,

I tried to update my dawarich instance from 023.6 to a current version. After having read the version comments I realized that a simple on step update would probably fail.
I upgraded to 0.24.0 as a first step and migrated the database to postgis/postgis:17-3.5-alpine.
During that update I cleaned up the docker-compose.yml and found some stuff from earlier versions that seem not to be required any more (redis, sidekick). System came up and was usable. 
As a next step I updated to 0.25.0.
This time, the migration fails with long stack traces:
```

dawarich_app  | PostgreSQL is ready. Running database migrations...
dawarich_app  | [dotenv] Set DATABASE_PORT, REDIS_URL, and DISTANCE_UNIT
dawarich_app  | [dotenv] Loaded .env.development
dawarich_app  | D, [2025-06-06T19:09:00.248089 #11] DEBUG -- :    (0.6ms)  SELECT pg_
try_advisory_lock(1212213197400985920)
dawarich_app  | D, [2025-06-06T19:09:00.289363 #11] DEBUG -- :   ActiveRecord::SchemaMigration 
Load (21.5ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schem
a_migrations"."version" ASC
dawarich_app  | D, [2025-06-06T19:09:00.344187 #11] DEBUG -- :   ActiveRecord::InternalMetadata
 Load (6.2ms)  SELECT * FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 
ORDER BY "ar_internal_metadata"."key" ASC LIMIT 1  [[nil, "environment"]]
dawarich_app  | D, [2025-06-06T19:09:00.347673 #11] DEBUG -- :    (0.5ms)  SELECT pg_
advisory_unlock(1212213197400985920)
dawarich_app  | D, [2025-06-06T19:09:00.357413 #11] DEBUG -- :   ActiveRecord::SchemaMigration 
Load (0.4ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema
_migrations"."version" ASC
dawarich_app  | Running DATA migrations...
dawarich_app  | [dotenv] Set DATABASE_PORT, REDIS_URL, and DISTANCE_UNIT
dawarich_app  | [dotenv] Loaded .env.development
dawarich_app  | D, [2025-06-06T19:09:04.962738 #52] DEBUG -- :    (2.1ms)  SELECT pg_
try_advisory_lock(1212213197400985920)
dawarich_app  | D, [2025-06-06T19:09:04.991115 #52] DEBUG -- :   DataMigrate::DataSchemaMigrati
on Load (6.6ms)  SELECT "data_migrations"."version" FROM "data_migrations" ORDER BY "data_mi
grations"."version" ASC
dawarich_app  | D, [2025-06-06T19:09:05.041093 #52] DEBUG -- :   ActiveRecord::InternalMetadata
 Load (6.6ms)  SELECT * FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 
ORDER BY "ar_internal_metadata"."key" ASC LIMIT 1  [[nil, "environment"]]
dawarich_app  | I, [2025-06-06T19:09:05.042497 #52]  INFO -- : Migrating to MigratePointsLatlon (20250
222213848)
dawarich_app  | == 20250222213848 MigratePointsLatlon: migrating ==============================
dawarich_app  | D, [2025-06-06T19:09:05.266365 #52] DEBUG -- :   TRANSACTION (0.3ms)  
BEGIN
dawarich_app  | D, [2025-06-06T19:09:05.328872 #52] DEBUG -- :   User Load (9.1ms)  S
ELECT "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT $1  [["LIMIT", 1000]]
dawarich_app  | 2025-06-06T19:09:05.539Z pid=52 tid=1qk INFO: Sidekiq 7.3.9 connecting to Redis with o
ptions {size: 10, pool_name: "internal", url: "redis://localhost:6379/1"}
dawarich_app  | E, [2025-06-06T19:09:05.559631 #52] ERROR -- : Failed enqueuing DataMigrations::Migrat
ePointsLatlonJob to Sidekiq(default): RedisClient::CannotConnectError (Connection refused - connect(2)
 for 127.0.0.1:6379 (redis://localhost:6379/1))
dawarich_app  | D, [2025-06-06T19:09:05.574304 #52] DEBUG -- :   TRANSACTION (0.3ms)  
ROLLBACK
dawarich_app  | D, [2025-06-06T19:09:05.580786 #52] DEBUG -- :    (0.5ms)  SELECT pg_
advisory_unlock(1212213197400985920)
dawarich_app  | rake aborted!
dawarich_app  | StandardError: An error has occurred, this and all later migrations canceled: (Standar
dError)
dawarich_app  | 
dawarich_app  | Connection refused - connect(2) for 127.0.0.1:6379
dawarich_app  | /var/app/vendor/bundle/ruby/3.4.0/gems/redis-client-0.23.2/lib/redis_client/ruby_conne
ction.rb:120:in 'RedisClient::RubyConnection#connect'
dawarich_app  | /var/app/vendor/bundle/ruby/3.4.0/gems/redis-client-0.23.2/lib/redis_client/ruby_conne
ction.rb:51:in 'RedisClient::RubyConnection#initialize'
dawarich_app  | /var/app/vendor/bundle/ruby/3.4.0/gems/redis-client-0.23.2/lib/redis_client.rb:759:in 
'Class#new'
dawarich_app  | /var/app/vendor/bundle/ruby/3.4.0/gems/redis-client-0.23.2/lib/redis_client.rb:759:in 
'block in RedisClient#connect'
dawarich_app  | /var/app/vendor/bundle/ruby/3.4.0/gems/redis-client-0.23.2/lib/redis_client/middleware
s.rb:12:in 'RedisClient::BasicMiddleware#connect'
dawarich_app  | /var/app/vendor/bundle/ruby/3.4.0/gems/redis-client-0.23.2/lib/redis_client.rb:758:in 
'RedisClient#connect'
dawarich_app  | /var/app/vendor/bundle/ruby/3.4.0/gems/redis-client-0.23.2/lib/redis_client.rb:745:in 
'RedisClient#raw_connection'

```

My docker-compose.yml :

```
networks:
  dawarich:
services:
  dawarich_db_pg_17:
    image: postgis/postgis:17-3.5-alpine
    shm_size: 1G
    container_name: dawarich_db_pg_17
    volumes:
      - dawarich_db_data_pg_17:/var/lib/postgresql/data
      - dawarich_shared:/var/shared
    networks:
      - dawarich
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d dawarich_development" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s


  dawarich_app:
    image: freikin/dawarich:0.25.0
    container_name: dawarich_app
    volumes:
      - /mnt/dawarich/public:/var/app/public
      - /mnt/dawarich/watched:/var/app/tmp/imports/watched
    networks:
      - dawarich
    ports:
      - 3000:3000
      - 9394:9394 # Prometheus exporter, uncomment if needed
    stdin_open: true
    tty: true
    entrypoint: web-entrypoint.sh
    command: ['bin/rails', 'server', '-p', '3000', '-b', '::']
    restart: on-failure
    environment:
      PUID: 1000
      PGID: 1000
      RAILS_ENV: development
      DATABASE_HOST: dawarich_db_pg_17
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      # SQLite database paths for secondary databases
      QUEUE_DATABASE_PATH: /dawarich_db_data/dawarich_development_queue.sqlite3
      CACHE_DATABASE_PATH: /dawarich_db_data/dawarich_development_cache.sqlite3
      CABLE_DATABASE_PATH: /dawarich_db_data/dawarich_development_cable.sqlite3
      MIN_MINUTES_SPENT_IN_CITY: 60
      APPLICATION_HOSTS: localhost,srv5,srv5.lan,dawarich.lan,dawarich
      TIME_ZONE: Europe/London
      APPLICATION_PROTOCOL: http
      i#DISTANCE_UNIT: km
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: 0.0.0.0
      PROMETHEUS_EXPORTER_PORT: 9394
      ENABLE_TELEMETRY: false # More on telemetry: https://dawarich.app/docs/tutorials/telemetry
      SELF_HOSTED: "true"
      STORE_GEODATA: "true"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO - http://127.0.0.1:3000/api/v1/health | grep -q '\"status\"\\s*:\\s*\"ok\"'" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db_pg_17:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '2.50'    # Limit CPU usage to 50% of one core
          memory: '4G'    # Limit memory usage to 4GB

volumes:
  dawarich_shared:
      driver: nfs
      driver_opts:
        type: nfs
        o: addr=nas2.lan,rw,mountvers=3
        device: ":/mnt/brt4/nfs-exports/dawarich/shared"
  dawarich_public:
      driver: nfs
      driver_opts:
        type: nfs
        o: addr=nas2.lan,rw,mountvers=3
        device: ":/mnt/brt4/nfs-exports/dawarich/public"
  dawarich_watched:
      driver: nfs
      driver_opts:
        type: nfs
        o: addr=nas2.lan,rw,mountvers=3
        device: ":/mnt/brt4/nfs-exports/dawarich/watched"
  dawarich_db_data_pg_17:
      driver_opts:
        type: nfs
        o: addr=nas2.lan,rw,mountvers=3
        device: ":/mnt/brt4/nfs-exports/dawarich/db17"

```

How can I fix this?
