### ISSUE TITLE
Completly lost with update breaking changes

### ISSUE THREAD

**Issue by Coysh** [Freika/dawarich#1353]
I had about a month away due to a few personal issues and am now completly lost when it comes to breaking changes and updates.

I know I need to update a few things - but any pointers into what?

Here is my docker-compose:

```
networks:
  dawarich: null
services:
  dawarich_redis:
    image: redis:7.0-alpine
    command: redis-server
    networks:
      - dawarich
    volumes:
      - shared_data:/var/shared/redis
    restart: always
  dawarich_db:
    image: postgis/postgis:14-3.5-alpine
    container_name: dawarich_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - shared_data:/var/shared
    networks:
      - dawarich
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: always
  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    volumes:
      - public:/var/app/public
    networks:
      - dawarich
    ports:
      - 4000:3000
    stdin_open: true
    tty: true
    entrypoint: web-entrypoint.sh
    command:
      - bin/rails
      - server
      - -p
      - "3000"
      - -b
      - "::"
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      MIN_MINUTES_SPENT_IN_CITY: 60
      APPLICATION_HOST: localhost
      APPLICATION_HOSTS: localhost
      TIME_ZONE: Europe/London
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: "5"
    depends_on:
      - dawarich_db
      - dawarich_redis
    deploy:
      resources:
        limits:
          cpus: "0.50" # Limit CPU usage to 50% of one core
          memory: 2G # Limit memory usage to 2GB
  dawarich_sidekiq:
    image: freikin/dawarich:latest
    container_name: dawarich_sidekiq
    volumes:
      - public:/var/app/public
    networks:
      - dawarich
    stdin_open: true
    tty: true
    entrypoint: sidekiq-entrypoint.sh
    command:
      - bundle
      - exec
      - sidekiq
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      APPLICATION_HOST: localhost
      APPLICATION_HOSTS: localhost
      BACKGROUND_PROCESSING_CONCURRENCY: 10
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: "5"
    depends_on:
      - dawarich_db
      - dawarich_redis
      - dawarich_app
    deploy:
      resources:
        limits:
          cpus: "0.50" # Limit CPU usage to 50% of one core
          memory: 2G # Limit memory usage to 2GB
volumes:
  db_data: null
  gem_cache: null
  shared_data: null
  public: null
  watched: null
```
