### ISSUE TITLE
Need help to Update from 0.25.3 to 0.27.3

### ISSUE THREAD

**Issue by spirit0607** [Freika/dawarich#1354]
Hey, I am very sorry, but I need some help to Update mit Installation from 0.25.3 to 0.27.3. I ran this von a Synology NAS. 

I tried different things, but nothing works. 

Could someone help me, please? Thank you!

Here is my docker-compose.yml
```
version: '3'

services:
  dawarich_redis:
    image: redis:7.0-alpine
    container_name: dawarich_redis
    command: redis-server
    restart: unless-stopped
    volumes:
      - ./redis:/var/shared/redis

  dawarich_db:
    image: postgis/postgis:14-3.5-alpine
    container_name: dawarich_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./db_shared:/var/shared

  dawarich_app:
    image: freikin/dawarich:0.25.3
    container_name: dawarich_app
    depends_on:
      - dawarich_db
      - dawarich_redis
    stdin_open: true
    tty: true
    entrypoint: web-entrypoint.sh
    command: ['bin/dev']
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./public:/var/app/public
    ports:
      - 7000:3000

  dawarich_sidekiq:
    image: freikin/dawarich:0.25.3
    container_name: dawarich_sidekiq
    depends_on:
      - dawarich_db
      - dawarich_redis
      - dawarich_app
    entrypoint: sidekiq-entrypoint.sh
    command: ['sidekiq']
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./public:/var/app/public
```
