### ISSUE TITLE
Database not starting after update.

### ISSUE THREAD

**Issue by runzl0r** [Freika/dawarich#1361]
This is my docker-compose, I think the error is somewhere here, since the database does not start.
```
networks:
  dawarich:
services:
  dawarich_db:
    image: postgis/postgis:17-3.5-alpine
    shm_size: 1G
    container_name: dawarich_db
    volumes:
      - dawarich_db_data_pg_17:/var/lib/postgresql/data
      - dawarich_shared:/var/shared
      # - ./postgresql.conf:/etc/postgresql/postgresql.conf # Optional, uncomment if you want to use a custom config
    networks:
      - dawarich
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dawarich_development
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d dawarich_development" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    # command: postgres -c config_file=/etc/postgresql/postgresql.conf # Use custom config, uncomment if you want to use a custom config
  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    volumes:
      - dawarich_public:/var/app/public
      - dawarich_watched:/var/app/tmp/imports/watched
      - dawarich_storage:/var/app/storage
#      - dawarich_db_data:/dawarich_db_data
      - dawarich_db_data_pg_17:/var/lib/postgresql/data
      - dawarich_shared:/var/shared
    networks:
      - dawarich
    ports:
      - 3001:3000
      # - 9394:9394 # Prometheus exporter, uncomment if needed
    stdin_open: true
    tty: true
    entrypoint: web-entrypoint.sh
    command: ['bin/rails', 'server', '-p', '3000', '-b', '::']
   restart: on-failure
    environment:
      RAILS_ENV: development
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      # SQLite database paths for secondary databases
      QUEUE_DATABASE_PATH: /dawarich_db_data/dawarich_development_queue.sqlite3
      CACHE_DATABASE_PATH: /dawarich_db_data/dawarich_development_cache.sqlite3
      CABLE_DATABASE_PATH: /dawarich_db_data/dawarich_development_cable.sqlite3
      MIN_MINUTES_SPENT_IN_CITY: 60
      APPLICATION_HOSTS: localhost
      TIME_ZONE: Europe/London
      APPLICATION_PROTOCOL: http
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: 0.0.0.0
      PROMETHEUS_EXPORTER_PORT: 9394
      SELF_HOSTED: "true"
      STORE_GEODATA: "true"
      PHOTON_API_HOST: photon.donsomhong.net
      PHOTON_API_USE_HTTPS: true

    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO - http://127.0.0.1:3000/api/v1/health | grep -q '\"status\"\\s*:\\s*\"ok\"'" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '1'    # Limit CPU usage to 50% of one core
          memory: '4G'    # Limit memory usage to 4GB
volumes:
  dawarich_db_data:
  dawarich_shared:
  dawarich_public:
  dawarich_watched:
  dawarich_storage:
  dawarich_db_data_pg_17:
```

Output of database container:
```
PostgreSQL Database directory appears to contain a database; Skipping initialization
2025-06-08 09:32:26.888 UTC [1] LOG:  starting PostgreSQL 17.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
2025-06-08 09:32:26.888 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2025-06-08 09:32:26.888 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2025-06-08 09:32:26.891 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2025-06-08 09:32:26.895 UTC [29] LOG:  database system was shut down at 2025-06-06 08:25:19 UTC
2025-06-08 09:32:26.895 UTC [29] LOG:  invalid checkpoint record
2025-06-08 09:32:26.895 UTC [29] PANIC:  could not locate a valid checkpoint record at 0/16C56DC0
2025-06-08 09:32:27.020 UTC [1] LOG:  startup process (PID 29) was terminated by signal 6: Aborted
2025-06-08 09:32:27.020 UTC [1] LOG:  aborting startup due to startup process failure
2025-06-08 09:32:27.020 UTC [1] LOG:  database system is shut down
```

Output of dawarich app:

```
⚠️ Starting Rails environment: development ⚠️
Created SQLite database directory at /dawarich_db_data
Setting up all required databases...
Attempting to create database dawarich_development if it doesn't exist...
Note: Database dawarich_development may already exist or couldn't be created now
⏳ Waiting for database dawarich_development to be ready...
Postgres database dawarich_development is unavailable - retrying...
Postgres database dawarich_development is unavailable - retrying..
```

I didnt change anything in the last update, just did a compose pull and compose up -d and it wouldn't start anymore...
Is this fixable or do I need to restart? Would be sad since I can only restore info from immich, the tracked info would be gone

**Comment by Freika** [comment]
Let's try the following:

1. Update your compose file:

```diff
```diff
...
  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    volumes:
      - dawarich_public:/var/app/public
      - dawarich_watched:/var/app/tmp/imports/watched
      - dawarich_storage:/var/app/storage
      - dawarich_db_data:/dawarich_db_data
+     - dawarich_sqlite_data:/dawarich_sqlite_data
    ...
    restart: on-failure
    environment:
    ...
      DATABASE_NAME: dawarich_development
+     # PostgreSQL database name for solid_queue
+     QUEUE_DATABASE_NAME: dawarich_development_queue
+     QUEUE_DATABASE_PASSWORD: password
+     QUEUE_DATABASE_USERNAME: postgres
+     QUEUE_DATABASE_PORT: 5432
+     QUEUE_DATABASE_HOST: dawarich_db
      # SQLite database paths for cache and cable databases
-     QUEUE_DATABASE_PATH: /dawarich_db_data/dawarich_development_queue.sqlite3
-     CACHE_DATABASE_PATH: /dawarich_db_data/dawarich_development_cache.sqlite3
-     CABLE_DATABASE_PATH: /dawarich_db_data/dawarich_development_cable.sqlite3
+     CACHE_DATABASE_PATH: /dawarich_sqlite_data/dawarich_development_cache.sqlite3
+     CABLE_DATABASE_PATH: /dawarich_sqlite_data/dawarich_development_cable.sqlite3

volumes:
  dawarich_db_data:
+ dawarich_sqlite_data:
  dawarich_shared:
  dawarich_public:
  dawarich_watched:
  dawarich_storage:
...
```

2. Remove sqlite files from your `dawarich_db_data` volume:
2.1: ssh into your database docker container: `docker exec -it <dawarich_db CONTAINER_ID> sh`
2.2 remove all the sqlite3 files: `rm -rf /var/lib/postgresql/data/*.sqlite3*`

3. Stop all the container and start them again with updated compose file.

Let me know if it helped

**Comment by runzl0r** [comment]
Sadly there is still an issue:
```
PostgreSQL Database directory appears to contain a database; Skipping initialization
2025-06-08 13:31:35.199 UTC [1] LOG:  starting PostgreSQL 17.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
2025-06-08 13:31:35.199 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2025-06-08 13:31:35.199 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2025-06-08 13:31:35.202 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2025-06-08 13:31:35.207 UTC [29] LOG:  database system was shut down at 2025-06-06 08:25:19 UTC
2025-06-08 13:31:35.207 UTC [29] LOG:  invalid checkpoint record
2025-06-08 13:31:35.207 UTC [29] PANIC:  could not locate a valid checkpoint record at 0/16C56DC0
2025-06-08 13:31:35.320 UTC [1] LOG:  startup process (PID 29) was terminated by signal 6: Aborted
2025-06-08 13:31:35.320 UTC [1] LOG:  aborting startup due to startup process failure
2025-06-08 13:31:35.321 UTC [1] LOG:  database system is shut down
```

For app its still the same since the db dependency can not be resolved.

I think the issue is that Im not sure which folder contains the database since there was that mixup with pg17...Not sure how to solve it :(
Also looks like I can't connect to the container to delete the files since its stuck in a reboot loop.

**Comment by Freika** [comment]
Try this to connect to docker volume: https://chatgpt.com/share/684593a4-5a2c-800c-ad02-7779ba2e5d9e

**Comment by runzl0r** [comment]
still the same error. is there a way I can fix the database? at least that what's chatgpt proposed, that there is some error...

**Comment by Freika** [comment]
So you connected to docker volume, removed files with the command I provided, updated your compose file, and after that, your DB container still wont start?

**Comment by runzl0r** [comment]
correct

**Comment by Freika** [comment]
Well, looks like your db data was corrupted. We can still try couple of things though. Back up your volume data ([example](https://www.howtogeek.com/devops/how-to-back-up-your-docker-volumes/)) first.

Let's try to ssh into container with access to your database volume and run the following:

```bash

docker exec -it your_postgres_container sh

su - postgres
/usr/lib/postgresql/17/bin/pg_resetwal -f /var/lib/postgresql/data
```

Then start your db container

**Comment by runzl0r** [comment]
Ok that worked. Some data is missing but that's not big of an issue. Can you help me how to get rid of those pg_17 volumes? Should I do db dump, clean install and put the dump back?

**Comment by Freika** [comment]
Great! Yes, you can use this tutorial: https://dawarich.app/docs/tutorials/backup-and-restore

**Comment by Korenchkin** [comment]
if you need to access data on docker container(do it in stopped state),you can go to /var/lib/docker/volumes (on the docker host,usual location,could be elsewhere) and delete/backup away...but there might be some inconsistencies if you delete whole shared folder(nothing bad,but if you don't have the mood to do complete docker prune,keep shared folders intact and delete only content under)

for adventurous persons(so you don't have to search for it each time you need access to them),you can map those shared folders to your place:

```
volumes:
  dawarich_db_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /opt/dawarich/db_data
  dawarich_db_sqlite:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /opt/dawarich/db_sqlite
...
```
(*edit x: nevermind,learned something new,that you should mark code blocks by triple ..ehm "`" apostrophes)
or just use symlink
