### ISSUE TITLE
No access to /jobs status 401

### ISSUE THREAD

**Issue by visevision** [Freika/dawarich#1376]
**OS & Hardware**
Intel something von Debian

**Version**
0.27.4 starting with 0.27.2 when i removed sidekiq

**Describe the bug**
When i press the "open dashboard"-button for the background jobs i got in the browser and the log status 401

**To Reproduce**
1. Go to Settings
2. Click on Show Open Dashboard

**Expected behavior**

**Screenshots**

**Logs**
{
  "method": "GET",
  "path": "/jobs/",
  "format": "html",
  "controller": "MissionControl::Jobs::QueuesController",
  "action": "index",
  "status": 401,
  "allocations": 232,
  "duration": 21.06,
  "view": 0,
  "db": 0
}

**Additional context**

**Comment by doerakje** [comment]
Same problem here

**OS & Hardware**
Ubuntu 24.04 & AMD

**Version**
0.27.4 starting from scratch

**Logs**
method=GET path=/jobs/ format=html controller=MissionControl::Jobs::QueuesController action=index status=401 allocations=160 duration=0.37 view=0 db=0

**compose.yml**
```yaml
services:

################################################################
########  DAWARICH
################################################################
########  Location History Tracker
########  Port 3000
################################################################

  dawarich_db:
    image: postgis/postgis:17-3.5-alpine
    container_name: dawarich_db
    hostname: dawarich_db
    security_opt:
      - no-new-privileges:true
    restart: always
    networks:
      - t3_proxy
    environment:
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
    volumes:
      - ${DOCKERDIR}/appdata/dawarich/db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "dawarich" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    shm_size: 1G
    labels:
      ## Watchtower
      - com.centurylinklabs.watchtower.enable=true
      # - com.centurylinklabs.watchtower.monitor-only=true

  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    hostname: dawarich_app
    security_opt:
      - no-new-privileges:true
    restart: always # on-failure
    networks:
      - t3_proxy
    ports:
      - 3000:3000
      # - 9394:9394 # Prometheus exporter, uncomment if needed
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
    command: ['bin/rails', 'server', '-p', '3000', '-b', '::']
    entrypoint: web-entrypoint.sh
    environment:
      RAILS_ENV: production
      DATABASE_HOST: $DATABASE_HOST
      DATABASE_PORT: $DATABASE_PORT
      DATABASE_USERNAME: $DATABASE_USERNAME
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      DATABASE_NAME: $DATABASE_NAME
      # PostgreSQL database name for solid_queue
      QUEUE_DATABASE_NAME: $QUEUE_DATABASE_NAME
      QUEUE_DATABASE_PASSWORD: $DATABASE_PASSWORD
      QUEUE_DATABASE_USERNAME: $DATABASE_USERNAME
      QUEUE_DATABASE_HOST: $DATABASE_HOST
      QUEUE_DATABASE_PORT: $DATABASE_PORT
      # SQLite database paths for cache and cable databases
      CACHE_DATABASE_PATH: /dawarich_sqlite_data/dawarich_production_cache.sqlite3
      CABLE_DATABASE_PATH: /dawarich_sqlite_data/dawarich_production_cable.sqlite3
      MIN_MINUTES_SPENT_IN_CITY: 60
      APPLICATION_HOST: "[REMOVED]"
      APPLICATION_HOSTS: "localhost,::1,127.0.0.1,192.168.27.101,[REMOVED]"
      TIME_ZONE: $TZ
      APPLICATION_PROTOCOL: http
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: 0.0.0.0
      PROMETHEUS_EXPORTER_PORT: 9394
      SECRET_KEY_BASE: [REMOVED]
      RAILS_LOG_TO_STDOUT: "true"
      SELF_HOSTED: "true"
      STORE_GEODATA: "true"
      PHOTON_API_HOST: 192.168.27.101:2322 
      PHOTON_API_USE_HTTPS: false
    volumes:
      - ${DOCKERDIR}/appdata/dawarich/public:/var/app/public
      - ${DOCKERDIR}/appdata/dawarich/watched:/var/app/tmp/imports/watched
      - ${DOCKERDIR}/appdata/dawarich/storage:/var/app/storage
      - ${DOCKERDIR}/appdata/dawarich/db_data:/dawarich_db_data
      - ${DOCKERDIR}/appdata/dawarich/sqlite_data:/dawarich_sqlite_data
    stdin_open: true
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO - http://127.0.0.1:3000/api/v1/health | grep -q '\"status\"\\s*:\\s*\"ok\"'" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    deploy:
      resources:
        limits:
          # cpus: '0.50'    # Limit CPU usage to 50% of one core
          memory: '4G'    # Limit memory usage to 4GB
    labels:
      - traefik.enable=true
      ## HTTP Routers
      - traefik.http.routers.dawarich.entrypoints=websecure
      - traefik.http.routers.dawarich.rule=Host(`[REMOVED].$DOMAINNAME_2`)
      ## Middlewares
      - traefik.http.routers.dawarich.middlewares=chain-oauth2@file
      ## HTTP Services
      - traefik.http.routers.dawarich.service=dawarich
      - traefik.http.services.dawarich.loadbalancer.server.port=3000
      ## Watchtower
      - com.centurylinklabs.watchtower.enable=true
      # - com.centurylinklabs.watchtower.monitor-only=true
```
