### ISSUE TITLE
Crashing after latest update

### ISSUE THREAD

**Issue by sebcourant** [Freika/dawarich#1412]
**OS & Hardware**
Docker

**Version**
0.28.1

**Describe the bug**
Crashing on start with error log :

> dawarich_db     | 2025-06-12 10:09:58.928 UTC [84] ERROR:  database "dawarich_development" already exists
dawarich_db     | 2025-06-12 10:09:58.928 UTC [84] STATEMENT:  CREATE DATABASE dawarich_development;
dawarich_app    | Note: Database dawarich_development may already exist or couldn't be created now
dawarich_app    | ⏳ Waiting for database dawarich_development to be ready...
dawarich_app    | ✅ PostgreSQL database dawarich_development is ready!
dawarich_app    | Running migrations for all databases...
dawarich_app    | Running primary database migrations...
dawarich_app    | [dotenv] Loaded .env.development
dawarich_app    | bin/rails aborted!
dawarich_app    | ArgumentError: invalid value for Integer(): "0/0" (ArgumentError)
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/redis-client-0.24.0/lib/redis_client/url_config.rb:33:in 'RedisClient::URLConfig#db'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/redis-client-0.24.0/lib/redis_client/config.rb:200:in 'RedisClient::Config#initialize'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/redis-client-0.24.0/lib/redis_client.rb:174:in 'Class#new'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/redis-client-0.24.0/lib/redis_client.rb:174:in 'RedisClient.config'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/redis-5.4.0/lib/redis/client.rb:23:in 'Redis::Client.config'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/redis-5.4.0/lib/redis.rb:142:in 'Redis#initialize_client'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/redis-5.4.0/lib/redis.rb:73:in 'Redis#initialize'
dawarich_app    | /var/app/config/initializers/geocoder.rb:7:in 'Class#new'
dawarich_app    | /var/app/config/initializers/geocoder.rb:7:in '<main>'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/engine.rb:693:in 'Kernel#load'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/engine.rb:693:in 'block in Rails::Engine#load_config_initializer'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/activesupport-8.0.2/lib/active_support/notifications.rb:212:in 'ActiveSupport::Notifications.instrument'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/engine.rb:692:in 'Rails::Engine#load_config_initializer'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/engine.rb:646:in 'block (2 levels) in <class:Engine>'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/engine.rb:645:in 'Array#each'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/engine.rb:645:in 'block in <class:Engine>'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/initializable.rb:32:in 'BasicObject#instance_exec'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/initializable.rb:32:in 'Rails::Initializable::Initializer#run'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/initializable.rb:61:in 'block in Rails::Initializable#run_initializers'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/initializable.rb:50:in 'Array#each'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/initializable.rb:50:in 'Rails::Initializable::Collection#tsort_each_child'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/initializable.rb:60:in 'Rails::Initializable#run_initializers'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/application.rb:440:in 'Rails::Application#initialize!'
dawarich_app    | /var/app/config/environment.rb:7:in '<main>'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in 'Kernel#require'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/zeitwerk-2.7.3/lib/zeitwerk/core_ext/kernel.rb:34:in 'Kernel#require'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/application.rb:416:in 'Rails::Application#require_environment!'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/application.rb:567:in 'block in Rails::Application#run_tasks_blocks'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:281:in 'block in Rake::Task#execute'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:281:in 'Array#each'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:281:in 'Rake::Task#execute'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:219:in 'block in Rake::Task#invoke_with_call_chain'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:199:in 'Monitor#synchronize'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:199:in 'Rake::Task#invoke_with_call_chain'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:243:in 'block in Rake::Task#invoke_prerequisites'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:241:in 'Array#each'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:241:in 'Rake::Task#invoke_prerequisites'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:218:in 'block in Rake::Task#invoke_with_call_chain'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:199:in 'Monitor#synchronize'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:199:in 'Rake::Task#invoke_with_call_chain'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:243:in 'block in Rake::Task#invoke_prerequisites'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:241:in 'Array#each'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:241:in 'Rake::Task#invoke_prerequisites'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:218:in 'block in Rake::Task#invoke_with_call_chain'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:199:in 'Monitor#synchronize'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:199:in 'Rake::Task#invoke_with_call_chain'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/task.rb:188:in 'Rake::Task#invoke'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/application.rb:188:in 'Rake::Application#invoke_task'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/application.rb:138:in 'block (2 levels) in Rake::Application#top_level'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/application.rb:138:in 'Array#each'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/application.rb:138:in 'block in Rake::Application#top_level'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/application.rb:147:in 'Rake::Application#run_with_threads'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/application.rb:132:in 'Rake::Application#top_level'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/commands/rake/rake_command.rb:27:in 'block (2 levels) in Rails::Command::RakeCommand.perform'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/application.rb:214:in 'Rake::Application#standard_exception_handling'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/commands/rake/rake_command.rb:27:in 'block in Rails::Command::RakeCommand.perform'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/commands/rake/rake_command.rb:44:in 'block in Rails::Command::RakeCommand.with_rake'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/lib/rake/rake_module.rb:59:in 'Rake.with_application'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/commands/rake/rake_command.rb:41:in 'Rails::Command::RakeCommand.with_rake'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/commands/rake/rake_command.rb:20:in 'Rails::Command::RakeCommand.perform'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/command.rb:150:in 'Rails::Command.invoke_rake'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/command.rb:67:in 'block in Rails::Command.invoke'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/command.rb:143:in 'Rails::Command.with_argv'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/command.rb:63:in 'Rails::Command.invoke'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/commands.rb:18:in '<main>'
dawarich_app    | /var/app/vendor/bundle/ruby/3.4.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in 'Kernel#require'
dawarich_app    | Tasks: TOP => db:migrate => db:load_config => environment
dawarich_app    | (See full trace by running task with --trace)
dawarich_app exited with code 0

Something due to redis_url ? 

Here is my compose file :

```
networks:
  dawarich: null
services:
  dawarich_redis:
    image: redis:7.0-alpine
    container_name: dawarich_redis
    command: redis-server
    networks:
      - dawarich
    volumes:
      - dawarich_shared:/data
    restart: always
    healthcheck:
      test:
        - CMD
        - redis-cli
        - --raw
        - incr
        - ping
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  dawarich_db:
    image: postgis/postgis:14-3.5-alpine
    shm_size: 1G
    container_name: dawarich_db
    volumes:
      - /docker_data/dawarich/dawarich_db_data:/var/lib/postgresql/data
      - /docker_data/dawarich/dawarich_shared:/var/shared
      # - ./postgresql.conf:/etc/postgresql/postgresql.conf # Optional, uncomment if you want to use a custom config
    networks:
      - dawarich
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: always
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres -d dawarich_development
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    # command: postgres -c config_file=/etc/postgresql/postgresql.conf # Use custom config, uncomment if you want to use a custom config
  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    volumes:
      - /docker_data/dawarich/dawarich_public:/var/app/public
      - /docker_data/dawarich/dawarich_watched:/var/app/tmp/imports/watched
    networks:
      - dawarich
    ports:
      - 3007:3000
      # - 9394:9394 # Prometheus exporter, uncomment if needed
    stdin_open: true
    tty: true
    entrypoint: web-entrypoint.sh
    command:
      - bin/rails
      - server
      - -p
      - "3000"
      - -b
      - "::"
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      MIN_MINUTES_SPENT_IN_CITY: 60
      APPLICATION_HOSTS: localhost
      TIME_ZONE: Europe/London
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: 0.0.0.0
      PROMETHEUS_EXPORTER_PORT: 9394
      ENABLE_TELEMETRY: false # More on telemetry: https://dawarich.app/docs/tutorials/telemetry
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: "5"
    healthcheck:
      test:
        - CMD-SHELL
        - wget -qO - http://127.0.0.1:3000/api/v1/health | grep -q
          '"status"\s*:\s*"ok"'
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
      dawarich_redis:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: "0.50" # Limit CPU usage to 50% of one core
          memory: 4G # Limit memory usage to 4GB
  dawarich_sidekiq:
    image: freikin/dawarich:latest
    container_name: dawarich_sidekiq
    volumes:
      - /docker_data/dawarich/dawarich_public:/var/app/public
      - /docker_data/dawarich/dawarich_watched:/var/app/tmp/imports/watched
    networks:
      - dawarich
    stdin_open: true
    tty: true
    entrypoint: sidekiq-entrypoint.sh
    command:
      - sidekiq
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      APPLICATION_HOSTS: localhost
      BACKGROUND_PROCESSING_CONCURRENCY: 10
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: dawarich_app
      PROMETHEUS_EXPORTER_PORT: 9394
      ENABLE_TELEMETRY: false # More on telemetry: https://dawarich.app/docs/tutorials/telemetry
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: "5"
    healthcheck:
      test:
        - CMD-SHELL
        - bundle exec sidekiqmon processes | grep $${HOSTNAME}
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
      dawarich_redis:
        condition: service_healthy
        restart: true
      dawarich_app:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: "0.50" # Limit CPU usage to 50% of one core
          memory: 4G # Limit memory usage to 4GB
volumes:
  dawarich_db_data: null
  dawarich_shared: null
  dawarich_public: null
  dawarich_watched: null
```
