### ISSUE TITLE
Error: NoMethodError: undefined method 'each' for nil:NilClass (NoMethodError)... when trying to import a Google Timeline json

### ISSUE THREAD

**Issue by SerinitySW** [Freika/dawarich#221]
**Describe the bug**
Following the steps in the documentation, I've run into a problem when running the rake command. It prints what I've pasted in the logs section.
**Version**
Dawarich 0.13.0
Redis 7.0-alpine
Postgresql 14.2-alpine

**To Reproduce**
1. Run docker-compose provided by repo, replacing the filepath variables with paths (the variables wouldn't work)
2. Copy Takeout.json into `/mnt/user/appdata/dawarich/public/imports`
3. Enter the container's sh (either through unRAID's built-in 'console' button or by running the `docker exec -it dawarich_app sh` command
4. Run `bundle exec rake import:big_file['public/imports/Timeline.json','myemailaddress@gmail.com']`
5. Error shown below prints

**Expected behavior**
The import process to start

**Screenshots**
![image](https://github.com/user-attachments/assets/b24d8a75-724b-4526-8786-a2879f32cf5a)

**Logs**
```
/var/app # bundle exec rake import:big_file['public/imports/Timeline.json',''myemailaddress@gmail.com']
[dotenv] Set DATABASE_PORT and PHOTON_API_HOST
[dotenv] Loaded .env.development
W, [2024-09-03T20:09:19.753116 #140]  WARN -- : DEPRECATION WARNING: `Rails.application.secrets` is deprecated in favor of `Rails.application.credentials` and will be removed in Rails 7.2. (called from <main> at /var/app/config/environment.rb:5)
D, [2024-09-03T20:09:20.450564 #140] DEBUG -- :   User Load (6.6ms)  SELECT "users".* FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "'myemailaddress@gmail.com"], ["LIMIT", 1]]
D, [2024-09-03T20:09:20.451269 #140] DEBUG -- :   ↳ app/services/tasks/imports/google_records.rb:9:in `initialize'
D, [2024-09-03T20:09:20.629750 #140] DEBUG -- :   TRANSACTION (0.5ms)  BEGIN
D, [2024-09-03T20:09:20.631529 #140] DEBUG -- :   ↳ app/services/tasks/imports/google_records.rb:26:in `create_import'
D, [2024-09-03T20:09:20.635522 #140] DEBUG -- :   Import Create (6.2ms)  INSERT INTO "imports" ("name", "user_id", "source", "created_at", "updated_at", "raw_points", "doubles", "processed", "raw_data", "points_count") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING "id"  [["name", "public/imports/Timeline.json"], ["user_id", 1], ["source", 2], ["created_at", "2024-09-03 20:09:20.625882"], ["updated_at", "2024-09-03 20:09:20.625882"], ["raw_points", 0], ["doubles", 0], ["processed", 0], ["raw_data", nil], ["points_count", 0]]
D, [2024-09-03T20:09:20.637467 #140] DEBUG -- :   ↳ app/services/tasks/imports/google_records.rb:26:in `create_import'
D, [2024-09-03T20:09:20.641597 #140] DEBUG -- :   TRANSACTION (3.5ms)  COMMIT
D, [2024-09-03T20:09:20.642332 #140] DEBUG -- :   ↳ app/services/tasks/imports/google_records.rb:26:in `create_import'
D, [2024-09-03T20:09:20.643201 #140] DEBUG -- : Importing public/imports/Timeline.json for 'myemailaddress@gmail.com, file size is 37284011... This might take a while, have patience!
rake aborted!
NoMethodError: undefined method `each' for nil:NilClass (NoMethodError)

    json_data['locations'].each do |json|
                          ^^^^^
/var/app/app/services/tasks/imports/google_records.rb:34:in `schedule_import_jobs'
/var/app/app/services/tasks/imports/google_records.rb:19:in `call'
/var/app/lib/tasks/import.rake:9:in `block (2 levels) in <main>'
/var/app/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/cli.rb:451:in `exec'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/cli.rb:34:in `dispatch'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/cli.rb:28:in `start'
/usr/local/bundle/gems/bundler-2.5.9/exe/bundle:28:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.5.9/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.5.9/exe/bundle:20:in `<top (required)>'
/usr/local/bundle/bin/bundle:25:in `load'
/usr/local/bundle/bin/bundle:25:in `<main>'
Tasks: TOP => import:big_file
(See full trace by running task with --trace)
/var/app # root@Gecko:~# 
```

**Additional context**
I did notice that the redis container is naming itself dawarich-dawarich_redis-1 no matter what I try. Below is my docker compose:

```
version: '3'
networks:
  dawarich:
services:
  dawarich_redis:
    image: redis:7.0-alpine
    command: redis-server
    networks:
      - dawarich
    volumes:
      - /mnt/user/appdata/dawarich/shared:/var/shared/redis
    restart: always
  dawarich_db:
    image: postgres:14.2-alpine
    container_name: dawarich_db
    volumes:
      - /mnt/user/appdata/dawarich/data:/var/lib/postgresql/data
      - /mnt/user/appdata/dawarich/shared:/var/shared
    networks:
      - dawarich
    environment:
      POSTGRES_USER: dawarich
      POSTGRES_PASSWORD: passwordhere
    restart: always
  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    volumes:
      - /mnt/user/appdata/dawarich/gems:/usr/local/bundle/gems
      - /mnt/user/appdata/dawarich/public:/var/app/public
    networks:
      - dawarich
    ports:
      - 3877:3000
    stdin_open: true
    tty: true
    entrypoint: dev-entrypoint.sh
    command: ['bin/dev']
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: dawarich
      DATABASE_PASSWORD: passwordhere
      DATABASE_NAME: dawarich_development
      MIN_MINUTES_SPENT_IN_CITY: 60
      APPLICATION_HOST: localhost
      APPLICATION_HOSTS: localhost
      TIME_ZONE: Europe/London
      APPLICATION_PROTOCOL: http
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    depends_on:
      - dawarich_db
      - dawarich_redis
    deploy:
      resources:
        limits:
          cpus: '3.00'    # Limit CPU usage to 50% of one core
          memory: '2G'    # Limit memory usage to 2GB
  dawarich_sidekiq:
    image: freikin/dawarich:latest
    container_name: dawarich_sidekiq
    volumes:
      - /mnt/user/appdata/dawarich/gems:/usr/local/bundle/gems
      - /mnt/user/appdata/dawarich/public:/var/app/public
    networks:
      - dawarich
    stdin_open: true
    tty: true
    entrypoint: dev-entrypoint.sh
    command: ['sidekiq']
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: dawarich
      DATABASE_PASSWORD: passwordhere
      DATABASE_NAME: dawarich_development
      APPLICATION_HOST: localhost
      APPLICATION_HOSTS: localhost,sub.domain.tld
      BACKGROUND_PROCESSING_CONCURRENCY: 25
      APPLICATION_PROTOCOL: http
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    depends_on:
      - dawarich_db
      - dawarich_redis
      - dawarich_app
    deploy:
      resources:
        limits:
          cpus: '3.00'    # Limit CPU usage to 50% of one core
          memory: '2G'    # Limit memory usage to 2GB
```
