### ISSUE TITLE
Nginx Proxy Manager in docker issue

### ISSUE THREAD

**Issue by hartmark** [Freika/dawarich#230]
**Describe the bug**
I fail to get dawarich to accept connections from my reverse proxy.
https://github.com/NginxProxyManager/nginx-proxy-manager

**Version**
docker-compose version

**To Reproduce**
1. Setup the nginx reverse proxy  by creating this docker-compose.yml file

```
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
```

2. Surf into localhost:81 and setup foohost.mydomain.com
3. Then I use https://github.com/Freika/dawarich/blob/master/docker-compose.yml
4. I remove the lines with APPLICATION_HOSTS
5. and change APPLICATION_HOST to have foohost.mydomain.com
6. When surfing into foohost.mydomain.com I'm met with just a json-response:

`{"status":"OK","version":{"major":2,"minor":11,"revision":3}}`

**Expected behavior**
If I surf into http://localhost:3000 it works as expected but I want it to behave the same for foohost.mydomain.com
