### ISSUE TITLE
Healthcheck endpoint

### ISSUE THREAD

**Issue by tetebueno** [Freika/dawarich#321]
**Describe the bug**
Not quite a bug, but a feature request. I't be nice to have an accessible API for healthcheck of the app service.

**Version**
0.15.3

**To Reproduce**
1. Try to execute a `curl` to an endpoint to see if service is running.

**Expected behavior**
Have a response from an endpoint to parse and determine health status of the app.

**Screenshots**
N/A

**Logs**
N/A

**Additional context**
Trying to add healthchecks for all Docker compose services I found that the only health check endopint available is `/api/v1/health`, but this is only accessible to an authenticated user. Also, `curl` is not installed in the Docker image, that would also be needed to craft a healthcheck command for the container.

I've managed to add healthcheck for all other services in `docker-compose.yaml`, my idea is to prepare a pull request, but I need to be sure what to do for the main service:

```yaml
  redis:
    ...
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  db:
    ...
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d dawarich_development" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  app:
    ...
    depends_on:
      db:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
        restart: true
  sidekiq:
    ...
    depends_on:
      db:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
        restart: true
      app:
        condition: service_started # Change to service_healthy once this issue is addressed.
...
```
