### ISSUE TITLE
Dawarich docker - Puma exits - a way to troubleshoot?

### ISSUE THREAD

**Issue by nitobuendia** [Freika/dawarich#365]
**Describe the bug**
When I ran `docker-compose up`, dawarich no longer starts.

Fails with `css.1  | exited with code 0`. Is there a way for me to troubleshoot this?

**Version**
Docker: `image: freikin/dawarich:latest`

**To Reproduce**
1. Run `docker-compose up -d`.
2. Fails with the below logs.

**Expected behavior**
Dawarich starts (as it used to).

**Other info**
Not sure if related - but just before this broke, I [added additional sidekiq containers](https://dawarich.app/docs/FAQ#how-to-speed-up-the-import-process). Then this issue started happening, but it could just have been because I had to stop the container and it never restarted (with or without the new sidekiq). Later, I removed the additional sidekiqs, but it still doesn't start with the same error. I don't see any logs files where I can troubleshoot a bit further beyond what's below.

**Logs**

```text
dawarich_app        | Latest version already installed. Done.
dawarich_app        | Successfully installed bundler-2.5.9
dawarich_app        | 1 gem installed
dawarich_app        | Database dawarich already exists, skipping creation...
dawarich_app        | PostgreSQL is ready. Running database migrations...
dawarich_app        | [dotenv] Set PHOTON_API_HOST
dawarich_app        | [dotenv] Loaded .env.development
dawarich_app        | D, [2024-10-31T01:46:29.772302 #24] DEBUG -- :   ActiveRecord::SchemaMigration Load (2.8ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
dawarich_app        | D, [2024-10-31T01:46:29.810129 #24] DEBUG -- :   ActiveRecord::SchemaMigration Load (1.5ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
dawarich_app        | Running DATA migrations...
dawarich_app        | [dotenv] Set PHOTON_API_HOST
dawarich_app        | [dotenv] Loaded .env.development
dawarich_app        | D, [2024-10-31T01:46:31.102370 #45] DEBUG -- :    (0.6ms)  SELECT pg_try_advisory_lock(1300285682869233375)
dawarich_app        | D, [2024-10-31T01:46:31.104519 #45] DEBUG -- :   DataMigrate::DataSchemaMigration Load (1.5ms)  SELECT "data_migrations"."version" FROM "data_migrations" ORDER BY "data_migrations"."version" ASC
dawarich_app        | D, [2024-10-31T01:46:31.107541 #45] DEBUG -- :   ActiveRecord::InternalMetadata Load (1.6ms)  SELECT * FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 ORDER BY "ar_internal_metadata"."key" ASC LIMIT 1  [[nil, "environment"]]
dawarich_app        | D, [2024-10-31T01:46:31.108834 #45] DEBUG -- :    (0.7ms)  SELECT pg_advisory_unlock(1300285682869233375)
dawarich_app        | D, [2024-10-31T01:46:31.110275 #45] DEBUG -- :   DataMigrate::DataSchemaMigration Load (0.7ms)  SELECT "data_migrations"."version" FROM "data_migrations" ORDER BY "data_migrations"."version" ASC
dawarich_app        | Running seeds...
dawarich_app        | [dotenv] Set PHOTON_API_HOST
dawarich_app        | [dotenv] Loaded .env.development
dawarich_app        | D, [2024-10-31T01:46:32.398754 #56] DEBUG -- :   ActiveRecord::SchemaMigration Load (1.9ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
dawarich_app        | D, [2024-10-31T01:46:32.414724 #56] DEBUG -- :   User Exists? (1.3ms)  SELECT 1 AS one FROM "users" LIMIT $1  [["LIMIT", 1]]
dawarich_app        | 01:46:32 web.1  | started with pid 72
dawarich_app        | 01:46:32 css.1  | started with pid 73
dawarich_app        | 01:46:33 web.1  | => Booting Puma
dawarich_app        | 01:46:33 web.1  | => Rails 7.2.1.1 application starting in development 
dawarich_app        | 01:46:33 web.1  | => Run `bin/rails server --help` for more startup options
dawarich_app        | 01:46:33 web.1  | [dotenv] Set PHOTON_API_HOST
dawarich_app        | 01:46:33 web.1  | [dotenv] Loaded .env.development
dawarich_app        | 01:46:33 css.1  | [dotenv] Set PHOTON_API_HOST
dawarich_app        | 01:46:33 css.1  | [dotenv] Loaded .env.development
dawarich_app        | 01:46:34 web.1  | Puma starting in single mode...
dawarich_app        | 01:46:34 web.1  | * Puma version: 6.4.3 (ruby 3.3.4-p94) ("The Eagle of Durango")
dawarich_app        | 01:46:34 web.1  | *  Min threads: 10
dawarich_app        | 01:46:34 web.1  | *  Max threads: 10
dawarich_app        | 01:46:34 web.1  | *  Environment: development
dawarich_app        | 01:46:34 web.1  | *          PID: 72
dawarich_app        | 01:46:34 web.1  | * Listening on http://0.0.0.0:3000
dawarich_app        | 01:46:34 web.1  | Use Ctrl-C to stop
dawarich_app        | 01:46:35 css.1  | exited with code 0
dawarich_app        | 01:46:35 system | sending SIGTERM to all processes
dawarich_app        | 01:46:35 web.1  | - Gracefully stopping, waiting for requests to finish
dawarich_app        | 01:46:35 web.1  | Exiting
dawarich_app        | 01:46:35 web.1  | terminated by SIGTERM
dawarich_app exited with code 0
```

**Additional context**

docker-compose.yaml

```yaml
services:
  dawarich_redis:
    image: redis:7.0-alpine
    container_name: dawarich_redis
    command: redis-server
    volumes:
      - ./data/shared:/var/shared/redis

  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    restart: unless-stopped
    command: ['bin/dev']
    entrypoint: dev-entrypoint.sh
    depends_on:
      - dawarich_redis
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    environment:
      TIME_ZONE: Asia/Singapore
      RAILS_ENV: development
      DISTANCE_UNIT: "km"
      MIN_MINUTES_SPENT_IN_CITY: 60
    env_file:
      - ./secrets.env
    volumes:
      - ./data/gem_cache:/usr/local/bundle/gems
      - ./data/public:/var/app/public
      - ./data/watched:/var/app/tmp/imports/watched
    labels:
      - "traefik.enable=true"
      # other traefik labels

  dawarich_sidekiq:
    image: freikin/dawarich:latest
    container_name: dawarich_sidekiq
    restart: unless-stopped
    command: ['sidekiq']
    entrypoint: dev-entrypoint.sh
    depends_on:
      - dawarich_redis
      - dawarich_app
    env_file:
      - ./secrets.env
```

secrets.env (anything with `<var>` has been redacted for obvious reasons:

```env
APPLICATION_PROTOCOL="http"
APPLICATION_HOST="<mydomain.com>:<port>"
APPLICATION_HOSTS="localhost,<mydomain.com>:<port>,<otherdomain.com>:<port>"

REDIS_URL="redis://dawarich_redis:6379/0"

DATABASE_HOST="<dbdomain.com>"
DATABASE_PORT="<port>"
DATABASE_USERNAME="dawarich"
DATABASE_PASSWORD="<password>"
DATABASE_NAME="<database>"

POSTGRES_USER="dawarich"
POSTGRES_PASSWORD="<password>"
REVERSE_GEOCODING_ENABLED="true"

RAILS_MAX_THREADS=10
BACKGROUND_PROCESSING_CONCURRENCY=10
```

**Comment by shaman007** [comment]
Having same issue when trying to run it in K8S. More debug info would be really nice! Is there a switch to increase verbosity?

**Comment by shaman007** [comment]
My setup:

- k8s deployment;
- all volumes are persistent;
- no ingress, no service, it just a 'localhost' run;
- I'd tried to mimic the docker-compose example as close as possible;
- Sidekiq works, I see records in the Redis
- It had creaded database in my Postgres and sees it on container restart.

My config so far:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dawarich
  namespace: dawarich
  labels:
    app: dawarich
spec:
  selector:
    matchLabels:
      app: dawarich
  template:
    metadata:
      labels:
        app: dawarich
    spec:
      containers:
        - name: dawarich
          env:
            - name: TIME_ZONE
              value: "Europe/Prague"
            - name: RAILS_ENV
              value: development
            - name: REDIS_URL
              value: redis://:<secret>@redis-master.redis.svc.cluster.local:6379/10
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-password
                  key: redis-password
            - name: DATABASE_HOST
              value: postgres-postgresql.db.svc.cluster.local
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USERNAME
              value: postgres
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: password
            - name: DATABASE_NAME
              value: dawarich_development
            - name: MIN_MINUTES_SPENT_IN_CITY
              value: "60"
            - name: APPLICATION_HOST
              value: localhost
            - name: APPLICATION_HOSTS
              value: localhost
            - name: APPLICATION_PROTOCOL
              value: http
            - name: DISTANCE_UNIT
              value: km
            - name: PHOTON_API_HOST
              value: photon.komoot.io
            - name: PHOTON_API_USE_HTTPS
              value: "true"
          image: freikin/dawarich:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /usr/local/bundle/gems_app
              name: gem-cache
            - mountPath: /var/app/public
              name: public
            - mountPath: /var/app/tmp/imports/watched
              name: watched
          command:
            - "dev-entrypoint.sh"
          args:
            - "bin/dev"
          resources:
            limits:
              memory: "3Gi"
              cpu: "1500m"
          ports:
          - containerPort: 3000
        - name: dawarich-sidekiq
          env:
            - name: RAILS_ENV
              value: development
            - name: REDIS_URL
              value: redis://:<secret>@redis-master.redis.svc.cluster.local:6379/10
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-password
                  key: redis-password
            - name: DATABASE_HOST
              value: postgres-postgresql.db.svc.cluster.local
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USERNAME
              value: postgres
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: password
            - name: DATABASE_NAME
              value: dawarich_development
            - name: BACKGROUND_PROCESSING_CONCURRENCY
              value: "10"
            - name: APPLICATION_HOST
              value: localhost
            - name: APPLICATION_HOSTS
              value: localhost
            - name: APPLICATION_PROTOCOL
              value: http
            - name: DISTANCE_UNIT
              value: km
            - name: PHOTON_API_HOST
              value: photon.komoot.io
            - name: PHOTON_API_USE_HTTPS
              value: "true"
          image: freikin/dawarich:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /usr/local/bundle/gems_sidekiq
              name: gem-sidekiq
            - mountPath: /var/app/public
              name: public
            - mountPath: /var/app/tmp/imports/watched
              name: watched
          command:
            - "dev-entrypoint.sh"
          args:
            - "sidekiq"
          resources:
            limits:
              memory: "3Gi"
              cpu: "1500m"
      volumes:
        - name: gem-cache
          persistentVolumeClaim:
            claimName: gem-cache
        - name: gem-sidekiq
          persistentVolumeClaim:
            claimName: gem-sidekiq
        - name: public
          persistentVolumeClaim:
            claimName: public
        - name: watched
          persistentVolumeClaim:
            claimName: watched

```
