### ISSUE TITLE
Continue Reverse Geocoding "eats" much RAM

### ISSUE THREAD

**Issue by tabacha** [Freika/dawarich#487]
**Describe the bug**

**Version**
0.19.0

**To Reproduce**

Limit the Sideikq container with memory in docker-compose.yml like this:
```  
networks:
  dawarich:
services:
  ...
  dawarich_sidekiq:
    ....
    deploy:
      resources:
        limits:
          cpus: '1'    
          memory: '6G'    # Limit memory usage to 6GB

```

1. Import 6 Million Points which are not geocoded for one user. On my machine it looks like this:
```
select COUNT(*) FROM Points where user_id=1 and geodata='{}';
  count  
---------
 6410501
(1 row)

```

2. Click on -> Settings -> Background Jobs -> Continue Reverse Geocoding
3. Accept Message to yes
4. Afer a while you will find a `dawarich_sidekiq  | Killed` in the docker compose logfile. 

**Expected behavior**

Geocoding should not take so much memory. It sould continue when a dawarich processed is killed or restarted by the user.

I saw in the logfile this sql query:

```
  SELECT "points".* FROM "points" WHERE "points"."user_id" = $1 AND "points"."geodata" = $2  [["user_id", 1], ["geodata", "{}"]]
``` 

This means that alle 6 million  not geocoded points will be loaded into memory (RAM). 

I suggest to use batches. and modify the query and add an 'LIMIT 1000` at the end ofthe query.

Process this 1000 Points and afterwards do it again.

**Logs**
[docker-compose-logs-6G-limit.log](https://github.com/user-attachments/files/18026255/docker-compose-logs-6G-limit.log)
