### ISSUE TITLE
App does not bind to IPv6

### ISSUE THREAD

**Issue by duckfullstop** [Freika/dawarich#498]
**Describe the bug**
When launching Dawarich, the default listen path of `0.0.0.0` results in binding to IPv4 addresses only, and IPv6 requests are refused.

**Version**
0.18.2 (but present on `master`)

**To Reproduce**
1. Launch Dawarich using the default `bin/dev` launch path.
2. Attempt to access Dawarich using an IPv6 address.

**Expected behavior**
Dawarich should return the usual data that it returns over IPv4.

**Additional context**
This affects Kubernetes IPv6 / DualStack deployments in particular, including those using the third party helm chart - which, while I appreciate is third party, is using the standard launch binary!

I note #437, but that still calls `bin/dev` and in turn `procfile.dev`

The quick and dirty fix would be to patch `procfile.dev` to bind to all addresses (`web: bin/rails server -p 3000 -b ::`), but I'm not sure if it makes more sense to add configurability (say an envvar) for this instead. Unfortunately Ruby is far from my native tongue, so it's probably better to leave that kind of decision making to you.

**Comment by hopeseekr** [comment]
I got around this (and have proper SSL support) by using a Nginx reverse proxy.

Here's my server config:

```nginx
server {
    listen [::]:443 ssl;
    listen 116.202.37.112:443 ssl;
#    listen 80;
#    listen 443;
    server_name location.zpf.io;  # This should match the domain the external clients use to access the service

    root /var/www/public;
    index index.html;

    gzip on; 

    location / {
        proxy_pass http://172.18.0.3:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_ssl_server_name on;
        proxy_ssl_verify off;  # Depending on your security requirements you might want to enable or disable SSL verification
        proxy_redirect off;
    }

    ssl_certificate /etc/letsencrypt/live/location.zpf.io/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/location.zpf.io/privkey.pem; # managed by Certbot
}
```

I have it listening to a specific IPv4 address so that nginx listens on ports 80 and 443 of the public IP and every other docker instance and npm server listens on a different 127.0.0.x address.

The entire Class A 127.x.x.x block is private to localhost. I don't know why we all use 127.0.0.1 only...

**Comment by duckfullstop** [comment]
> I got around this (and have proper SSL support) by using a Nginx reverse proxy.

That's definitely a workaround - the big issue is that in Kubernetes, by default if the cluster is configured to be IPv6 first (or indeed IPv6 only), service objects will expect to dial a workload on the v6 address, mysteriously breaking connectivity.

The workaround is to define the service as v4:

```
ipFamilies:
  - IPv4
ipFamilyPolicy: SingleStack
```

but that's pretty dirty (and still breaks on v6 only clusters). Binding to `::` is a simple fix that doesn't break backwards compatibility to v4 (it still resolves to v4-only interfaces).

**Comment by hopeseekr** [comment]
Did you try changing the docker-compose.yml tl " - 3000" instead of " - 3000:3000"??

**Comment by hopeseekr** [comment]
Well, try this...

```
web: bin/rails server -p 3000 -b ::
```

With this k8s config:


```yaml
apiVersion: v1
kind: Service
metadata:
  name: rails-service
  annotations:
    # Ensure your cloud provider or networking plugin supports IPv6
    networking.alpha.kubernetes.io/ipv6: "true"
spec:
  selector:
    app: rails-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
  # If using a LoadBalancer that supports IPv6
  ipFamilies:
    - IPv6
```
