### ISSUE TITLE
Afraid to upgrade due to Docker volume name changes...

### ISSUE THREAD

**Issue by hopeseekr** [Freika/dawarich#501]
**Describe the bug**
Conflict in my docker-compose.yml:

```
volumes:
<<<<<<< Updated upstream
  dawarich_db_data:
  dawarich_gem_cache_app:
  dawarich_gem_cache_sidekiq:
  dawarich_shared:
  dawarich_public:
  dawarich_watched:
=======
  gem_cache:
  shared_data:
  public:
  watched:
>>>>>>> Stashed changes
```

**Version**
v0.19.3

**To Reproduce**
1. Install v0.18.0
2. Do a `git pull` up to v0.19.3.
3. Notice that the docker volume names have changed.

**Expected behavior**
I would expect some sort of migration guide in the README on how to avoid irretrievable data loss and how to clean up the old volumes, or mabye just how to rename them.

**Additional context**
I lack all confidence in the upgrade, so I reverted.

```
git checkout --theirs docker-compose.yml 
```

This kept the volumes the same. I hope it doesn't actually break anything :-/ I have a multi-day Google Timeline import going, and I was hoping this upgrade would dramatically speed it up.
