### ISSUE TITLE
0.22.0 dawarich_app fails to start : `cannot load such file -- /usr/local/bundle/gems/bundler-2.5.21/exe/bundle (LoadError)`

### ISSUE THREAD

**Issue by gboudreau** [Freika/dawarich#638]
In 0.21.6, I had this in my docker-compose:
```
    entrypoint: dev-entrypoint.sh
    command: ['bin/dev']
```

Was working as expected:
```
dawarich_app    | Fetching rubygems-update-3.5.7.gem
dawarich_app    | Successfully installed rubygems-update-3.5.7
dawarich_app    | Installing RubyGems 3.5.7
dawarich_app    |   Successfully built RubyGem
dawarich_app    |   Name: bundler
dawarich_app    |   Version: 2.5.7
dawarich_app    |   File: bundler-2.5.7.gem
dawarich_app    | Bundler 2.5.7 installed
dawarich_app    | RubyGems 3.5.7 installed
dawarich_app    | Regenerating binstubs
dawarich_app    | Regenerating plugins
dawarich_app    | 
dawarich_app    | 
dawarich_app    | 
dawarich_app    | ------------------------------------------------------------------------------
dawarich_app    | 
dawarich_app    | RubyGems installed the following executables:
dawarich_app    | 	/usr/local/bin/gem
dawarich_app    | 	/usr/local/bin/bundle
dawarich_app    | 	/usr/local/bin/bundler
dawarich_app    | 
dawarich_app    | RubyGems system software updated
dawarich_app    | Fetching bundler-2.5.9.gem
dawarich_app    | Successfully installed bundler-2.5.9
dawarich_app    | 1 gem installed
dawarich_app    | 
dawarich_app    | A new release of RubyGems is available: 3.5.7 → 3.6.2!
dawarich_app    | Run `gem update --system 3.6.2` to update your installation.
dawarich_app    | 
dawarich_app    | Database dawarich_development already exists, skipping creation...
dawarich_app    | PostgreSQL is ready. Running database migrations...
...
dawarich_app    | 16:20:23 web.1  | [149] * Listening on http://[::]:3000
dawarich_app    | 16:20:23 web.1  | [149] Use Ctrl-C to stop
dawarich_app    | 16:20:23 web.1  | [149] - Worker 0 (PID: 163) booted in 0.01s, phase: 0
dawarich_app    | 16:20:23 web.1  | [149] - Worker 1 (PID: 170) booted in 0.01s, phase: 0
dawarich_app    | 16:20:23 web.1  | [149] - Worker 2 (PID: 179) booted in 0.07s, phase: 0
```

But on 0.22.0, I now have this in my docker-compose:
```
    entrypoint: web-entrypoint.sh
    command: ['bin/rails', 'server', '-p', '3000', '-b', '::']
```

But that fails with the following error:
```
dawarich_app    | ✅ PostgreSQL is ready!
dawarich_app    | PostgreSQL is ready. Running database migrations...
dawarich_app    | /usr/local/bundle/bin/bundle:25:in `load': cannot load such file -- /usr/local/bundle/gems/bundler-2.5.21/exe/bundle (LoadError)
dawarich_app    | 	from /usr/local/bundle/bin/bundle:25:in `<main>'
dawarich_app exited with code 0
```

full docker-compose.yml:
```yaml
networks:
  dawarich:

services:
  dawarich_redis:
    image: redis:7.0-alpine
    container_name: dawarich_redis
    command: redis-server
    networks:
      - dawarich
    volumes:
      - ${SHARED_DATA_LOCATION}:/data
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  dawarich_db:
    image: postgres:14.2-alpine
    shm_size: 1G
    container_name: dawarich_db
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
      - ${SHARED_DATA_LOCATION}:/var/shared
      - ${DB_CONF_LOCATION}:/etc/postgresql/postgresql.conf
    networks:
      - dawarich
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d dawarich_development" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    volumes:
      - ${GEM_CACHE_LOCATION}app:/usr/local/bundle/gems
      - ${PUBLIC_LOCATION}:/var/app/public
      - ${WATCHED_LOCATION}:/var/app/tmp/imports/watched
    networks:
      - dawarich
    ports:
      - 2284:3000
    stdin_open: true
    tty: true
    entrypoint: web-entrypoint.sh
    command: ['bin/rails', 'server', '-p', '3000', '-b', '::']
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      MIN_MINUTES_SPENT_IN_CITY: 60
      APPLICATION_HOST: localhost
      APPLICATION_HOSTS: localhost,dawarich.patati.ca
      TIME_ZONE: America/Toronto
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
      REVERSE_GEOCODING_ENABLED: true
      PHOTON_API_HOST: photon.home.patati.ca
      WEB_CONCURRENCY: 3
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO - http://127.0.0.1:3000/api/v1/health | grep -q '\"status\"\\s*:\\s*\"ok\"'" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
      dawarich_redis:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '0.50'    # Limit CPU usage to 50% of one core
          memory: '4G'    # Limit memory usage to 4GB
  dawarich_sidekiq:
    image: freikin/dawarich:latest
    container_name: dawarich_sidekiq
    volumes:
      - ${GEM_CACHE_LOCATION}sidekiq:/usr/local/bundle/gems
      - ${PUBLIC_LOCATION}:/var/app/public
      - ${WATCHED_LOCATION}:/var/app/tmp/imports/watched
    networks:
      - dawarich
    stdin_open: true
    tty: true
    entrypoint: sidekiq-entrypoint.sh
    command: ['sidekiq']
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      APPLICATION_HOST: localhost
      APPLICATION_HOSTS: localhost,dawarich.patati.ca
      BACKGROUND_PROCESSING_CONCURRENCY: 10
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
      REVERSE_GEOCODING_ENABLED: true
      PHOTON_API_HOST: photon.home.patati.ca
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "bundle exec sidekiqmon processes | grep $${HOSTNAME}" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
      dawarich_redis:
        condition: service_healthy
        restart: true
      dawarich_app:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '0.50'    # Limit CPU usage to 50% of one core
          memory: '4G'    # Limit memory usage to 4GB
```

**Comment by Freika** [comment]
You have probably meant 0.22.0 version.

Got same issue, solved by changing both sidekiq and app containers to use single volume for gem caching, in your case:

```
  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_sidekiq
    volumes:
      - ${GEM_CACHE_LOCATION}:/usr/local/bundle/gems
  dawarich_sidekiq:
    image: freikin/dawarich:latest
    container_name: dawarich_sidekiq
    volumes:
      - ${GEM_CACHE_LOCATION}:/usr/local/bundle/gems
```

Let me know if it helps
