### ISSUE TITLE
Incorrect path to entry point scripts in Dockerfile.prod

### ISSUE THREAD

**Issue by chrisl8** [Freika/dawarich#639]
I think that this line:
https://github.com/Freika/dawarich/blob/ae60a38e0cc75ae502d773e030fb6bfb69fd43a3/docker/Dockerfile.prod#L47

and this line:
https://github.com/Freika/dawarich/blob/ae60a38e0cc75ae502d773e030fb6bfb69fd43a3/docker/Dockerfile.prod#L50

have incorrect paths.

`./docker/` should just be `./`

**Comment by Freika** [comment]
Thanks! Will fix it in the next release.

**Comment by chrisl8** [comment]
Actually I think this is my mistake, I was setting up the context incorrectly in my compose file.

I had it set up like this:
```
  dawarich_app:
    container_name: dawarich_app
    build:
      context: ./dawarich/docker
      dockerfile: Dockerfile.prod
```

but it should be like this:
```
  dawarich_app:
    container_name: dawarich_app
    build:
      context: ./dawarich
      dockerfile: docker/Dockerfile.prod
```

and then your `Dockerfile.prod` seems to work.
