### ISSUE TITLE
Wrong database selected using docker compose

### ISSUE THREAD

**Issue by adromir** [Freika/dawarich#730]
**OS & Hardware**
Unraid

**Version**
all

**Describe the bug**
I try to use a modified Docker compose to run Dawarich and Dawarich Sidekiq on my Unraid Server but the app fails to start because it says in the logs "Database andreas not found". If I use the Unraid template with the same credentials for the Database it works without any issues.

**Additional context**
Modified Docker Compose:

```
services:
  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    network_mode: bridge  
    restart: unless-stopped
    memswap_limit: -1
    volumes:
      - /mnt/cache/appdata/dawarich/wwwroot:/var/app/public
      - /mnt/cache/appdata/dawarich/imports:/var/app/tmp/imports/watched
    ports:
      - 3030:3000
      # - 9394:9394 # Prometheus exporter, uncomment if needed
    stdin_open: true
    tty: true
    entrypoint: web-entrypoint.sh
    command: ['bin/rails', 'server', '-p', '3000', '-b', '::','rm /var/app/tmp/pids/server.pid']
    environment:
      RAILS_ENV: production
      REDIS_URL: redis://192.168.2.5:6379/0
      DATABASE_HOST: 192.168.2.5
      DATABASE_PORT: 5432
      DATABASE_USERNAME: andreas
      DATABASE_PASSWORD: +++++
      DATABASE_NAME: dawarich
      MIN_MINUTES_SPENT_IN_CITY: 60
      APPLICATION_HOSTS: localhost,::1,127.0.0.1,192.168.2.5
      TIME_ZONE: Europe/Berlin
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: 0.0.0.0
      PROMETHEUS_EXPORTER_PORT: 9394
      SECRET_KEY_BASE: 1234567890
      RAILS_LOG_TO_STDOUT: "true"
      PHOTON_API_HOST: 192.168.2.5:2322
      PHOTON_API_USE_HTTPS: false
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO - http://127.0.0.1:3000/api/v1/health | grep -q '\"status\"\\s*:\\s*\"ok\"'" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    deploy:
      resources:
        limits:
          cpus: '0.50'    # Limit CPU usage to 50% of one core
          memory: '4G'    # Limit memory usage to 2GB
  dawarich_sidekiq:
    image: freikin/dawarich:latest
    container_name: dawarich_sidekiq
    volumes:
      - /mnt/cache/appdata/dawarich/wwwroot:/var/app/public
      - /mnt/cache/appdata/dawarich/imports:/var/app/tmp/imports/watched
    stdin_open: true
    tty: true
    entrypoint: sidekiq-entrypoint.sh
    command: ['bundle', 'exec', 'sidekiq']
    memswap_limit: -1
    network_mode: bridge  
    restart: unless-stopped
    environment:
      RAILS_ENV: production
      REDIS_URL: redis://192.168.2.5:6379/0
      DATABASE_HOST: 192.168.2.5
      DATABASE_PORT: 5432
      DATABASE_USERNAME: andreas
      DATABASE_PASSWORD: ++++++
      DATABASE_NAME: dawarich
      MIN_MINUTES_SPENT_IN_CITY: 60
      APPLICATION_HOSTS: localhost,::1,127.0.0.1,192.168.2.5
      TIME_ZONE: Europe/Berlin
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: 0.0.0.0
      PROMETHEUS_EXPORTER_PORT: 9394
      SECRET_KEY_BASE: 1234567890
      RAILS_LOG_TO_STDOUT: "true"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "bundle exec sidekiqmon processes | grep $${HOSTNAME}" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_app:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '0.50'    # Limit CPU usage to 50% of one core
          memory: '4G'    # Limit memory usage to 2GB
```
