### ISSUE TITLE
docker compose failed to create app/stack

### ISSUE THREAD

**Issue by herrxyz** [Freika/dawarich#731]
**OS & Hardware**
debian, portainer, CPU Intel Celeron J4105, 4 GB RAM

**Version**
latest docker compose, see below

**Describe the bug**
Failed to deploy a stack: Container dawarich_app Creating Container dawarich_app Created Container dawarich_sidekiq Creating Container dawarich_sidekiq Created Container dawarich_app Starting Container dawarich_app Started Container dawarich_app Waiting Container dawarich_app Error dependency failed to start: container dawarich_app is unhealthy 

**To Reproduce**
use docker compose file below

**Expected behavior**
image should start and run

**Screenshots**
no

**Logs**
If applicable, add logs from containers `dawarich_app` and `dawarich_sidekiq` to help explain your problem.
stacks disappeared because error during creation

**Additional context**
used docker compose config: (password redacted)
```
services:
  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    network_mode: bridge  
    restart: unless-stopped
    memswap_limit: -1
    volumes:
      - /mnt/cache/appdata/dawarich/wwwroot:/var/app/public
      - /mnt/cache/appdata/dawarich/imports:/var/app/tmp/imports/watched
    ports:
      - 3030:3000
      # - 9394:9394 # Prometheus exporter, uncomment if needed
    stdin_open: true
    tty: true
    entrypoint: web-entrypoint.sh
    command: ['bin/rails', 'server', '-p', '3000', '-b', '::','rm /var/app/tmp/pids/server.pid']
    environment:
      RAILS_ENV: production
      REDIS_URL: redis://192.168.16.111:6379/0
      DATABASE_HOST: 192.168.16.111
      DATABASE_PORT: 5432
      DATABASE_USERNAME: judawar
      DATABASE_PASSWORD: dfg4676xxx
      DATABASE_NAME: dawarich
      MIN_MINUTES_SPENT_IN_CITY: 60
      APPLICATION_HOSTS: localhost,::1,127.0.0.1,192.168.16.111
      TIME_ZONE: Europe/Berlin
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: 0.0.0.0
      PROMETHEUS_EXPORTER_PORT: 9394
      SECRET_KEY_BASE: 1527834690
      RAILS_LOG_TO_STDOUT: "true"
      PHOTON_API_HOST: 192.168.16.111:2322
      PHOTON_API_USE_HTTPS: false
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO - http://127.0.0.1:3000/api/v1/health | grep -q '\"status\"\\s*:\\s*\"ok\"'" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    deploy:
      resources:
        limits:
          cpus: '0.50'    # Limit CPU usage to 50% of one core
          memory: '2G'    # Limit memory usage to 2GB
  dawarich_sidekiq:
    image: freikin/dawarich:latest
    container_name: dawarich_sidekiq
    volumes:
      - /mnt/cache/appdata/dawarich/wwwroot:/var/app/public
      - /mnt/cache/appdata/dawarich/imports:/var/app/tmp/imports/watched
    stdin_open: true
    tty: true
    entrypoint: sidekiq-entrypoint.sh
    command: ['bundle', 'exec', 'sidekiq']
    memswap_limit: -1
    network_mode: bridge  
    restart: unless-stopped
    environment:
      RAILS_ENV: production
      REDIS_URL: redis://192.168.16.111:6379/0
      DATABASE_HOST: 192.168.16.111
      DATABASE_PORT: 5432
      DATABASE_USERNAME: judawar
      DATABASE_PASSWORD: dfg4676xxx
      DATABASE_NAME: dawarich
      MIN_MINUTES_SPENT_IN_CITY: 60
      APPLICATION_HOSTS: localhost,::1,127.0.0.1,192.168.16.111
      TIME_ZONE: Europe/Berlin
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: 0.0.0.0
      PROMETHEUS_EXPORTER_PORT: 9394
      SECRET_KEY_BASE: 1527834690
      RAILS_LOG_TO_STDOUT: "true"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "bundle exec sidekiqmon processes | grep $${HOSTNAME}" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_app:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '0.50'    # Limit CPU usage to 50% of one core
          memory: '2G'    # Limit memory usage to 2GB

```
