### ISSUE TITLE
DaWarIch not loading after Update

### ISSUE THREAD

**Issue by datadrowner** [Freika/dawarich#752]
Hey guys,

I updated my docker-compose to the latest but I am unable to access the page.

```
networks:
  dawarich: null
services:
  dawarich_redis:
    image: 'redis:7.0-alpine'
    container_name: dawarich_redis
    command: redis-server
    networks:
      - dawarich
    volumes:
      - 'dawarich_shared:/data'
    restart: always
    healthcheck:
      test:
        - CMD
        - redis-cli
        - '--raw'
        - incr
        - ping
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  dawarich_db:
    image: 'postgres:14.2-alpine'
    shm_size: 1G
    container_name: dawarich_db
    volumes:
      - 'dawarich_db_data:/var/lib/postgresql/data'
      - 'dawarich_shared:/var/shared'
    networks:
      - dawarich
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: always
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U postgres -d dawarich_development'
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  dawarich_app:
    image: 'freikin/dawarich:latest'
    container_name: dawarich_app
    volumes:
      - 'dawarich_public:/var/app/public'
      - 'dawarich_watched:/var/app/tmp/imports/watched'
    networks:
      - dawarich
    stdin_open: true
    tty: true
    entrypoint: web-entrypoint.sh
    command: ['bin/rails', 'server', '-p', '3000', '-b', '::']
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: 'redis://dawarich_redis:6379/0'
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      MIN_MINUTES_SPENT_IN_CITY: 60

      APPLICATION_HOST: dawarich.cooldomain.com
      APPLICATION_HOSTS: dawarich.cooldomain.com
      TIME_ZONE: Europe/Berlin
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
      PHOTON_API_HOST: photon.komoot.io
      PHOTON_API_USE_HTTPS: true
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: 0.0.0.0
      PROMETHEUS_EXPORTER_PORT: 9394
      ENABLE_TELEMETRY: false
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: '5'
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget -qO - http://127.0.0.1:3000/api/v1/health | grep -q ''"status"\s*:\s*"ok"'''
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
      dawarich_redis:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 4G
  dawarich_sidekiq:
    image: 'freikin/dawarich:latest'
    container_name: dawarich_sidekiq
    volumes:
      - 'dawarich_public:/var/app/public'
      - 'dawarich_watched:/var/app/tmp/imports/watched'
    networks:
      - dawarich
    stdin_open: true
    tty: true
    entrypoint: sidekiq-entrypoint.sh
    command: ['bundle', 'exec', 'sidekiq']
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: 'redis://dawarich_redis:6379/0'
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      APPLICATION_HOST: dawarich.cooldomain.com
      APPLICATION_HOSTS: dawarich.cooldomain.com
      BACKGROUND_PROCESSING_CONCURRENCY: 10
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
      PHOTON_API_HOST: photon.komoot.io
      PHOTON_API_USE_HTTPS: true
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: dawarich_app
      PROMETHEUS_EXPORTER_PORT: 9394
      ENABLE_TELEMETRY: false
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: '5'
    healthcheck:
      test:
        - CMD-SHELL
        - 'bundle exec sidekiqmon processes | grep $${HOSTNAME}'
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
      dawarich_redis:
        condition: service_healthy
        restart: true
      dawarich_app:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 4G
volumes:
  dawarich_db_data: null
  dawarich_shared: null
  dawarich_public: null
  dawarich_watched: null

```
