### ISSUE TITLE
Docker compose for Synology failed

### ISSUE THREAD

**Issue by mcwieger** [Freika/dawarich#756]
**OS & Hardware**
Synology 1520+

**Version**
Latest (0.23.5?)

**Describe the bug**
Dawarich_app cannot connect to dawarich_db. Following error is given:

```
psql: error: connection to server on socket "/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
Postgres is unavailable - retrying...
	Is the server running locally and accepting connections on that socket?
```

Dawarich_db log shows the following:

`listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"`

Could it be that the directories don't match?

**To Reproduce**
Create a stack with the following docker_compose.yml and .env variables:

```
services:
  dawarich_redis:
    image: redis:7.0-alpine
    container_name: dawarich_redis
    command: redis-server
    restart: unless-stopped
    volumes:
      - /volume1/docker/dawarich/redis:/var/shared/redis

  dawarich_db:
    image: postgres:14.2-alpine
    container_name: dawarich_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - /volume1/docker/dawarich/db:/var/lib/postgresql/data
      - /volume1/docker/dawarich/shared:/var/shared

  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    depends_on:
      - dawarich_db
      - dawarich_redis
    stdin_open: true
    tty: true
    entrypoint: web-entrypoint.sh
    command: ['bin/dev']
    restart: unless-stopped
    volumes:
      - /volume1/docker/dawarich/public:/var/app/public
    ports:
      - 9020:3000

  dawarich_sidekiq:
    image: freikin/dawarich:latest
    container_name: dawarich_sidekiq
    depends_on:
      - dawarich_db
      - dawarich_redis
      - dawarich_app
    entrypoint: sidekiq-entrypoint.sh
    command: ['sidekiq']
    restart: unless-stopped
    volumes:
      - /volume1/docker/dawarich/public:/var/app/public
```

```
###################################################################################
# Dawarich
###################################################################################

RAILS_ENV=development
MIN_MINUTES_SPENT_IN_CITY=60
APPLICATION_HOSTS=localhost
TIME_ZONE=Europe/Amsterdam
BACKGROUND_PROCESSING_CONCURRENCY=10
APPLICATION_PROTOCOL=http
DISTANCE_UNIT=km
REVERSE_GEOCODING_ENABLED=true
PHOTON_API_HOST=ph.spieghel.myds.me    

###################################################################################
# Database
###################################################################################

DATABASE_HOST=dawarich_db
DATABASE_USERNAME=postgres
DATABASE_PASSWORD=password
DATABASE_NAME=dawarich_development

###################################################################################
# Redis
###################################################################################
```

REDIS_URL=redis://dawarich_redis:6379/0

**Expected behavior**
Stack should start and connection can be made to :9020.

**Screenshots**
N/A

**Logs**
See above

**Additional context**
Tested with both existing db as well as empty db. Both failed.

**Comment by mistertoi** [comment]
Maybe this can help you. I wrote my docker-compose by combining parts from Marius and the official Synology compose. The containers are running, and internally everything is fine. My struggle is that I can't manage to import the data from Immich. But give it a try with this

```
services:
  dawarich_redis:
    image: redis:7.0-alpine
    container_name: dawarich_redis
    command: redis-server
    restart: unless-stopped
    volumes:
      - /volume1/docker/dawarich/redis:/data:rw
    environment:
      vm.overcommit_memory: 1
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 60s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      internal:
        ipv4_address: 172.36.0.2
  
  dawarich_db:
    image: postgres:14.2-alpine
    container_name: dawarich_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - /volume1/docker/dawarich/db_data:/var/lib/postgresql/data:rw
      - /volume1/docker/dawarich/db_shared:/var/shared:rw
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d dawarich_development" ]
      interval: 60s
      retries: 5
      start_period: 30s
      timeout: 10s
    # command: postgres -c config_file=/etc/postgresql/postgresql.conf # Use custom config, uncomment if you want to use a custom config
    shm_size: 1GB
    networks:
      internal:
        ipv4_address: 172.36.0.3
  
  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    volumes:
      - /volume1/docker/dawarich/public:/var/app/public:rw
      - /volume1/docker/dawarich/watched:/var/app/tmp/imports/watched:rw
    networks:
      internal:
        ipv4_address: 172.36.0.4
      mvl:
        ipv4_address: 192.168.178.247
    ports:
      - 3639:3000
      # - 32568:3000
      # - 9394:9394 # Prometheus exporter, uncomment if needed
    stdin_open: true
    tty: true
    entrypoint: web-entrypoint.sh
    command: ['bin/rails', 'server', '-p', '3000', '-b', '::']
    restart: unless-stopped
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      SECRET_KEY_BASE: SomeVerlyLongRandomKey
      APPLICATION_HOSTS: ${APPLICATION_HOSTS}
      MIN_MINUTES_SPENT_IN_CITY: 60
      TIME_ZONE: Europe/Berlin
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
      # PROMETHEUS_EXPORTER_ENABLED: true
      # PROMETHEUS_EXPORTER_HOST: localhost
      # PROMETHEUS_EXPORTER_PORT: 9394
      ENABLE_TELEMETRY: false # More on telemetry: https://dawarich.app/docs/tutorials/telemetry
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO - http://127.0.0.1:3000/api/v1/health | grep -q '\"status\"\\s*:\\s*\"ok\"'" ]
      interval: 60s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_started
      dawarich_redis:
        condition: service_started
  
  dawarich_sidekiq:
    image: freikin/dawarich:latest
    container_name: dawarich_sidekiq
    volumes:
      - /volume1/docker/dawarich/public:/var/app/public:rw
      - /volume1/docker/dawarich/watched:/var/app/tmp/imports/watched:rw
    networks:
      internal:
        ipv4_address: 172.36.0.5
    stdin_open: true
    tty: true
    entrypoint: sidekiq-entrypoint.sh
    command: ['sidekiq']
    restart: on-failure
    environment:
      RAILS_ENV: ${RAILS_ENV}
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      SECRET_KEY_BASE: SomeVerlyLongRandomKey
      APPLICATION_HOSTS: ${APPLICATION_HOSTS}
      BACKGROUND_PROCESSING_CONCURRENCY: 10
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
      # PROMETHEUS_EXPORTER_ENABLED: true
      # PROMETHEUS_EXPORTER_HOST: localhost
      # PROMETHEUS_EXPORTER_PORT: 9394
      ENABLE_TELEMETRY: false # More on telemetry: https://dawarich.app/docs/tutorials/telemetry
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "bundle exec sidekiqmon processes | grep $${HOSTNAME}" ]
      interval: 60s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_started
      dawarich_redis:
        condition: service_started
      dawarich_app:
        condition: service_started

networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.36.0.0/16
          gateway: 172.36.0.1
          ip_range: 172.36.0.1/24
  
  mvl:
    external: true

volumes:
  dawarich_db_data:
  dawarich_shared:
  dawarich_public:
  dawarich_watched:

```
