### ISSUE TITLE
Dawarich_app after update unhealthy

### ISSUE THREAD

**Issue by m3tc0n** [Freika/dawarich#811]
Hi, after the latest update my dawarich instance is not running anymore. 

When I try the redeploy the stack, I get an error which is saying the dawarich_app is unhealthy. 

This is my stack. I could use some help tot solve this.

```
services:
# dawarich_redis
  dawarich_redis:
    image: redis:7.4-alpine
    container_name: dawarich_redis
    command: redis-server
    networks:
      dawarich:
        ipv4_address: 172.27.0.2
    volumes:
      - /DATA/AppData/dawarich/dawarich_redis_data:/var/shared/redis
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

# dawarich_db
  dawarich_db:
    image: postgres:17-alpine
    shm_size: 1G
    container_name: dawarich_db
    volumes:
      - /DATA/AppData/dawarich/dawarich_db_data:/var/lib/postgresql/data
    networks:
      dawarich:
        ipv4_address: 172.27.0.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dawarich_production
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

# dawarich_app
  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    volumes:
      - /DATA/AppData/dawarich/dawarich_public:/var/app/public
      - /DATA/AppData/dawarich/dawarich_watched:/var/app/tmp/imports/watched
    networks:
      dawarich:
        ipv4_address: 172.27.0.4
    ports:
      - 3097:3000
      # - 9394:9394 # Prometheus exporter, uncomment if needed
    stdin_open: true
    tty: true
    entrypoint: web-entrypoint.sh
    command: ['bin/rails', 'server', '-p', '3000', '-b', '::']
    restart: on-failure
    environment:
      RAILS_ENV: production
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_production
      MIN_MINUTES_SPENT_IN_CITY: 60
      APPLICATION_HOSTS: localhost,::1,127.0.0.1,timeline.[mydomain],192.168.30.3
      TIME_ZONE: Europe/Amsterdam
      APPLICATION_PROTOCOL: http
      PHOTON_API_HOST: photon:2322
      PHOTON_API_USE_HTTPS: false
      DISTANCE_UNIT: km
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: 0.0.0.0
      PROMETHEUS_EXPORTER_PORT: 9394
      SECRET_KEY_BASE: 1234567890
      RAILS_LOG_TO_STDOUT: "true"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO - http://127.0.0.1:3000/api/v1/health | grep -q '\"status\"\\s*:\\s*\"ok\"'" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
      dawarich_redis:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '0.50'    # Limit CPU usage to 50% of one core
          memory: '2G'    # Limit memory usage to 2GB

# dawarich_sidekiq
  dawarich_sidekiq:
    image: freikin/dawarich:latest
    container_name: dawarich_sidekiq
    volumes:
      - /DATA/AppData/dawarich/dawarich_public:/var/app/public
      - /DATA/AppData/dawarich/dawarich_watched:/var/app/tmp/imports/watched
    networks:
      dawarich:
        ipv4_address: 172.27.0.5
    stdin_open: true
    tty: true
    entrypoint: sidekiq-entrypoint.sh
    command: ['bundle', 'exec', 'sidekiq']
    restart: on-failure
    environment:
      RAILS_ENV: production
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_production
      APPLICATION_HOSTS: localhost,::1,127.0.0.1,timeline.[mydomain],192.168.30.3
      BACKGROUND_PROCESSING_CONCURRENCY: 10
      APPLICATION_PROTOCOL: http
      PHOTON_API_HOST: photon:2322

      PHOTON_API_USE_HTTPS: false
      DISTANCE_UNIT: km
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: dawarich_app
      PROMETHEUS_EXPORTER_PORT: 9394
      SECRET_KEY_BASE: 1234567890
      RAILS_LOG_TO_STDOUT: "true"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "bundle exec sidekiqmon processes | grep $${HOSTNAME}" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
      dawarich_redis:
        condition: service_healthy
        restart: true
      dawarich_app:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '0.50'    # Limit CPU usage to 50% of one core
          memory: '2G'    # Limit memory usage to 2GB

# photon
  photon:
    image: rtuszik/photon-docker:latest
    container_name: photon
    restart: unless-stopped
    networks:
      dawarich:
        ipv4_address: 172.27.0.6
    ports:
      - "2322:2322"
    environment:
      - COUNTRY_CODE=nl
      - UPDATE_INTERVAL=24h
      - LOG_LEVEL=INFO
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /DATA/AppData/photon/photon_data:/photon/photon_data

networks:
  dawarich:
    name: dawarich
    driver: bridge
    ipam:
     config:
       - subnet: 172.27.0.0/16
         gateway: 172.27.0.1
```
