### ISSUE TITLE
Visited cities and countries are not displayed

### ISSUE THREAD

**Issue by marwonn** [Freika/dawarich#913]
**OS & Hardware**
Docker on DebianVM virtualised with Proxmox

**Version**
Darwarich 0.24.1

**Describe the bug**
Under 'Stats' only 'Total distance' and 'Geopoints tracked' are displayed. Visited cities and countries are missing.
I have 12,946 imported points but 0 reverse geocoded points. 
When I go to 'Settings' --> 'Background jobs' and click on 'Start Reverse Geocoding' nothing happens.

Did I miss something in my configuration?

**Docker compose config**
**OS & Hardware**
Docker on DebianVM virtualised with Proxmox

**Version**
Darwarich 0.24.1

**Describe the bug**
Under 'Stats' only 'Total distance' and 'Geopoints tracked' are displayed. Visited cities and countries is missing.
I have 12,946 imported point but 0 reverse geocoded points. 
When I go to 'Settings' --> 'Background jobs' and click on 'Start Reverse Geocoding' nothing happens.

Did I miss something in my configuration?

**Docker compose config**
```
networks:
  dawarich:
services:
  dawarich_redis:
    image: redis:7.0-alpine
    container_name: dawarich_redis
    command: redis-server
    networks:
      - dawarich
    volumes:
      - $DATADIR/dawarich_shared:/data
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  dawarich_db_pg_17:
    image: postgis/postgis:17-3.5-alpine
    shm_size: 1G
    container_name: dawarich_db_pg_17
    volumes:
      - $DATADIR/dawarich_db_data_pg_17:/var/lib/postgresql/data
      - $DATADIR/dawarich_shared:/var/shared
    networks:
      - dawarich
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PASS
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d dawarich_development" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  dawarich_app:
    image: freikin/dawarich:0.24.1
    container_name: dawarich_app
    volumes:
      - $DATADIR/dawarich_public:/var/app/public
      - $DATADIR/dawarich_watched:/var/app/tmp/imports/watched
    networks:
      - dawarich
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    entrypoint: web-entrypoint.sh
    command: ['bin/rails', 'server', '-p', '3000', '-b', '::']
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db_pg_17
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: PASS
      DATABASE_NAME: dawarich_development
      MIN_MINUTES_SPENT_IN_CITY: 60
      APPLICATION_HOSTS: localhost
      TIME_ZONE: Europe/Berlin
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: 0.0.0.0
      PROMETHEUS_EXPORTER_PORT: 9394
      ENABLE_TELEMETRY: false # More on telemetry: https://dawarich.app/docs/tutorials/telemetry
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO - http://127.0.0.1:3000/api/v1/health | grep -q '\"status\"\\s*:\\s*\"ok\"'" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db_pg_17:
        condition: service_healthy
        restart: true
      dawarich_redis:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '0.50'    # Limit CPU usage to 50% of one core
          memory: '4G'    # Limit memory usage to 4GB
  dawarich_sidekiq:
    image: freikin/dawarich:latest
    container_name: dawarich_sidekiq
    volumes:
      - $DATADIR/dawarich_public:/var/app/public
      - $DATADIR/dawarich_watched:/var/app/tmp/imports/watched
    networks:
      - dawarich
    stdin_open: true
    tty: true
    entrypoint: sidekiq-entrypoint.sh
    command: ['sidekiq']
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db_pg_17
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: PASS
      DATABASE_NAME: dawarich_development
      APPLICATION_HOSTS: http://IP
      BACKGROUND_PROCESSING_CONCURRENCY: 10
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: dawarich_app
      PROMETHEUS_EXPORTER_PORT: 9394
      ENABLE_TELEMETRY: false # More on telemetry: https://dawarich.app/docs/tutorials/telemetry
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "bundle exec sidekiqmon processes | grep $${HOSTNAME}" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db_pg_17:
        condition: service_healthy
        restart: true
      dawarich_redis:
        condition: service_healthy
        restart: true
      dawarich_app:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '0.50'    # Limit CPU usage to 50% of one core
          memory: '4G'    # Limit memory usage to 4GB

volumes:
  dawarich_db_data:
  dawarich_shared:
  dawarich_public:
  dawarich_watched:
  dawarich_db_data_pg_17:
```
