### ISSUE TITLE
Moving to a new machine gives `Error response from daemon: failed to create task for container: ...`

### ISSUE THREAD

**Issue by marinegor** [Freika/dawarich#950]
**OS & Hardware**
```bash
marinegor@homepc:~$ uname -a
Linux homepc 6.11.0-19-generic #19~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Feb 17 11:51:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

**Version**
I was running `dawarich:latest`, moved to a new machine, and tried running `latest` or `0.24.1`

**Describe the bug**
When running `docker compose up`, I get:

```
marinegor@homepc:~/nixos/containers/dawarich$ docker compose up --force-recreate
[+] Running 4/4
 ✔ Container dawarich_sidekiq  Recreated                                                                                                                              0.3s 
 ✔ Container dawarich_app      Recreated                                                                                                                              0.3s 
 ✔ Container dawarich_redis    Recreated                                                                                                                              0.2s 
 ✔ Container dawarich_db       Recreated                                                                                                                              0.1s 
Attaching to dawarich_app, dawarich_db, dawarich_redis, dawarich_sidekiq
dawarich_redis    | 1:C 16 Mar 2025 19:57:07.762 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
dawarich_redis    | 1:C 16 Mar 2025 19:57:07.762 # Redis version=7.0.15, bits=64, commit=00000000, modified=0, pid=1, just started
dawarich_redis    | 1:C 16 Mar 2025 19:57:07.762 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
dawarich_redis    | 1:M 16 Mar 2025 19:57:07.763 * monotonic clock: POSIX clock_gettime
dawarich_redis    | 1:M 16 Mar 2025 19:57:07.763 * Running mode=standalone, port=6379.
dawarich_redis    | 1:M 16 Mar 2025 19:57:07.763 # Server initialized
dawarich_redis    | 1:M 16 Mar 2025 19:57:07.763 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
dawarich_redis    | 1:M 16 Mar 2025 19:57:07.763 * Loading RDB produced by version 7.0.15
dawarich_redis    | 1:M 16 Mar 2025 19:57:07.763 * RDB age 0 seconds
dawarich_redis    | 1:M 16 Mar 2025 19:57:07.763 * RDB memory usage when created 8.93 Mb
dawarich_db       | 
dawarich_db       | PostgreSQL Database directory appears to contain a database; Skipping initialization
dawarich_db       | 
dawarich_redis    | 1:M 16 Mar 2025 19:57:07.772 * Done loading RDB, keys loaded: 252, keys expired: 0.
dawarich_redis    | 1:M 16 Mar 2025 19:57:07.772 * DB loaded from disk: 0.009 seconds
dawarich_redis    | 1:M 16 Mar 2025 19:57:07.772 * Ready to accept connections
dawarich_db       | 2025-03-16 19:57:07.788 UTC [1] LOG:  starting PostgreSQL 14.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit
dawarich_db       | 2025-03-16 19:57:07.789 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
dawarich_db       | 2025-03-16 19:57:07.789 UTC [1] LOG:  listening on IPv6 address "::", port 5432
dawarich_db       | 2025-03-16 19:57:07.790 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
dawarich_db       | 2025-03-16 19:57:07.793 UTC [21] LOG:  database system was shut down at 2025-03-16 19:57:07 UTC
dawarich_db       | 2025-03-16 19:57:07.799 UTC [1] LOG:  database system is ready to accept connections
Gracefully stopping... (press Ctrl+C again to force)
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: exec: "dev-entrypoint.sh": executable file not found in $PATH: unknown
```

And other containers on the same machine run without problems.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If applicable, add logs from containers `dawarich_app` and `dawarich_sidekiq` to help explain your problem.

**Additional context**

my `docker-compose.yml` (mostly copied from the tutorial)

```
services:
  dawarich_redis:
    image: redis:7.0-alpine
    container_name: dawarich_redis
    command: redis-server
    networks:
      - caddy_caddynet
    volumes:
      - /mnt/ssd-storage/docker-volumes/dawarich/dawarich_shared:/data
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  dawarich_db:
    image: postgres:14.2-alpine
    shm_size: 1G
    container_name: dawarich_db
    volumes:
      - /mnt/ssd-storage/docker-volumes/dawarich/dawarich_db_data:/var/lib/postgresql/data
      - /mnt/ssd-storage/docker-volumes/dawarich/dawarich_shared:/var/shared
      # - ./postgresql.conf:/etc/postgresql/postgresql.conf # Optional, uncomment if you want to use a custom config
    networks:
      - caddy_caddynet
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d dawarich_development" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    # command: postgres -c config_file=/etc/postgresql/postgresql.conf # Use custom config, uncomment if you want to use a custom config
  dawarich_app:
    image: freikin/dawarich
    container_name: dawarich_app
    volumes:
      - /mnt/ssd-storage/docker-volumes/dawarich/dawarich_gem_cache_app:/usr/local/bundle/gems
      - /mnt/ssd-storage/docker-volumes/dawarich/dawarich_public:/var/app/public
      - /mnt/ssd-storage/docker-volumes/dawarich/dawarich_watched:/var/app/tmp/imports/watched
    networks:
      - caddy_caddynet
    ports:
      - 3000:3000
      # - 9394:9394 # Prometheus exporter, uncomment if needed
    stdin_open: true
    tty: true
    entrypoint: dev-entrypoint.sh
    command: ['bin/dev']
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      MIN_MINUTES_SPENT_IN_CITY: 60
      APPLICATION_HOST: localhost
      APPLICATION_HOSTS: localhost,dawarich.nwhl.uk
      TIME_ZONE: Europe/Amsterdam
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
      PHOTON_API_HOST: photon.komoot.io
      PHOTON_API_USE_HTTPS: true
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: 0.0.0.0
      PROMETHEUS_EXPORTER_PORT: 9394
      ENABLE_TELEMETRY: false # More on telemetry: https://dawarich.app/docs/tutorials/telemetry
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO - http://127.0.0.1:3000/api/v1/health | grep -q '\"status\"\\s*:\\s*\"ok\"'" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
      dawarich_redis:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '0.50'    # Limit CPU usage to 50% of one core
          memory: '2G'    # Limit memory usage to 2GB
  dawarich_sidekiq:
    image: freikin/dawarich
    container_name: dawarich_sidekiq
    volumes:
      - /mnt/ssd-storage/docker-volumes/dawarich/dawarich_gem_cache_sidekiq:/usr/local/bundle/gems
      - /mnt/ssd-storage/docker-volumes/dawarich/dawarich_public:/var/app/public
      - /mnt/ssd-storage/docker-volumes/dawarich/dawarich_watched:/var/app/tmp/imports/watched
    networks:
      - caddy_caddynet
    stdin_open: true
    tty: true
    entrypoint: dev-entrypoint.sh
    command: ['sidekiq']
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      APPLICATION_HOST: localhost
      APPLICATION_HOSTS: localhost,dawarich.nwhl.uk
      BACKGROUND_PROCESSING_CONCURRENCY: 10
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
      PHOTON_API_HOST: photon.komoot.io
      PHOTON_API_USE_HTTPS: true
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: dawarich_app
      PROMETHEUS_EXPORTER_PORT: 9394
      ENABLE_TELEMETRY: false # More on telemetry: https://dawarich.app/docs/tutorials/telemetry
      REVERSE_GEOCODING_ENABLED: true
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "bundle exec sidekiqmon processes | grep $${HOSTNAME}" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
      dawarich_redis:
        condition: service_healthy
        restart: true
      dawarich_app:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '0.50'    # Limit CPU usage to 50% of one core
          memory: '2G'    # Limit memory usage to 2GB

networks:
  caddy_caddynet:
    external: true
```
